### ISSUE TITLE
docker怎么配置nginx转发到swoole服务

### ISSUE THREAD

**Issue by ibit2** [swooletw/laravel-swoole#103]
docker怎么配置nginx转发到swoole服务

**Comment by albertcht** [comment]
If you're asking a workable Nginx config. Please see [Nginx-Configuration](https://github.com/swooletw/laravel-swoole/wiki/9.-Nginx-Configuration). If you're asking a docker-related question.  It's been out of the scope of this package. 

Also please read [Issues Guideline](https://github.com/swooletw/laravel-swoole/wiki/Z2.-Issues-Guideline) before opening an issue, thanks.

**Comment by beartistic** [comment]
+1
