### ISSUE TITLE
Onopen无法调用

### ISSUE THREAD

**Issue by junshenshi** [swooletw/laravel-swoole#104]
Please answer these questions before submitting your issue. Thanks!

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
PHP

`PHP 7.2.7-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jun 22 2018 08:44:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.7-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies`

swoole

`swoole support => enabled
Version => 4.0.2
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608`

2. Please provide your Laravel/Lumen version.

laravel 5.5

3. Which release version of this package are you using?

2.4.1

4. What did you do? If possible, provide a recipe for reproducing the error.
使用最新版无法调用自定义的Handler的onopen方法，

使用2.2.1的时候是正常调用

5. What did you expect to see?

希望能正常调用onopen

6. What did you see instead?

**Comment by junshenshi** [comment]
![image](https://user-images.githubusercontent.com/19427115/42982713-30abba9c-8c15-11e8-84c0-dccf3a523233.png)
![image](https://user-images.githubusercontent.com/19427115/42982731-42a45e2a-8c15-11e8-9ae0-937729e74600.png)

**Comment by junshenshi** [comment]
$this->sandbox->enable();

**Comment by junshenshi** [comment]
@albertcht  嗨
如何不使用 sandbox 呢？
因为重置 LaravelApp的时候 在
rebindRouterContainer 方法里面出现错误，导致程序终止

没有使用nginx反向代理，也没有配swoole的代理，只使用服务器是使用apache2

我是使用token来传递UID，才连接地址上加上了参数，
前端连接地址
wss://www.xxx.com/wss?user_id=eyJpdiI6IjBTMld3S3RVSzhWRG5cL2tFN3dZNU5nPT0iLCJ2YWx1ZSI6IndnY28weXdsV3FVZzhSR2lZYVh3a2c9PSIsIm1hYyI6ImVkNzQzNWZmNTliNTgyYzBjMzRmMGRiZTRhZDc0ZTMxMTFmMTMyYWVmMDliMDg3MGUxZDkwMjcwMzUzYzIzMGIifQ==

最终报错的地址是：
`Symfony\Component\HttpKernel\Exception\NotFoundHttpException 
in /var/www/test.ucpin.com/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:179
Stack trace:
#0 /var/www/test.ucpin.com/vendor/swooletw/laravel-swoole/src/Server/Sandbox.php(251): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/test.ucpin.com/vendor/swooletw/laravel-swoole/src/Server/Sandbox.php(266): Illuminate\Routing\Router->SwooleTW\Http\Server\{closure}()
#2 /var/www/test.ucpin.com/vendor/swooletw/laravel-swoole/src/Server/Sandbox.php(141): SwooleTW\Http\Server\Sandbox->rebindRouterContainer(Object(Illuminate\Foundation\Application))
#3 /var/www/test.ucpin.com/vendor/swooletw/laravel-swoole/src/Server/Sandbox.php(324): SwooleTW\Http\Server\Sandbox->resetLaravelApp(Object(Illuminate\Foundation\Application))
#4 /var/www/test.ucpin.com/vendor/swooletw/laravel-swoole/src/Websocket/CanWebsocket.php(69): SwooleTW\Http\Server\Sandbox->enable()
#5 {main}`

**Comment by albertcht** [comment]
Hi @junshenshi ,

Thanks for your report, I've marked this issue as a bug. I'm going to fix it in the next release version.

**Comment by albertcht** [comment]
Hi @junshenshi ,

What if you connect your ws server with the address: `wss://www.xxx.com/?user_id=...`?

**Comment by junshenshi** [comment]
@albertcht  
嗯 是链接到该地址

 ws://www.xxx.com/?user_id=token

希望给个开关来控制本包
设置使用socket服务 或 设置使用server服务

**Comment by junshenshi** [comment]
![image](https://user-images.githubusercontent.com/19427115/42987461-04392c08-8c2c-11e8-89ae-5bef051b3b7b.png)
debug

apache 服务器
JS链接地址 ws://www.xxx.com/?user_id=token
 2.4.1包
laravel 5.5
swoole 4.0

**Comment by junshenshi** [comment]
![image](https://user-images.githubusercontent.com/19427115/42987637-8ac9ff40-8c2c-11e8-948a-e21cd7248bb2.png)

**Comment by junshenshi** [comment]
@albertcht 嗨

**Comment by junshenshi** [comment]
@albertcht 嗨
js链接地址： ws://www.xxx.com/?user_id=token
差异地址
 vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php   164 line
 $route = $this->matchAgainstRoutes($routes, $request);
apache+wss情况下 $route 为假
nginx+ws情况下  $route 为真

可能需要您把本包修改下

希望能改成不需要反向代理swoole都能使用
兼容apache服务器

**Comment by albertcht** [comment]
Hi @junshenshi ,

How do you run your WS server on Apache?

**Comment by junshenshi** [comment]
嗨@albertcht
没有使用swoole作为http服务器 只是使用websocket
这样运行 php artisan swoole:http start

还有一个小小的建议，
room的名字请在wiki表明不要以下划线命名
或者使用另外一种存储方法不要使用这样来获取uid
count($explode = explode('uid_', $room)) === 2

**Comment by albertcht** [comment]
This issue will be fixed in the next release version.
