### ISSUE TITLE
不能使用echo，var_dump函数？有没有兼容的办法？

### ISSUE THREAD

**Issue by Jackfinal** [swooletw/laravel-swoole#107]
Please answer these questions **in English** before submitting your issue. Thanks!

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
PHP 7.1.19 (cli) (built: Jul 13 2018 17:31:46) ( NTS )

2. Please provide your Laravel/Lumen version.
Laravel5.6

3. Which release version of this package are you using?

4. What did you do? If possible, provide a recipe for reproducing the error.

5. What did you expect to see?

6. What did you see instead?

**Comment by albertcht** [comment]
Please read [Issues Guideline](https://github.com/swooletw/laravel-swoole/wiki/Z2.-Issues-Guideline) before opening an issue, thanks.

**Comment by albertcht** [comment]
Currently you can `var_dump` or `echo` a string if you don't return anything in response.  For example:
```php
Route::get('/', function () {
    var_dump('test');
});
```
