### ISSUE TITLE
如何在laravel自带的artisan command里使用websocket？

### ISSUE THREAD

**Issue by mrzxy** [swooletw/laravel-swoole#109]
Make sure you read **Issues Guideline** and answer these questions **in English** before submitting your issue. Thanks!
(Those issues which violate the guideline will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

PHP 7.2.4

2. Please provide your Laravel/Lumen version.

laravel5.61

3. Which release version of this package are you using?

2.4.1

4. What did you do? If possible, provide a recipe for reproducing the error.

5. What did you expect to see?

![image](https://user-images.githubusercontent.com/11501927/43354331-9d747d40-927c-11e8-9dd4-db68cdf750d7.png)

6. What did you see instead?

**Comment by albertcht** [comment]
No, you can only push messages to clients running in swoole websocket server.

**Comment by mrzxy** [comment]
# @albertcht 那如何实现消息重发机制呢？ 我的思路是这样的，通过crontab每秒检测消息是否发送成功，

**Comment by albertcht** [comment]
This is impossible to send messages to disconnected clients, and currently you can't get failed pushes with this package. The only way to achieve your goal is to bind fds to user ids, and your frontend side needs to response a success message back to server. After that you can trigger the server to send messages to these failed users. (You can design an Http API for this trigger.)

**Comment by junshenshi** [comment]
@mrzxy 嘿 你那边解决这个场景了？
我这边也需要主动发送websocket给用户
