### ISSUE TITLE
Very serious bugs were found??

### ISSUE THREAD

**Issue by chinawilon** [swooletw/laravel-swoole#110]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
PHP 7.1.7 
Version => 4.0.1

2. Please provide your Laravel/Lumen version.
lumen => v5.6

3. Which release version of this package are you using?
dev-master

4. What did you do? If possible, provide a recipe for reproducing the error.

> App\Facdes\Api.php
```php
<?php

namespace App\Facades;

use Illuminate\Support\Facades\Facade;

class Api extends Facade
{
    /**
     * Get the registered name of the component.
     *
     * @return string
     */
    protected static function getFacadeAccessor()
    {
        return 'api';
    }
}
```
> App\Providers\ApiServiceProvider.php
```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use App\Services\ApiService;

class ApiServiceProvider extends ServiceProvider
{
    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton('api', function ($app) {
            return $app->make(ApiService::class);
        });
    }
}

```

> App\Providers\AppServiceProvider.php
```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use App\Facades\Api;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function boot()
    {
        Api::initialization(); //Api Do some initialization
    }
}

```

When the request  is received, the initialization work is not done !!
Through analysis,  that it is caused by the ```$resolvedInstance``` attribute of the facade. It's a static attribute, So when the worker starts up, The facade returns the previous instance object, so that the worker app is not initialized in the worker.

I think the ```$resolvedInstance``` attribute can be cleared in the worker process when it start.

**Comment by albertcht** [comment]
Do you mean your `api` instance is only resolved in the first time? Do you want your `api` instance initialized in every request? If not, please give me more details about your questions.

**Comment by chinawilon** [comment]
```php
    /**
     * Set laravel snapshot to container and facade.
     */
    public function enable()
    {
        $this->enabled = true;
        $this->setInstance($app = $this->getLaravelApp());
        $this->resetLaravelApp($app);
    }

    /**
     * Replace app's self bindings.
     */
    protected function setInstance($application)
    {
        $application->instance('app', $application);
        $application->instance(Container::class, $application);

        if ($this->isFramework('lumen')) {
            $application->instance(LumenApplication::class, $application);
        }

        Container::setInstance($application);
/*
* Here we clear the parsing instance of the facade,
* If a facade is used in the provider, it is cleared out, causing serious problems.
* Because the $resovledInstance attribute of the facade is static, the app in the current worker does not 
* actually make, so the next time you use a facade, you will call the app in the worker to make it again
*/
        Facade::clearResolvedInstances(); 
        Facade::setFacadeApplication($application);
    }
```

**Comment by albertcht** [comment]
Sorry, I'm still confused about what your question is.

> When the request is received, the initialization work is not done !!

So do you want `Api::initialization()` to be called in every request?

> So when the worker starts up, The facade returns the previous instance object, so that the worker app is not initialized in the worker.

I can't understand the meaning of this sentence.

> Because the $resovledInstance attribute of the facade is static, the app in the current worker does not actually make, so the next time you use a facade, you will call the app in the worker to make it again.

Facade in Laravel is just a bridge for users to get the instance in current app container statically. I can't understand the meaning of this sentence.

Can you make your question more clear or describe it in mandarin if you feel more comfortable?

**Comment by chinawilon** [comment]
多谢，我英语不怎么样，只能用普通话来表达了。

现在的问题是，如果我们在provider中使用了类似Api这种自定义的Facade的话，会出现一个很严重bug。

在laravel-swoole中虽然worker每次启动Application都重新include下```bootstrap/app.php```，但是如果这个文件的provider使用了自定义facade会出现问题，原因是facade类使用了一个```static```属性的```$resolvedInstance```来保存它resolved过的类，这个就会导致在worker进程中的api facade返回的是上一次master/manager进程中解析过的那个类，它并没有去触发worker中的容器获取。

```php
    /**
     * Resolve the facade root instance from the container.
     *
     * @param  string|object  $name
     * @return mixed
     */
    protected static function resolveFacadeInstance($name)
    {
        if (is_object($name)) {
            return $name;
        }

        if (isset(static::$resolvedInstance[$name])) {
            return static::$resolvedInstance[$name];
        }

    //在worker中并没有执行这一步，因为这个属性是static，它的manager进程已经解析过了
        return static::$resolvedInstance[$name] = static::$app[$name]; 
    }
```

但是接下来laravel-swoole做了一个清除facade的```$resolvedInstacen```属性操作。
```php
    /**
     * Replace app's self bindings.
     */
    protected function setInstance($application)
    {
        $application->instance('app', $application);
        $application->instance(Container::class, $application);

        if ($this->isFramework('lumen')) {
            $application->instance(LumenApplication::class, $application);
        }

        Container::setInstance($application);
        Facade::clearResolvedInstances(); //就是这里
        Facade::setFacadeApplication($application);
    }
```

那么可以看到，当前worker中的容器并没有实例化过api这种自定义的facade，那么下次在worker进程中使用api这种facade的时候，worker中的app会真正去解析它，这就导致了在provider中的初始化动作失效了。

**Comment by albertcht** [comment]
Only the instances listed in `$resolves` of Sandbox will be pre-resolved and shared with the sandbox container. In your case, you can simply add your api provider to `providers` in `config/swoole_http.php` to make it booted in every request.

**Comment by albertcht** [comment]
I close this issue first because this is how it works, instead of a bug. Also, please **DO NOT** use a misleading title before you confirm an issue you submitted is a bug.
