### ISSUE TITLE
About Websocket::on('test', 'ExampleController@method'); 

### ISSUE THREAD

**Issue by adon988** [swooletw/laravel-swoole#111]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

PHP 7.1.18

Swoole Version: 4.0.3

2. Please provide your Laravel/Lumen version.

Laravel 5.6

3. Which release version of this package are you using?

e5f1cf7
(2018-07-30 clone :last version)

4. What did you do? If possible, provide a recipe for reproducing the error.

When I create a ExampleController, and test emit.. but nothing happened.

routes/websocket.php

```
Websocket::on('test', 'ExampleController@index');
```

Here is my controller

ExampleController.php
```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ExampleController extends Controller
{
    public function index($websocket, $data){
        
        $websocket->emit("message", "Hello this is message from ExampleController.");
        
    }
}
```

5. What did you expect to see?

client emit to test, and socket.on('message') should get server emit response message. but nothing happened...

```js
socket.emit('test', 'from client');

socket.on('message', function(data){console.log(data);});
```
6. What did you see instead?

**Comment by albertcht** [comment]
Hi @adon988 ,

Did you resolve the problem yet?

**Comment by adon988** [comment]
Yes, just forget add Namespace~ [issue49](https://github.com/swooletw/laravel-swoole/issues/49)
