### ISSUE TITLE
Support more sock type unix socket stream and dgram 

### ISSUE THREAD

**Issue by to2false** [swooletw/laravel-swoole#114]
I want to custom socket type
https://github.com/swooletw/laravel-swoole/blob/master/src/Server/Manager.php#L145 
```
$args = [SWOOLE_PROCESS, SWOOLE_UNIX_STREAM];
```

Not found in config.

**Comment by albertcht** [comment]
I will consider to extract this to a configurable setting.

**Comment by albertcht** [comment]
Hi @to2false ,

This feature has been implemented in release `v2.5.0`. Now you can customize it in `socket_type` in `swoole_http.php`. You can go check it.
