### ISSUE TITLE
为什么websocket 客户端链接后，会不停的重新加载？

### ISSUE THREAD

**Issue by mrzxy** [swooletw/laravel-swoole#115]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
PHP 7.2.4

2. Please provide your Laravel/Lumen version.

laravel5.6.24

3. Which release version of this package are you using?

v2.4.1

4. What did you do? If possible, provide a recipe for reproducing the error.

5. What did you expect to see?

6. What did you see instead?

```js
//socket client
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.1.1/socket.io.js"></script>
<script type="text/javascript">
    const socket = io('http://api.dev.ecb_admin.com', {
        transports: ['websocket'],
        reconnection: true,
        query: {
            //10:d0:7a:87:94:85
            token: '{token}'
        }
    });

    socket.on('connect', () => console.log(socket.id))
    socket.on('disconnect', reason => console.log('exit:' + reason))

    socket.on('messages', function(m) { 
        m = JSON.parse(m)
        setTimeout(function() {

            console.log('msgid:' + m.msgid)
            socket.emit('messages_received', m.msgid)
        }, 3000)
    })

</script>
```
php端：
![image](https://user-images.githubusercontent.com/11501927/43674898-182904c6-980d-11e8-97dd-22bd1a61cff5.png)

输出：
![image](https://user-images.githubusercontent.com/11501927/43674889-f5d57ada-980c-11e8-830b-0869624f2a48.png)

**Comment by mrzxy** [comment]
@albertcht 发现redis connected_clients 会一直增加，目前解决方法：加入 redis timeout，请问有什么更好的办法吗

**Comment by albertcht** [comment]
If the `redis` instance can be in the pre-solved list, all the clients will share one redis connection together. For now, I haven't come up with a better solution.

**Comment by mrzxy** [comment]
谢谢
