### ISSUE TITLE
require_once routes.php

### ISSUE THREAD

**Issue by whistling** [swooletw/laravel-swoole#117]
PHP 7.1  + swoole 2.0+laravel 5.5+ laravel-swoole 2.3

 My project was huge and routes file was big, so I decided to split the routes file into smaller files for 
easy management. 

I use require_once to include the small route files  into api.php
`
require_once __DIR__ . '/manager.php';
require_once __DIR__ . '/battery.php';`

but, the result was route not found, !!!

and I change my code use require to include the small route files  into api.php

`require __DIR__ . '/manager.php';
require __DIR__ . '/battery.php';`

it works  ,why???

swoole document tell me to use require_once not require        ...........

![image](https://user-images.githubusercontent.com/19922692/43936004-25456a0c-9c89-11e8-83d8-2c957c1af633.png)

**Comment by zhangzc90** [comment]
> It should not make any differences because `api.php` will be only loaded once.

i meet the same question, still don't know why
