### ISSUE TITLE
Sandbox problem?

### ISSUE THREAD

**Issue by to2false** [swooletw/laravel-swoole#121]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

- php 7.2.5
- swoole 4.0.1

2. Please provide your Laravel/Lumen version.

- Lumen 5.6

3. Which release version of this package are you using?

- 2.4.1

4. What did you do? If possible, provide a recipe for reproducing the error.

- Require [overtrue/pinyin](https://github.com/overtrue/pinyin) package
- Register singleton in provider
```
<?php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Overtrue\Pinyin\MemoryFileDictLoader;
use Overtrue\Pinyin\Pinyin;

class AppServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->singleton(Pinyin::class, function() {
            $pinyin = new Pinyin();
            $pinyin->setLoader(new MemoryFileDictLoader(base_path('vendor/overtrue/pinyin/data/')));
        
            return $pinyin;
        });
    }
}
```

- Make a test router
```
$router->get('/test', function () {
    var_dump(app(\Overtrue\Pinyin\Pinyin::class)->permalink('测试'));
});
```
- Configure this provider to bootstrap/app.php
```
$app->register(App\Providers\AppServiceProvider::class);
```

- Use ab tool to simulate 100 request

5. What did you expect to see?

- No memory leak problem.

6. What did you see instead?

- Out of memory (default memory limit is 128M)

7. Additional instructions

-  I replaced sandbox with cloning application directly, the memory usage not growing too much.

**Comment by to2false** [comment]
Here's another way to avoid this problem, but not very well:

Load the class into the container ahead of time
```
    public function boot()
    {
        $pinyin = new Pinyin();
        $pinyin->setLoader(new MemoryFileDictLoader(base_path('vendor/overtrue/pinyin/data/')));

        $this->app->singleton(Pinyin::class);
        $this->app->instance(Pinyin::class, $pinyin);
    }
```

**Comment by albertcht** [comment]
Hi @to2false ,

Developers are able to customize their pre-resolved list to control which instances should be resolved before being cloned by sandbox in the future released version.

You should avoid using `require` or `include` function in your code.  Here's the partial code of `MemoryFileDictLoader.php`:

```php
public function __construct($path)
{
    if (file_exists($segment)) {
        $this->segments[] = (array) include $segment;
    }
}
```

You should use `include_once` instead.

**Comment by to2false** [comment]
@albertcht Thanks. Look forward to future version.
