### ISSUE TITLE
配置文件中使用config()方法导致源码里取不到配置值

### ISSUE THREAD

**Issue by junshenshi** [swooletw/laravel-swoole#124]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

最新

2. Please provide your Laravel/Lumen version.

laravel 5.5
3. Which release version of this package are you using?

v2.3.7

4. What did you do? If possible, provide a recipe for reproducing the error.
系统配置文件
![image](https://user-images.githubusercontent.com/19427115/44244937-0c536f00-a209-11e8-9a32-0d5774d003a7.png)
swooletw配置文件
![image](https://user-images.githubusercontent.com/19427115/44245051-8ab01100-a209-11e8-8006-897c5569cff3.png)

启动swooletw出现 域名和端口无法读取到值
![image](https://user-images.githubusercontent.com/19427115/44244906-e5953880-a208-11e8-8181-986e7488ccbf.png)

5. What did you expect to see?

6. What did you see instead?

**Comment by albertcht** [comment]
https://blog.maqe.com/dont-use-laravel-s-config-inside-config-files-40e2c8207225

**Comment by junshenshi** [comment]
@albertcht  多谢！
