### ISSUE TITLE
swPort_onRead_http: Content-Length is too big, MaxSize=[20963328].

### ISSUE THREAD

**Issue by mrzxy** [swooletw/laravel-swoole#125]
我设置了`package_max_length`无效
![image](https://user-images.githubusercontent.com/11501927/44258486-a0412d00-a241-11e8-9a5a-66a0e23081c9.png)

**Comment by albertcht** [comment]
20963328 equals to `20 * 1024 * 1024`. It's default config value provided by this package. Did you restart your application after modifying the config?

**Comment by mrzxy** [comment]
@albertcht 重启过了，配置没生效

**Comment by albertcht** [comment]
Check what you get for `config('swoole_http.server.options.package_max_length')`.
