### ISSUE TITLE
Swoole 4.1 new feature `Runtime :: enableCoroutine()` integration

### ISSUE THREAD

**Issue by xiaohuilam** [swooletw/laravel-swoole#126]
After swoole 4.1.*, it brings a new feature [`Runtime::enableCoroutine()`](https://wiki.swoole.com/wiki/page/965.html), to enable coroutine by just simple few line codes to wrap request handler.

### Referrence
 - This issue is not for bug tracking.
 - Documentation: [wiki.swoole](https://wiki.swoole.com/wiki/page/965.html)

**Comment by albertcht** [comment]
Hi @xiaohuilam ,

Thanks for your notification, I will take a look on it!

**Comment by albertcht** [comment]
Integrating coroutine on runtime level is my next experimental goal in the coroutine branch. I close this issue first.
