### ISSUE TITLE
swoole_http.log debug

### ISSUE THREAD

**Issue by mrzxy** [swooletw/laravel-swoole#128]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

php7.2.4

2. Please provide your Laravel/Lumen version.

laravel 5.6

3. Which release version of this package are you using?

v2.4.1

4. What did you do? If possible, provide a recipe for reproducing the error.

* log有时出现redisroom报错
* 客户端给服务端推送消息时，服务器有时出现收不到或者接受延迟的情况，延迟大概在10秒左右不等

5. What did you expect to see?

6. What did you see instead?

![image](https://user-images.githubusercontent.com/11501927/44654132-426fca80-aa23-11e8-9926-fb9f903f6667.png)

**Comment by albertcht** [comment]
The exception thrown by `RedisRoom` is obviously caused by wrong type argument for `removeValue` function. The interesting thing is I can't figure out in what situation the `rooms` variable will equal to `0`?

```php
public function leave($rooms = [])
{
    $rooms = is_string($rooms) || is_integer($rooms) ? func_get_args() : $rooms;

    $this->room->delete($this->sender, $rooms);

    return $this;
}
```

As for the delay messages from your client side, there are too many possibilities, eg. high latency network.

**Comment by mrzxy** [comment]
@albertcht 延迟的问题很奇怪，服务端推送客户端没有延迟，双方进行心跳包也没有延迟，
客户端发送服务端就有延迟，然后我观察swoole_http.log 会出现 RedisRoom 的异常

**Comment by mrzxy** [comment]
@albertcht 就算rooms等于0，最终也会转换成数组，不会导致 类型错误啊，
```php
    public function delete(int $fd, $roomNames = [])
    {
        $roomNames = is_array($roomNames) ? $roomNames : [$roomNames];
        $roomNames = count($roomNames) ? $roomNames : $this->getRooms($fd);

        $this->removeValue($fd, $roomNames, 'fds');

        foreach ($roomNames as $room) {
            $this->removeValue($room, [$fd], 'rooms');
        }
    }
```

**Comment by albertcht** [comment]
You're right, so that's what I'm curious about. Because basically it won't happen. That's just what I found from your log screenshot. If you can provide more detailed info and that will help.

**Comment by mrzxy** [comment]
我只提供一下我的场景， 我有50个设备进行socket链接，当websocker驱动为`redis`时会发生上述情况，主要发生在群推送和群接收的情况，非必现， 我现在使用 `table` 比没有出现上述问题和收发延迟的问题

**Comment by albertcht** [comment]
I tested the websocket feature with redis driver, but I can't reproduce this bug. There's nothing I can do unless you provide a repo which can reproduce your bugs.
