### ISSUE TITLE
How to return response inside go routine? 

### ISSUE THREAD

**Issue by moon0326** [swooletw/laravel-swoole#133]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

php 7.2 and Swoole 4.0.4

2. Please provide your Laravel/Lumen version.

5.2

3. Which release version of this package are you using?

latest

4. What did you do? If possible, provide a recipe for reproducing the error.
5. What did you expect to see?
6. What did you see instead?

Hi, 

I'm not even sure if it is possible, but is there a way to return json response from a go routine?

Let's say I have a route

```php
$app->get('/test', function() {

    go(function() {
         // do something to get some data
    });

});
```

How do I return json data inside go function for the /test route?

**Comment by albertcht** [comment]
Hi @moon0326 ,

You don't need to use `go(function(){});` to wrap your code because a coroutine environment will be automatically created in `onRequest()` callback function.

**Comment by moon0326** [comment]
@albertcht ah..that makes sense! Thank you :)
