### ISSUE TITLE
isRunning returns true instead of false

### ISSUE THREAD

**Issue by grubicv** [swooletw/laravel-swoole#135]
https://github.com/swooletw/laravel-swoole/blob/7c11d754ddc29f78a9ab4aecd5a7341e5e9b3c51/src/Commands/HttpServerCommand.php#L234

if the process is running and you kill it, error will be 0. Doing !0 will return true meaning it's running, but it was actually killed... This causes all sorts of issues, for example with Docker on each run after the initial one...

**Comment by albertcht** [comment]
Hi @grubicv ,

It has been fixed in release `v2.5.0`. You can go check it.
