### ISSUE TITLE
How to clear class static variable

### ISSUE THREAD

**Issue by mitoop** [swooletw/laravel-swoole#142]
Hi, albertcht, my env is  
```
PHP Version   7.2.9     
Swoole Version  4.1.2                                                  
Laravel Version  5.7.3
```
I use laravel nova, and in the nova source code,  it use class static variable, how can i reset it? Thanks

**Comment by albertcht** [comment]
Hi @mitoop ,

You need to reset these static variables before every request by yourself. You can write your reset logics in service provider and add it to `providers` in `swoole_http.php`.

**Comment by mitoop** [comment]
Hi @albertcht 
I had tried. But it didn't work. I will make an another try. Thanks.

**Comment by mitoop** [comment]
Hi @albertcht 
Excuse me. Is there any good practice to reset the class static varible?

**Comment by albertcht** [comment]
Hi @mitoop ,

I think resetting static variables in service provider should do the trick. Do you mind providing more details about your implementation in your service provider?

**Comment by mitoop** [comment]
Hi @albertcht 
```php
class Nova
{
    use AuthorizesRequests;

    /**
     * The registered resource names.
     *
     * @var array
     */
    public static $resources = [];

    /**
     * An index of resource names keyed by the model name.
     *
     * @var array
     */
    public static $resourcesByModel = [];

    /**
     * The callback used to create new users via the CLI.
     *
     * @var \Closure
     */
    public static $createUserCallback;

   ....
```
In the code, it's used directly. I tried in service provider and write a reseter to make the variable equel its original value. But not works.

**Comment by albertcht** [comment]
Hi @mitoop ,

Can you paste the code of your service provider?

**Comment by mitoop** [comment]
Hi, @albertcht 
In swoole_http.php
```
  'providers' => [
        Illuminate\Pagination\PaginationServiceProvider::class,
        Bugsnag\BugsnagLaravel\BugsnagServiceProvider::class,
        Clockwork\Support\Laravel\ClockworkServiceProvider::class,
        App\Providers\NovaServiceProvider::class, // The service provider
    ], 
```
the boot and register:
```
    public function boot()
    {
        $this->routes();

        Nova::serving(function (ServingNova $event) {
            $this->authorization();

            $this->resources();
            Nova::cards($this->cards());
            Nova::tools($this->tools());
        });
    }

    public function register()
    {
        //
    }
```

In the service provider, it use `Nova` directly.

**Comment by albertcht** [comment]
Hi @mitoop ,

What if you reset static `$resources` property directly like:

```php
public function boot()
{
    Nova::$resources = [];
}
```

**Comment by mitoop** [comment]
Hi @albertcht 
I tried and Now I find some clue, It relates to many `class`, Tomorrow I will do more debugging. Thanks your time.

**Comment by zacksleo** [comment]
> Hi @mitoop ,
> 
> What if you reset static `$resources` property directly like:
> 
> ```
> public function boot()
> {
>     Nova::$resources = [];
> }
> ```

not work well

**Comment by ibrunotome** [comment]
Did you solved this @zacksleo ?

**Comment by zacksleo** [comment]
not yet
