### ISSUE TITLE
WARNING>swSSL_accept: bad SSL client

### ISSUE THREAD

**Issue by ITwrx** [swooletw/laravel-swoole#145]
1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
```
    PHP 7.2.10
    swoole 4.1.2
```

2. Please provide your Laravel/Lumen version.
    `Laravel Framework 5.5.43`

3. Which release version of this package are you using?
    `laravel-swoole 2.5 `

4. What did you do? If possible, provide a recipe for reproducing the error.
`I'm trying to enable ssl with swoole. swoole works on local env without ssl. haven't got it working with ssl on staging server yet.`
------------------------------
    
`added ssl related config lines from working, non-swoole, ssl-enabled nginx config to swoole nginx            config, including "proxy_set_header HTTPS "on";", per swoole instructions.`

    
`reloaded nginx.`

` restarted php (for non-swoole reasons)`

`added 'socket_type' => 'SWOOLE_SOCK_TCP | SWOOLE_SSL' and my cert and key paths in config/swoole-http`

`started swool http server.`

5. What did you expect to see?

    `swoole-http start and serv pages, over tls, without error
`

6. What did you see instead?

    `swoole-http starts but i get "502 bad gateway" in browser.`

    `swoole_http.log reports: WARNING>swSSL_accept: bad SSL client[127.0.0.1:58220].`

    `nginx reports: upstream prematurely closed connection while reading response header from upstream
`
-----------------------------

Thanks

**Comment by albertcht** [comment]
Hi @ITwrx ,

`WARNING>swSSL_accept: bad SSL client[127.0.0.1:58220]` means you access swoole server via non-https protocol. Are you able to access swoole server with SSL directly without Nginx proxy?

**Comment by ITwrx** [comment]
sorry for going silent on this. i had unexpected surgery shortly after i opened this and haven't had time to deal with this since then. i'll post back if i get it working. fuller docs for swoole with ssl and nginx reverse proxy would also be nice.

**Comment by albertcht** [comment]
Hi @ITwrx ,

No worries, just comment below directly when you get better. Take care :)

**Comment by ITwrx** [comment]
@albertcht so if enable tls/ssl in swoole config, swoole http server itself expects to serve over https? i didn't understand that. 

i just disabled ssl in swoole config and handled https in nginx and it is working. swoole is set to listen on 127.0.0.1, so that should be good. if i'm understanding this correctly, it might be helpful to clarify this in the wiki. 

thanks for this swoole package. excited to get these speed gains for laravel as this was the last (and frustrating) piece of the puzzle for my optimization efforts.
