### ISSUE TITLE
Issues with Dingo API / JWT authentication middleware

### ISSUE THREAD

**Issue by edmundluong88** [swooletw/laravel-swoole#149]
**1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)**

PHP 7.2.10 (cli) (built: Oct  1 2018 20:12:12) ( NTS )
Swoole 4.0.1

**2. Please provide your Laravel/Lumen version.**

Lumen 5.6.4

**3. Which release version of this package are you using?**

swooletw/laravel-swoole v2.5.0

**4. What did you do? If possible, provide a recipe for reproducing the error.**

1. Installed the following packages and integrated it with Lumen:

- https://github.com/tymondesigns/jwt-auth (v1.0.0-rc.3)
- https://github.com/dingo/api (v2.0.0-alpha2)

2. Registered the following service providers:

- Tymon\JWTAuth\Providers\LumenServiceProvider
- Dingo\Api\Provider\LumenServiceProvider

3. Enabled JWT authentication for Dingo API via the Tymon JWT package ([reference](https://github.com/dingo/api/wiki/Authentication#json-web-tokens-jwt))

4. Enabled the Dingo API authentication middleware on a Controller in the constructor ([reference](https://github.com/dingo/api/wiki/Authentication#require-authentication-on-controller-methods)):

```
class Controller extends BaseController
{
     public function __construct()
     {
          $this->middleware('api.auth');
     }
}
```
5. Logged in via API and retrieved a JWT token

6. Attempted to make an authenticated request (JWT token in the Authorization request header) to an endpoint in the middleware-protected controller, the request fails with a 401 Unauthorized Error with the error message "Failed to authenticate because of bad credentials or an invalid authorization header."

**5. What did you expect to see?**

I tracked down the exception to this line in the Dingo/Api/Auth/Auth class: https://github.com/dingo/api/blob/v2.0.0-alpha2/src/Auth/Auth.php#L113

This exception is thrown from the authenticate() method on [L73](https://github.com/dingo/api/blob/v2.0.0-alpha2/src/Auth/Auth.php#L73) in the same class. 

The error is thrown if Dingo API doesn't see an `Authorization` header in the request. I put debug log statements in the following classes to track the request and see where things are going wrong:

[Dingo/Api/Http/Middleware/Auth
](https://github.com/dingo/api/blob/v2.0.0-alpha2/src/Http/Middleware/Auth.php)
```
    /**
     * Perform authentication before a request is executed.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Closure                 $next
     *
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $route = $this->router->getCurrentRoute();

        Log::debug("In Dingo\Api\Http\Middleware\Auth handling request");
        Log::debug("Request is: " . $request);

        if (! $this->auth->check(false)) {
            $this->auth->authenticate($route->getAuthenticationProviders());
        }

        return $next($request);
    }
```

[Dingo/Api/Auth/Auth](https://github.com/dingo/api/blob/v2.0.0-alpha2/src/Auth/Auth.php)
```
    /**
     * Authenticate the current request.
     *
     * @param array $providers
     *
     * @throws \Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException
     *
     * @return mixed
     */
    public function authenticate(array $providers = [])
    {
        $exceptionStack = [];

        Log::debug('in Dingo/Api/Auth/Auth authenticating the request');


        // Spin through each of the registered authentication providers and attempt to
        // authenticate through one of them. This allows a developer to implement
        // and allow a number of different authentication mechanisms.
        foreach ($this->filterProviders($providers) as $provider) {
            try {
                Log::debug('Request: ' . $this->router->getCurrentRequest());
                Log::debug('Route: ' . $this->router->getCurrentRoute()->getName());

                $user = $provider->authenticate($this->router->getCurrentRequest(), $this->router->getCurrentRoute());

                $this->providerUsed = $provider;

                return $this->user = $user;
            } catch (UnauthorizedHttpException $exception) {
                $exceptionStack[] = $exception;
            } catch (BadRequestHttpException $exception) {
                // We won't add this exception to the stack as it's thrown when the provider
                // is unable to authenticate due to the correct authorization header not
                // being set. We will throw an exception for this below.
            }
        }

        Log::debug('throwing an unauthorized exception');

        $this->throwUnauthorizedException($exceptionStack);
    }
```

In a traditional PHP-FPM configuration, the JWT middleware and authentication works exactly as intended. No exceptions are thrown and the controller endpoints are properly protected. Here are the debugs logs for the successful case in a traditional environment:

Dingo/Api/Http/Middleware/Auth
```
[2018-10-11 17:09:09] dev.DEBUG: In Dingo\Api\Http\Middleware\Auth handling request
[2018-10-11 17:09:09] dev.DEBUG: Request is: GET /api/profile HTTP/1.1
Accept:          application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Authorization:   Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODg4OFwvYXBpXC9sb2dpbiIsImlhdCI6MTUzOTI3Nzc0NywiZXhwIjoxNTM5MjgxMzQ3LCJuYmYiOjE1MzkyNzc3NDcsImp0aSI6IjdlWVBiSUl5SXFaMDZQeHciLCJzdWIiOjUsInBydiI6Ijk2OWQ3MmRlNmI0MTQzZWYxNDY2MTg5MTExNjU4NmRiNjY1MDlkNjUiLCJ3aXphcmRfY29tcGxldGVkIjp0cnVlLCJmaXJzdF9uYW1lIjoiU2FsbHkiLCJsYXN0X25hbWUiOiJUaWxsbWFuIiwiZW1haWwiOiJzdHVkZW50MUBleGFtcGxlLmNvbSIsInJvbGVzIjpbIm1lbWJlciIsInN0dWRlbnQiXX0.J8666j_UTJWt88eai1pKiHnyOjIqUt01HJDQnljwTx0
Connection:      keep-alive
Content-Length:
Content-Type:    application/json
Cookie:          _ga=GA1.1.1568465141.1539267789; _gid=GA1.1.2055778598.1539267789; _gat=1
Host:            localhost:8888
Referer:         http://localhost:8888/student/dashboard/profile
User-Agent:      Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Cookie: _ga=GA1.1.1568465141.1539267789; _gid=GA1.1.2055778598.1539267789; _gat=1
```

Dingo/Api/Auth/Auth
```
[2018-10-11 17:09:09] dev.DEBUG: in Dingo/Api/Auth/Auth authenticating the request
[2018-10-11 17:09:09] dev.DEBUG: Request: GET /api/profile HTTP/1.1
Accept:          application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Authorization:   Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODg4OFwvYXBpXC9sb2dpbiIsImlhdCI6MTUzOTI3Nzc0NywiZXhwIjoxNTM5MjgxMzQ3LCJuYmYiOjE1MzkyNzc3NDcsImp0aSI6IjdlWVBiSUl5SXFaMDZQeHciLCJzdWIiOjUsInBydiI6Ijk2OWQ3MmRlNmI0MTQzZWYxNDY2MTg5MTExNjU4NmRiNjY1MDlkNjUiLCJ3aXphcmRfY29tcGxldGVkIjp0cnVlLCJmaXJzdF9uYW1lIjoiU2FsbHkiLCJsYXN0X25hbWUiOiJUaWxsbWFuIiwiZW1haWwiOiJzdHVkZW50MUBleGFtcGxlLmNvbSIsInJvbGVzIjpbIm1lbWJlciIsInN0dWRlbnQiXX0.J8666j_UTJWt88eai1pKiHnyOjIqUt01HJDQnljwTx0
Connection:      keep-alive
Content-Length:
Content-Type:    application/json
Cookie:          _ga=GA1.1.1568465141.1539267789; _gid=GA1.1.2055778598.1539267789; _gat=1
Host:            localhost:8888
Referer:         http://localhost:8888/student/dashboard/profile
User-Agent:      Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Cookie: _ga=GA1.1.1568465141.1539267789; _gid=GA1.1.2055778598.1539267789; _gat=1
```
As you can see, the request has the JWT token in the header and is being properly parsed. The request in the middleware and the request in the Auth class are identical. This is the expected behavior.

**6. What did you see instead?**

When making the same set of requests on the Laravel Swoole environment, here are the request logs:

Dingo/Api/Http/Middleware/Auth
```
[2018-10-11 16:02:00] dev.DEBUG: In Dingo\Api\Http\Middleware\Auth handling request
[2018-10-11 16:02:00] dev.DEBUG: Request is: GET /api/profile HTTP/1.1
Accept:            application/json
Accept-Encoding:   gzip, deflate, br
Accept-Language:   en-GB,en-US;q=0.9,en;q=0.8
Authorization:     Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3RcL2FwaVwvbG9naW4iLCJpYXQiOjE1MzkyNzM3MTksImV4cCI6MTUzOTI3NzMxOSwibmJmIjoxNTM5MjczNzE5LCJqdGkiOiJMWmlBUGR0YkdqQ0tnOWZZIiwic3ViIjo1LCJwcnYiOiI5NjlkNzJkZTZiNDE0M2VmMTQ2NjE4OTExMTY1ODZkYjY2NTA5ZDY1Iiwid2l6YXJkX2NvbXBsZXRlZCI6dHJ1ZSwiZmlyc3RfbmFtZSI6IlNhbGx5IiwibGFzdF9uYW1lIjoiVGlsbG1hbiIsImVtYWlsIjoic3R1ZGVudDFAZXhhbXBsZS5jb20iLCJyb2xlcyI6WyJtZW1iZXIiLCJzdHVkZW50Il19.J42k7UWroDZ18rM207vmEDEVVYJ10f5C1YEWpXYJcyo
Connection:        close
Content-Type:      application/json
Host:              localhost
Referer:           http://localhost:8000/student/dashboard/profile
User-Agent:        Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
X-Forwarded-For:   172.19.0.1
X-Forwarded-Host:  localhost
X-Forwarded-Port:  80
X-Forwarded-Proto: http
X-Real-Ip:         172.19.0.1
Cookie: _ga=GA1.1.1568465141.1539267789; _gid=GA1.1.2055778598.1539267789; _gat=1
```

Dingo/Api/Auth/Auth
```
[2018-10-11 16:02:00] dev.DEBUG: in Dingo/Api/Auth/Auth authenticating the request
[2018-10-11 16:02:00] dev.DEBUG: Request: POST /api/login HTTP/1.1
Accept:            application/json
Accept-Encoding:   gzip, deflate, br
Accept-Language:   en-GB,en-US;q=0.9,en;q=0.8
Connection:        close
Content-Length:    259
Content-Type:      multipart/form-data; boundary=----WebKitFormBoundaryacs4qkRAYOZIYH8j
Host:              localhost
Origin:            http://localhost:8000
Referer:           http://localhost:8000/login
User-Agent:        Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
X-Forwarded-For:   172.19.0.1
X-Forwarded-Host:  localhost
X-Forwarded-Port:  80
X-Forwarded-Proto: http
X-Real-Ip:         172.19.0.1
Cookie: _ga=GA1.1.1568465141.1539267789; _gid=GA1.1.2055778598.1539267789; _gat=1

------WebKitFormBoundaryacs4qkRAYOZIYH8j
Content-Disposition: form-data; name="email"

student1@example.com
------WebKitFormBoundaryacs4qkRAYOZIYH8j
Content-Disposition: form-data; name="password"

password
------WebKitFormBoundaryacs4qkRAYOZIYH8j--
```

As shown above, the requests are not the same in the Swoole environment. The middleware receives the correct request (requesting a user profile) but the Auth class receives a totally different request. This all blows up with the 401 Unauthorized error of course since the request in the Auth class does not have the JWT token. The request that's received in the Auth class is actually the initial request to login and retrieve a JWT.

From my investigation, it appears the Auth class is caching the old request in memory and not receiving the right request from the middleware. When inspecting the Auth class, the culprit appears to be on [this line](https://github.com/dingo/api/blob/v2.0.0-alpha2/src/Auth/Auth.php#L82) where the Auth class retrieves the request to authenticate from the injected `Dingo/Api/Routing/Router` class.

I have tried to follow the debug guidelines and register the Dingo API / JWT providers in the swoole_http config file and also tried to refresh the Router instance, but had no luck in doing so.

Any help would be greatly appreciated. Thanks!

**Comment by hubertnnn** [comment]
I believe you might need to create a custom resetter for Dingo's Router based on this one:
https://github.com/swooletw/laravel-swoole/blob/master/src/Server/Resetters/RebindRouterContainer.php

**Comment by bravist** [comment]
https://github.com/hhxsv5/laravel-s/issues/50

This is important

**Comment by edmundluong88** [comment]
> I believe you might need to create a custom resetter for Dingo's Router based on this one:
> https://github.com/swooletw/laravel-swoole/blob/master/src/Server/Resetters/RebindRouterContainer.php

Thanks for the tip, I'll be able to investigate and see if I can solve this in the next few days. I will be sure to report back here with my findings.

**Comment by albertcht** [comment]
Hi @edmundluong88 ,

Sorry for the late reply, I haven't tried dingo package but took a simple glance at its source code. Dingo seems to implement its own router system and injected container to many classes. That might be the main reason for causing this issue.

In this package, it tries to replace all the related containers to a sandbox container. However, if the containers in those dingo classes are preserved and not being replaced to a sandbox container, that will cause them didn't match the correct response.

Try to re-register these service providers to see if it helps: https://github.com/dingo/api/tree/v2.0.0-alpha2/src/Provider
