### ISSUE TITLE
关于广播无法发送

### ISSUE THREAD

**Issue by junshenshi** [swooletw/laravel-swoole#15]
HI 
您好！
Websocket::broadcast()->to(1)->emit('message', 'for your eyes only');
刚刚测试了 
broadcast 配合to(fd)无法发送给个人，
broadcast 配合to(room_name)可以发送到群组，
单独to可以发送
![qq 20180503185808](https://user-images.githubusercontent.com/19427115/39573087-4e656388-4f04-11e8-92f0-7e3a98c5ec14.png)
![qq 20180503185822](https://user-images.githubusercontent.com/19427115/39573089-5155f83c-4f04-11e8-951d-78abe3a8c607.png)

**Comment by albertcht** [comment]
Hi @junshenshi ,

請問您的編號 `1` 是發送者的 fd 嗎？如果是的話 `Websocket::broadcast()->to(1)` 是無法送達的，因為 `broadcast` 代表要送給除了自己以外的人

**Comment by junshenshi** [comment]
hai Albert
不是发送给自身，
同样是发送给$to
只有原生方法成功

**Comment by albertcht** [comment]
Hi @junshenshi ,

我的意思是你無法發送的狀況下`發送者 fd` 和`接收者fd`是相同的嗎？
當`發送者 fd` 和`接收者fd`相同時又使用了 broadcast 該筆發送會被忽略
再和你確認一次：
```
Websocket::to(1)->emit('message', 'for your eyes only');
```
你上面這樣寫是可以發送的嗎？

我剛剛自己測試了一下，發送邏輯是正常的

**Comment by junshenshi** [comment]
发现原因，to()方法需要传整型，字符串的fd无法触发。

**Comment by albertcht** [comment]
沒錯，`to()` 方法的參數當傳入整數會被判斷為 `fd`，字串會被判斷為房間名稱

**Comment by junshenshi** [comment]
OK 好了，我强制转换了。考虑下要不要把发送方法to切分为fd发送，room发送两个方法，fd发送可以传数组，因为有个场景大概是同一个用户，打开多个窗口拥有多个fd。我用循环解决了多fd，如果能传数组那更好了。

**Comment by albertcht** [comment]
其實 websocket 現有的 api 除了有 `to` 之外，另外有 `toAll` 的方法是支援 array 的
但我現在可能會想將 `toArray` 合併至 `to` 讓他同時支援單或多個 `fd` 傳入
關於 `to` 是否會分成兩個方法來區分房間和 `fd` 我會仔細考慮一下，感謝你的建議

**Comment by junshenshi** [comment]
Ok 谢谢

**Comment by albertcht** [comment]
Hi @junshenshi ,

在新版的程式中我已經將 websocket 和 room 中原本含有 `All` 名稱的方法全數移除，並讓原先單數的方法支援單個或是陣列參數

至於 `to` 我還是照原先的設計同時支援 `fd` 和房間名稱，只是對於 `fd` 的形態做更好的兼容，當字串形態的 `fd` 找不到房間成員時，而 `fd` 又符合 `numeric` 條件會將該 `fd` 列入發送清單中

**Comment by junshenshi** [comment]
ok  谢谢
