### ISSUE TITLE
PDO::prepare(): send of 62 bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by lzp9421** [swooletw/laravel-swoole#154]
经常第一次访问会出现这个错误，刷新一下会好。MySQL数据库。是因为长连接断开了的问题吗？请问怎样设置可以避免此问题？
local.ERROR: PDO::prepare(): send of 62 bytes failed with errno=32 Broken pipe (SQL: select * from `xxx` where `xx` = xx limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): PDO::prepare(): send of 62 bytes failed with errno=32 Broken pipe (SQL: select * from `xxx` where `xx` = xx limit 1) at /laravel_app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, ErrorException(code: 0): PDO::prepare(): send of 62 bytes failed with errno=32 Broken pipe at /laravel_app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:326)

php version  7.2.9
swoole version  4.1.2
"laravel/framework": "5.5.*"
mysql   5.7.23

**Comment by albertcht** [comment]
Hi @lzp9421 ,

Did you set to `persistent` mode in your database config? And Laravel has its own reconnection process for lost connection. Make sure if your code triggers that correctly. https://github.com/illuminate/database/blob/7d32146be1e4dfccb035e12cb38fcab0899fe3d1/Connection.php#L733
