### ISSUE TITLE
How Just want to open WebSocket??

### ISSUE THREAD

**Issue by zhouaini528** [swooletw/laravel-swoole#157]
| PHP Version     | 7.2.11-3+ubuntu18.04.1+deb.sury.org+1                |
| Swoole Version  | 4.2.5                                                |
| Laravel Version | 5.5.44                                               |
| Listen IP       | 192.168.10.10                                        |
| Listen Port     | 1215                                                 |
| Server Status   | Online                                               |
| Reactor Num     | 1                                                    |
| Worker Num      | 1                                                    |
| Task Worker Num | 1                                                    |
| Websocket Mode  | On                                                   |
| PID             | 23748                                                |
| Log Path        | /home/vagrant/code/shop/storage/logs/swoole_http.log

http access to success。

Just want to open websocket,Don't open http. How do I achieve this。Or how does the client access it?

**Comment by albertcht** [comment]
Hi @zhouaini528 ,

Websocket protocol is based on HTTP 1.1. A websocket connection needs to do http handshake and then upgrade to websocket. Therefore, it's impossible to only enable websocket mode without an HTTP server.
