### ISSUE TITLE
How to use this as just a socket server instead http / websocket

### ISSUE THREAD

**Issue by algking** [swooletw/laravel-swoole#158]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
php7.1
swoole 4.2.6

2. Please provide your Laravel/Lumen version.
laravel5.5

3. Which release version of this package are you using?
latest

4. What did you do? If possible, provide a recipe for reproducing the error.

5. What did you expect to see?

How to use this as just a socket server instead http / websocket

6. What did you see instead?

steps/ config file

**Comment by albertcht** [comment]
#157
