### ISSUE TITLE
Optimizing Nginx Config

### ISSUE THREAD

**Issue by hc-codersatlas** [swooletw/laravel-swoole#162]
Hi, the Nginx config in https://github.com/swooletw/laravel-swoole/wiki/9.-Nginx-Configuration can be further optimized, e.g.

try_files /not_exists @swoole;

TO

try_files @swoole /not_exists;

AND

For suffix, set the suffix per location to avoid the if.

Thanks!

**Comment by albertcht** [comment]
After the review, I would still like to keep the current configuration as an 
example. But many thanks for your suggestion :)
