### ISSUE TITLE
 I want to use Beijing time  in swoole.log.

### ISSUE THREAD

**Issue by dahuicyh** [swooletw/laravel-swoole#167]
in swoole.log "[2018-11-21 02:12:00 #62030.1]	NOTICE	Server is shutdown now"
Invalid time zone settings：
I set up the Asia/Shanghai time zone php.ini in the framework. It is still invalid.
Now I want to use Beijing time in my diary.
Please tell me how to modify it?

**Comment by albertcht** [comment]
Hi @dahuicyh ,

I think this is nothing to do with this package. Please check `timezone` in your `config/app.php'.
