### ISSUE TITLE
Laravel 5.7 not support

### ISSUE THREAD

**Issue by yangliulnn** [swooletw/laravel-swoole#169]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

```
➜  ~ php -v
PHP 7.2.11 (cli) (built: Oct 11 2018 16:23:09) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.11, Copyright (c) 1999-2018, by Zend Technologies
➜  ~ php --ri swoole

swoole

swoole support => enabled
Version => 4.1.2
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
kqueue => enabled
rwlock => enabled
openssl => enabled
pcre => enabled
zlib => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```

2. Please provide your Laravel/Lumen version.

```
➜  swoole php artisan -V  
Laravel Framework 5.7.15
```

3. Which release version of this package are you using?

2.5.0

4. What did you do? If possible, provide a recipe for reproducing the error.

"Declaration of SwooleTW\Http\Task\SwooleTaskQueue::createStringPayload($job, $data) should be compatible with Illuminate\Queue\Queue::createStringPayload($job, $queue, $data)"

5. What did you expect to see?

6. What did you see instead?

**Comment by fractalzombie** [comment]
#174

**Comment by fractalzombie** [comment]
#175
