### ISSUE TITLE
mysql-coroutine  How do you use it?

### ISSUE THREAD

**Issue by dahuicyh** [swooletw/laravel-swoole#173]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
PHP 7.2  swoole:4.0.4

2. Please provide your Laravel/Lumen version.
lumen:5.6

3. Which release version of this package are you using?
2.5

4. What did you do? If possible, provide a recipe for reproducing the error.

I want to use MySQL protocol, how to configure it！

This is my current configuration:（app.php）

$app->configure('swoole_http');
$app->configure('swoole_websocket');

$app->register(SwooleTW\Http\LumenServiceProvider::class);

The MySQL protocol has not been found to be in effect?

**Comment by damonto** [comment]
You can change the driver to `mysql-coroutine` in `config/database.php`

**Comment by damonto** [comment]
If you are using Lumen you should add LumenServiceProvider::class before `$app->withEloquent()`

**Comment by dahuicyh** [comment]
@damonto



error:
Undefined index: 00 (SQL: select * from `fm_media` where `fm_media`.`media_id` = 326271 limit 1

'mysql-coroutine' => [
    'driver' => 'mysql',
    'charset' => 'utf8mb4',
    'collation' => 'utf8mb4_general_ci',
    'prefix' => env('DB_PREFIX', ''),
    'timezone' => env('DB_TIMEZONE', '+8:00'),
    'strict' => false,
    'database' => env('DB_MEDIA_DATABASE', 'db_jupiter_media'),
    'read' => [
        'host' => '172.17.12.100',
        'username' => 'root',
        'password' => 'root',
    ],
    'write' => [
        'host' => '172.17.12.100',
        'username' => 'root',
        'password' => 'root',
    ],
    'host' => '172.17.12.100',
    'port' => 3306,
    'username' => 'root',
    'password' => 'root',
],



dahuicyh@qq.com

**Comment by damonto** [comment]
#160 #165

**Comment by dahuicyh** [comment]
@damonto
I installed it by composer, so what should I do about it?

"swooletw/laravel-swoole": "^2.5",

now:
https://github.com/swooletw/laravel-swoole/tree/develop   not in composer

**Comment by damonto** [comment]
"swooletw/laravel-swoole" : "dev-develop". NOT RECOMMEND.

**Comment by dahuicyh** [comment]
@damonto
thank you very much

Now a new error:
Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ErrorException: Swoole\Coroutine\MySQL::prepare(): mysql client is waiting response, cannot send new sql query.


wait 1 min response

**Comment by albertcht** [comment]
Hi @Leon-zzk ,

It doesn't support create another sub coroutine on your own temporarily.

Also, the coroutine feature is still in develop, it's not recommended to use coroutine client yet. Otherwise your some bindings in your app container will get polluted easily if you access them by Facades or static props.
