### ISSUE TITLE
  Not enough arguments (missing: "action").  

### ISSUE THREAD

**Issue by iPhonePKAndroid** [swooletw/laravel-swoole#179]
Last login: Sun Dec 23 16:55:50 on ttys003
You have new mail.
MacBook-Air:laravel a$ php -v
PHP 7.2.11 (cli) (built: Oct 11 2018 16:23:09) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.11, Copyright (c) 1999-2018, by Zend Technologies
MacBook-Air:laravel a$ 

Laravel5.7

**Comment by albertcht** [comment]
Please read [Issues Guideline](https://github.com/swooletw/laravel-swoole/wiki/Z2.-Issues-Guideline) before you open an issue.
