### ISSUE TITLE
这个扩展是测试版?

### ISSUE THREAD

**Issue by YangHaHabiu** [swooletw/laravel-swoole#180]
请问这个扩展是正式版还是测试版 为什么 function encode 里面要拼接一些不需要的参数 ( $packet = Packet::MESSAGE . Packet::EVENT;) function getSender 感觉也有问题

**Comment by albertcht** [comment]
Please read [Issues Guideline](https://github.com/swooletw/laravel-swoole/wiki/Z2.-Issues-Guideline) before you open an issue.
