### ISSUE TITLE
Session auth invalid

### ISSUE THREAD

**Issue by lilianjin** [swooletw/laravel-swoole#182]
## My environmental information
```

# PHP version
PHP 7.3.0 (cli) (built: Dec  7 2018 11:00:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0, Copyright (c) 1999-2018, by Zend Technologies


# Swoole information
swoole support => enabled
Version => 4.2.11
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2q  20 Nov 2018
pcre => enabled
zlib => enabled
brotli => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144
```

1. First of all, my config has made almost no changes.

2. Links file in websocket

```php
Websocket::on('connect', function ($websocket, Request $request) {
	if ($user = $request->user()) {
		dump('The user id: ' . $user->id . '---->' . $user->username . '[login in]');
		$websocket->loginUsing($user);
	}

	// called while socket on connect
});

Websocket::on('disconnect', function ($websocket) {
	echo 'FD:' . $websocket->getUserId() . ' has left.';
	//dump($websocket->getSender());
	// called while socket on disconnect
});

// Websocket::on('message', function ($websocket, $data) {
// 	$websocket->emit('message', $data);
// });

Websocket::on('chats', '\App\Http\Controllers\ChatsController@chatMessage');

```

```php

public function chatMessage($websocket, $data)
	{
		$user = UserModel::findByUsername($data['to']);
		// $user = UserModel::find($websocket->getUserId());
		$data['user'] = $user->useChattoArray();

		Websocket::toUser([$user, UserModel::find($websocket->getUserId())])->emit('chats_messages', addslashes(Jsonable::encode($data)));
	}
```

```bash


```
> Very strange, no matter where you are. It's all logged in to the user you first logged in, it's automatic
After trying to refresh, the second account that is logged in to different browsers in different places is the first one. Sometimes, weird will show ourselves. I considered the session problem, so I printed the sesion. The problems that arise are the same, sometimes the same, sometimes different. Let me think about the needs, especially here to seek help. ·Swooletw/laravel-swoole· is a great component, I like it very much! I also hope that the author can continue to maintain, even if it is commercialized. It is a great gospel for those of us who are superficial with the underlying knowledge of computers!

<img width="635" alt="wx20190102-094224 2x" src="https://user-images.githubusercontent.com/21023027/50578290-bce9a480-0e72-11e9-9d4f-e62928f7f36c.png">

**Comment by albertcht** [comment]
The user fetched in websocket `connect` callback is directly related to the `middleware` you set in `config/swoole_websocket.php`.

Where do you dump your session id? Try to dig it more and give me more details if possible.

**Comment by lilianjin** [comment]
configuration
```
'instances' => [
			'blade.compiler',
		],
```
Solve the problem

**Comment by lilianjin** [comment]
Please close this question and it has been resolved.

**Comment by albertcht** [comment]
Hi, just curious about why the session id is related to 'blade.compiler'?
