### ISSUE TITLE
TCP server 

### ISSUE THREAD

**Issue by junshenshi** [swooletw/laravel-swoole#184]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

newest 

2. Please provide your Laravel/Lumen version.

newest 

3. Which release version of this package are you using?
newest 

4. What did you do? If possible, provide a recipe for reproducing the error.

The package does not have a preset receive function

5. What did you expect to see?

How to add?

6. What did you see instead?

**Comment by albertcht** [comment]
No, this package doesn't support building tcp server on laravel side at this moment.
