### ISSUE TITLE
Global sessions for multiple servers. 

### ISSUE THREAD

**Issue by zilveer** [swooletw/laravel-swoole#191]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
- PHP v7.2, Swoole v4

2. Please provide your Laravel/Lumen version.
- Laravel 5.5

3. Which release version of this package are you using?
- Latest

4. What did you do? If possible, provide a recipe for reproducing the error.
- I want to set a global session for the user for using it in multiple servers, and one database server which handles the sessions.

5. What did you expect to see?
- Be able to use multiple servers for front end and one DB for backend and want to use the user sessions among the front end servers.

6. What did you see instead?
- I don't know if it is possible because according to the "notice"  documents fornd here :
https://github.com/swooletw/laravel-swoole/wiki/Z1.-Notices

Then it is not possible to use global variables, I don't know if this means that I cannot use global sessions ?

Thx for an amazing package and for any feedback.
Regards Zilveer

**Comment by albertcht** [comment]
Session Clustering is nothing to do with global variables. They are totally different.
