### ISSUE TITLE
Swoole\Http\Response::write(): data to send is empty.

### ISSUE THREAD

**Issue by noecs** [swooletw/laravel-swoole#194]
I introduced swooletw/laravel-swoole and configured nginx according to the documentation. When I was trying to use reactjs on the request interface. The first OPTIONS request has an error, but the http status code is 200.
Subsequent get requests are not reported. :
```
{
    "message":"Swoole\Http\Response::write(): data to send is empty.",
    "status_code": 500,
    "debug": {
        "line": 128,
        "file":"/Users/noecs/Desktop/noecs-laravel-shop/vendor/swooletw/laravel-swoole/src/Transformers/Response.php",
        "class": "ErrorException",
        "trace":[
            "#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Swoole\\Http\\Res...', '/Users/noecs/De...', 128, Array) ",
            "#1 /Users/noecs/Desktop/noecs-laravel-shop/vendor/swooletw/laravel-swoole/src/Transformers/Response.php(128): Swoole\Http\Response->write('')",
            "#2 /Users/noecs/Desktop/noecs-laravel-shop/vendor/swooletw/laravel-swoole/src/Transformers/Response.php(116): SwooleTW\Http\Transformers\Response->sendInChunk('')" ,
            "#3 /Users/noecs/Desktop/noecs-laravel-shop/vendor/swooletw/laravel-swoole/src/Transformers/Response.php(56): SwooleTW\Http\Transformers\Response->sendContent()",
            "#4 /Users/noecs/Desktop/noecs-laravel-shop/vendor/swooletw/laravel-swoole/src/Server/Manager.php(224): SwooleTW\Http\Transformers\Response->send()",
            "#5 {main}"
        ]
    }
}
```

**Comment by albertcht** [comment]
This is the limit by Swoole's response. You can't respond with empty content.

You have two options:

1. Respond your `OPTIONS` preflight request by Nginx if possible.
2. Add any content to your response.

**Comment by noecs** [comment]
Thank you for your help, thank you very much.

**Comment by ashleigh-hopkins** [comment]
I do think this should be classed as an issue. I'm sure lots of people have existing application code returning no content (only a status code), which is a perfectly valid HTTP response.

I made a pull request #209 which fixes this problem.

**Comment by albertcht** [comment]
Hi @ashleigh-hopkins,

Thanks for your pull request. I think that's indeed a simple way to support null content response, and I decide to mark this issue as `improvement` instead.
