### ISSUE TITLE
Unexpected DB transaction rollBack occasionally.

### ISSUE THREAD

**Issue by lokielse** [swooletw/laravel-swoole#196]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

- **PHP version : 7.2.6**
- **Swoole version : 4.2.6**

2. Please provide your Laravel/Lumen version.

- **Laravel : v5.6.39**

3. Which release version of this package are you using?

- **laravel-swoole : v2.6.2**

4. What did you do? If possible, provide a recipe for reproducing the error.

> There is a http resource of my app which create an order `without` db transaction. 
The order was saved in db and its raw data was responsed to client and user paid for it. 
After several seconds, the order got lost (as well as the logs in that duration).

P.S. 
> 1. There is no delete statements for any order records.
> 2. used none mysql-coroutine config

5. What did you expect to see?

> Independent db transaction for each request?

6. What did you see instead?

> It seems like some other requests'(or jobs) transaction take effect on it. while an exception was raised in a transaction and all statements been rollBacked.

**Comment by albertcht** [comment]
Please provide more detailed information and the steps (or partial code) to reproduce this issue, thanks.
