### ISSUE TITLE
Problem with swoole queue

### ISSUE THREAD

**Issue by prolic** [swooletw/laravel-swoole#197]
> 1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

4.2.12

> 2. Please provide your Laravel/Lumen version.

5.7

> 3. Which release version of this package are you using?

pecl

> 4. What did you do? If possible, provide a recipe for reproducing the error.

I have a job that is dispatched to swoole queue by laravel. That job triggers some model changes. Depending on those changes, an observer may dispatch another job to the queue.

Problem: I receive this exception
```
Swoole\\Server::task(): task method can only be used in the worker process.
```

Which totally makes sense, I understand why this happens. However, I cannot simply change from dispatch() to dispatchNow(), because the observer is also invoked from the web application, so I cannot call dispatchNow() without slowing the website down massively.

Is there a way to detect if I am in the worker or in the task? Depending on that information, I could change the call to dispatch() / dispatchNow() depending on this check.

But maybe this change would also be a good candidate for a bugfix in \SwooleTW\Http\Task\SwooleTaskQueue::push.

If you need further information let me know.

**Comment by albertcht** [comment]
Hi @prolic ,

You can use `app('swoole.server')->taskworker` to check if you're in a normal worker or a task worker.

**Comment by prolic** [comment]
@albertcht perfect, that did the trick for me. I extended laravel's bus-dispatcher and the corresponding provider, so I can add this check before every dispatch()-call, maybe you want to do the same within this library. Either way, I solved the problem for me now. Thanks a lot!

**Comment by albertcht** [comment]
Anytime.
