### ISSUE TITLE
\Illuminate\Http\Request is not reset

### ISSUE THREAD

**Issue by xutengx** [swooletw/laravel-swoole#198]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
PHP 7.2.13
swoole 4.2.12

2. Please provide your Laravel/Lumen version.
Laravel 5.5.44

3. Which release version of this package are you using?
v2.6.2

4. What did you do? If possible, provide a recipe for reproducing the error.

If sent nginx ` host ` and ` X - Forwarded - host ` and their values are not the same

// nginx configuration eg:
server {
    listen       83;
    server_name  www.local-test.cn;
    location / {
        proxy_pass http://Swoole.com;
        proxy_set_header Host "www.swoole-test.cn";
        proxy_set_header X-Forwarded-Host "www.local-test.cn";
        proxy_set_header Scheme $http_x_real_proto;
        proxy_set_header Server_port $http_x_real_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
    }
}
just like this
// nginx configuration
if( isset(ngx.host) && isset( ngx.X-Forwarded-Host) && (ngx.host !== ngx.X-Forwarded-Host))
{
    // php some controller
    use Illuminate\Http\Request
    public function someAction(Request $request): string
    {
        $eq = (spl_object_hash ($request) === spl_object_hash (app()->instances['request']));
        var_dump($eq); 
        // output : false
    }
}

5. What did you expect to see?
The dependency injected request object ===  `app()->instances['request']` .

6. What did you see instead?
The dependency injected request object does not change in each request, 
but `app()->instances['request']` has changed and correct.

**Comment by albertcht** [comment]
What's the relationship between your Nginx config and you issue title? BTW, The result for `spl_object_hash($request) === spl_object_hash(app('request'))` in my local environment is `true`.

**Comment by xutengx** [comment]
> 
> 
> What's the relationship between your Nginx config and you issue title? BTW, The result for `spl_object_hash($request) === spl_object_hash(app('request'))` in my local environment is `true`.

Only if nginx has both of these values [ host and x-forwarded-host ], and they are not equal, 
spl_object_hash($request) === spl_object_hash(app('request')) will be false.

**Comment by xutengx** [comment]
waiting for you

**Comment by albertcht** [comment]
Unable to reproduce this issue with the following request headers forwarded by Nginx:

```
["x-forwarded-for"]=>
  array(1) {
    [0]=>
    string(9) "127.0.0.1"
  }
["x-forwarded-host"]=>
  array(1) {
    [0]=>
    string(8) "test.dev"
  }
```

`spl_object_hash($request) === spl_object_hash(app('request'))` is always true.

**Comment by xutengx** [comment]
Ha ha,
It shouldn't be `x-forwarded-for` and `x-forwarded-host`, 
it should be `http_host` and `x-forwarded-host`;

**Comment by albertcht** [comment]
The result is still the same. Nothing changes.

```
array(9) {
  ["host"]=>
  array(1) {
    [0]=>
    string(12) "swoole.local"
  }
  ["x-forwarded-host"]=>
  array(1) {
    [0]=>
    string(8) "test.dev"
  }
```

**Comment by xutengx** [comment]
You have to reboot your swoole http service, not only your nginx.

**Comment by albertcht** [comment]
Unable to reproduce this issue with freshly started swoole and nginx srevers.

**Comment by xutengx** [comment]
I've recorded a one minute video to reproduce this problem;
so,  68822684@qq.com, This is my email. Send me an email and I could send it to you.

**Comment by albertcht** [comment]
Please upload your video to youtube and paste the public link here. Or making a docker image which can reproduce your issue can make it easier.

**Comment by albertcht** [comment]
Also, please make sure this issue also appears in a fresh new laravel project. Thus I can exclude the possibility if other 3rd-party packages or somewhere in your code cause this issue.

**Comment by xutengx** [comment]
http://v.youku.com/v_show/id_XNDA2MTAwMzY5Ng==.html?spm=a2h3j.8428770.3416059.1

**Comment by albertcht** [comment]
I can't watch this video correctly, please upload it to youtube if possible. Also, have you tried to reproduce this issue with a new laravel project?

**Comment by xutengx** [comment]
https://www.youtube.com/watch?v=x7y4opZ6NSQ
