### ISSUE TITLE
Is there a problem with websocket support for long polling?

### ISSUE THREAD

**Issue by Quiet95scholar** [swooletw/laravel-swoole#200]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

PHP 7.3  swoole Last version 

2. Please provide your Laravel/Lumen version.

5.7.19

3. Which release version of this package are you using?

Last version

4. What did you do? If possible, provide a recipe for reproducing the error.

I use nginx to forward http and websocket, the backend service uses laravel-swoole, and the websocket server is turned on. I use the npm component sockio-io-Client and laravel-echo to try to connect to websocket-server respectively. The result is that the ws protocol can be upgraded normally, but when I try to send a message or subscribe to a channel, I will find a long polling request that failed. Each time there are 3 HTTP requests and one WS connection, an infinite loop.
I tried to connect directly using the WS protocol, and the data transfer can be completed normally.
Because both php and WS services are provided by laravel-swoole, I guess there is a problem with laravel-swoole handling long polls.

5. What did you expect to see?

6. What did you see instead?

**Comment by Quiet95scholar** [comment]
@albertcht 
Sorry, I have read this document, but I forgot. I don't know if I will take the lead in implementing this function in the future. I support the long polling. I have not done research, I don't know if I should consider the browser maybe does not support websocket in the future network environment.
不好意思,看过这个文档,但是忘记了.不知道未来是否会率先实现这个功能呢,对长轮询的支持.我没有做过调研,不知道在未来的网络环境中是否还要考虑浏览器不支持websocket的问题.

**Comment by albertcht** [comment]
Hi @Quiet95scholar ,

I don't have the plan for supporting long polling yet. And I think native websocket should be supported by all the modern web browsers now.
