### ISSUE TITLE
WARNING http_request_on_header_value: cookie is too large

### ISSUE THREAD

**Issue by g30225579** [swooletw/laravel-swoole#201]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
PHP version:
PHP 7.2.10

Swoole version:
swoole support => enabled
Version => 4.2.1
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

2. Please provide your Laravel/Lumen version.
Laravel version 5.7

3. Which release version of this package are you using?
swooletw version 2.5.0

4. What did you do? If possible, provide a recipe for reproducing the error.
swoole_http.log里提示：WARNING	http_request_on_header_value: cookie is too large

**Comment by albertcht** [comment]
You should read Swoole's official document before opening this issue. There's a `8K` size limit for http header and it's not changeable.

**Comment by aftabnaveed** [comment]
Not sure what version of swoole you are using, but they seem to have fixed the issue here

https://github.com/swoole/swoole-src/issues/2164
