### ISSUE TITLE
Bad content-type for styles (text/plain)

### ISSUE THREAD

**Issue by Ostap34JS** [swooletw/laravel-swoole#203]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

PHP 7.3.1-1
Swoole 4.2.12

2. Please provide your Laravel/Lumen version.

Laravel 5.7 (latest)

3. Which release version of this package are you using?

don't know

4. What did you do? If possible, provide a recipe for reproducing the error.

- Step 1 - create basic laravel 5.7 project
```bash
composer create-project --prefer-dist laravel/laravel laraswoole
```
- Step 2 - install swoole and this package, publish the config
https://github.com/swooletw/laravel-swoole/wiki/4.-Installation

- Step 3 - run project
```bash
php artisan swoole:http start
```

- Step 3 - open browser and go to `http://127.0.0.1:1215/`

5. What did you expect to see?

content type of `app.css` must be `text/css`

6. What did you see instead?

content type of `app.css` it's `text/plain`, browser don't want to render css, if it have text/plain content type

## How to fix? (set content type`text/css` for styles)

Thanks...

**Comment by albertcht** [comment]
This bug has been fixed in the new release `v.2.6.3`.
