### ISSUE TITLE
pcntl extension required?

### ISSUE THREAD

**Issue by amcsi** [swooletw/laravel-swoole#205]
Recently a Docker deploy of mine failed, because the latest Laravel Swoole demanded for the pcntl extension to be enabled when doing `composer install`.

I've noticed this commit: https://github.com/swooletw/laravel-swoole/commit/aed922f141487cfe9dc084f098d81e5fe7fc1ac6#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R33

Is the pcntl extension really required? In the commit I didn't see anything that was using it. And Laravel Swoole seemed to have been working fine without pcntl so far.

**Comment by albertcht** [comment]
Hi @amcsi ,

Thanks for your question, originally I thought symfony's process relies on `pcntl`. However, after I reviewed its source code, indeed, `pcntl` seemed to be unnecessary.

I've removed it in the new release `v 2.6.4`

**Comment by amcsi** [comment]
Awesome, thanks!
