### ISSUE TITLE
How to get the user id through fd.

### ISSUE THREAD

**Issue by noecs** [swooletw/laravel-swoole#208]
1.surroundings:
PHP Version     7.2.8                                                                           
Swoole Version  4.2.10                                                                          
Laravel Version 5.5.45                                                                          
Listen IP       127.0.0.1                                                                       
Listen Port     5200                                                                            
Server Status   Offline                                                                         
Reactor Num     6                                                                               
Worker Num      | 6                                                                               
Task Worker Num | 6                                                                               
Websocket Mode  | On                                                                              

2.my question:
Below is my websocket controller code
```
/**
     * this user
     * @var
     */
    public $user;

    /**
     * total room name
     */
    const TOTAL_ROOM = 'all';

    /**
     * clients ID
1    * @param Request $request
     */
    public $clientsId;

    /**
     *
     * ChatController constructor.
     * @param Request $request
     */
    public function __construct(Request $request)
    {
        $this->user = $request->user();
        if($this->user == null) {
            //error
            throw new \InvalidArgumentException("Invalid Authorization");
        }
        //login user
        Websocket::loginUsing($this->user);
        //add room `all`
        Websocket::join(self::TOTAL_ROOM);
        //get users fd (array)
        $this->clientsId = Room::getClients(self::TOTAL_ROOM);
    }

    public function connect()
    {
        $users = $this->findUsers();
        Websocket::to(self::TOTAL_ROOM)->emit('message', 'enjoy the game');
    }


    public function disconnect()
    {
        Websocket::leave(self::TOTAL_ROOM);
        Websocket::to(self::TOTAL_ROOM)->emit('message', 'enjoy the game');
    }
```
When I add the current user to the global room. I need to send the current online user to the client when the current user connects to the websocket. I looked at the document and didn't mention it. How to get the user's id according to $fd. I want to query the database by user id to get their username or avatar.

**Comment by albertcht** [comment]
I think what you're looking for is `getUserId` function? It's listed in https://github.com/swooletw/laravel-swoole/wiki/7.-Websocket#websocket-apis

**Comment by noecs** [comment]
No, I want to get the currently logged in user, I can get it according to getUserId. However, I want to get a user based on the specified fd, which seems not so easy.

**Comment by noecs** [comment]
For example, I used `Room::getClients()` to get the user client ID of the currently connected websocket. I want to get the user id corresponding to these clients ($fd) based on this client ID array.

**Comment by albertcht** [comment]
Please refer to the source code in `SwooleTW\Http\Websocket::Authenticatable`: https://github.com/swooletw/laravel-swoole/blob/master/src/Websocket/Authenticatable.php#L97

However, if you want to get user data by fd, I highly recommend you implement your own users mapping (caching user data in this table) by native swoole table. Fetching user data by querying from database every time is not a good idea.

**Comment by noecs** [comment]
Whether it's looking for $user_id via $fd or $fd via $user_id, this will be more common. Is there a plan to complete this function?

**Comment by albertcht** [comment]
I think getting user data based on the current connected fd is the most common case. And since the room class is open, you can get all the rooms by fd easily.

**Comment by noecs** [comment]
Suppose it is a chat room or a game room. When a user connects to the room, the user is pushed to whom the current room is online. Or information such as games, chat nicknames, avatars, etc.

**Comment by albertcht** [comment]
As what I've said previously, you can get all the rooms by fd via room api easily.

**Comment by noecs** [comment]
Sorry, I may not understand the usage of this design. I am a chat room, chatting one-on-one, and saving the chat history to the mysql database.

**Comment by albertcht** [comment]
Did you really check the source code I pasted above?
https://github.com/swooletw/laravel-swoole/blob/master/src/Websocket/Authenticatable.php#L97

You can make a simple helper function for mapping from `fd` to `user_id` if you really check it...

```php
foreach (Room::getRooms($fd) as $room) {
    if (count($explode = explode(Websocket::USER_PREFIX, $room)) === 2) {
        return $explode[1];
    }
}

return null;
```

**Comment by noecs** [comment]
🤣I think I can use table to implement $fd=>$user , $user_id => so that I don't need to query database user information every time. I close the question first.
