### ISSUE TITLE
 Call to undefined function SwooleTW\Http\Server\swoole_set_process_name()

### ISSUE THREAD

**Issue by MohamedPHP** [swooletw/laravel-swoole#21]
I Am Using laravel 5.4 when i run `php artisan swoole:http start` i get this error  Call to undefined function SwooleTW\Http\Server\swoole_set_process_name()

**Comment by vlados** [comment]
I can confirm. Using vagrant (unix) with swoole extension loaded:

Version | 2.1.3
-- | --
Author | tianfeng.han[email: mikan.tenny@gmail.com]
coroutine | enabled
epoll | enabled
eventfd | enabled
timerfd | enabled
signalfd | enabled
cpu affinity | enabled
spinlock | enabled
rwlock | enabled
async postgresql | enabled
async http/websocket client | enabled
openssl | enabled
Linux Native AIO | enabled
pcre | enabled
zlib | enabled
mutex_timedlock | enabled
pthread_barrier | enabled
futex | enabled

**Comment by MohamedPHP** [comment]
@vlados Thanks For Help The Swoole.so extension was not enabled in my php.ini
