### ISSUE TITLE
Swoole\Coroutine\MySQL::prepare(): mysql client is waiting response, cannot send new sql query.

### ISSUE THREAD

**Issue by lzp9421** [swooletw/laravel-swoole#210]
PHP 7.2.9
swoole 4.1.2
laravel 5.5
swooletw/laravel-swoole ^2.5
-----------------------------------

config/database.php 
  connections.mysql.driver=mysql-coroutine

ERROR:
"Swoole\Coroutine\MySQL::prepare(): mysql client is waiting response, cannot send new sql query. 

Illuminate\Database\QueryException 
…/vendor/laravel/framework/src/Illuminate/Database/Connection.php664
62
ErrorException 
…/vendor/swooletw/laravel-swoole/src/Coroutine/PDO.php197
61
Swoole\Coroutine\MySQL prepare
…/vendor/swooletw/laravel-swoole/src/Coroutine/PDO.php197
60
SwooleTW\Http\Coroutine\PDO prepare
…/vendor/laravel/framework/src/Illuminate/Database/Connection.php326
59
Illuminate\Database\Connection Illuminate\Database\{closure}
…/vendor/laravel/framework/src/Illuminate/Database/Connection.php657
58
Illuminate\Database\Connection runQueryCallback
…/vendor/laravel/framework/src/Illuminate/Database/Connection.php624
57
Illuminate\Database\Connection run
…/vendor/laravel/framework/src/Illuminate/Database/Connection.php333
56
Illuminate\Database\Connection select
…/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php1719
55
Illuminate\Database\Query\Builder runSelect
…/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php1704
54
Illuminate\Database\Query\Builder get
…/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php481
53
Illuminate\Database\Eloquent\Builder getModels
…/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php465
52
Illuminate\Database\Eloquent\Builder get
…/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php77
51
Illuminate\Database\Eloquent\Builder first
…/app/Models/Model.php32
... ...

**Comment by albertcht** [comment]
Hi @lzp9421 ,

Coroutine feature is still unstable and in develop. Do not use it in production yet, thanks.
