### ISSUE TITLE
Uncaught ArgumentCountError: Too few arguments to function SwooleTW\Http\Server\Manager::onTask(), 2 passed and exactly 4 expected

### ISSUE THREAD

**Issue by marscoo** [swooletw/laravel-swoole#213]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
PHP 7.2.14
Swoole 4.2.13

2. Please provide your Laravel/Lumen version.
Laravel 5.7.26

3. Which release version of this package are you using?
v2.6.4

4. What did you do? If possible, provide a recipe for reproducing the error.
`QUEUE_DRIVER` set as `swoole`
Dispatch a job to queue

5. What did you expect to see?
The job should be executed without fatal error

6. What did you see instead?
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function SwooleTW\Http\Server\Manager::onTask(), 2 passed and exactly 4 expected in Users/****/Projects/****/vendor/swooletw/laravel-swoole/src/Server/Manager.php:262
Stack trace:
#0 {main}
  thrown in /Users/****/Projects/****/vendor/swooletw/laravel-swoole/src/Server/Manager.php on line 262
```

**Comment by marscoo** [comment]
Some new findings, this is not a bug.

I've enabled `enable_task_coroutine` so that the `onTask()` with 4 arguments is not applicable anymore.

For more details, please read:
https://wiki.swoole.com/wiki/page/p-task_enable_coroutine.html

I'm working on a patch for this feature, and will submit a PR when done.

**Comment by albertcht** [comment]
Great!

**Comment by junshenshi** [comment]
@marscoo  hi 请问你果边系点调用onTask（）嘅？
我睇文档冇介绍
