### ISSUE TITLE
Why do I need clone config every time?

### ISSUE THREAD

**Issue by crcms** [swooletw/laravel-swoole#216]
## Env

php:7.2
swoole:4.2
laravel:5.7
laravel-swoole:2.6.4

## problem:

Hello, I read your code, I don't quite understand, why config needs to be cloned every time. In theory, if the serviceProvider changes the config every time it is loaded, it will affect the current running. I don't quite understand the need. Where is the meaning of clone?

Thank you very much for answering my doubts, thank you.

**Comment by crcms** [comment]
@albertcht Hello albertcht:
I have studied again, whether it is because of the coroutine, if the concurrent coroutine does not perform clone, the config modification in the run may cause errors in other coroutines.
But there is another problem
The app is all clone, but the object inside the app does not generate a new clone object even if clone, the code does not find __clone, which leads to the fact that the app running in all concurrent coroutines is different objects, all inside the app. Instance is still the same object, there will still be problems

**Comment by crcms** [comment]
@albertcht Already understood

**Comment by albertcht** [comment]
Hi @crcms ,

In fact, the reason for cloning config instance in every request is pretty simple. As your understanding, even though the app container is cloned separately, however, some instances in that container will be preserved (eg. db, config, etc.).

Imagine there's a script in your app logic:

```php
Config::set(['foo' => 'bar']);
```

Then your config instance will be polluted for the next coming requests. That's why I need to reset the config instance in every request.

**Comment by crcms** [comment]
Hello @albertcht 
I still have a problem, even if you clone, but relative to the class in the class, still point to the same address, if I only change the property is not solved, even if using the app context, a simple example
```php
class Bar {
    //...
}
class Foo {
        public $bar;

        public function __construct(Bar $bar) {
                $this->bar = $bar;
        }
}

$bar = new Bar();
$foo = new Foo($bar);
$foo2 = clone $foo;

// bar class equal
var_dump($foo,$foo2);

```

**Comment by albertcht** [comment]
Hi @crcms ,

Yes, but in config class, there's only an `items` property. So it's safe to isolated config properties by only using clone method.

```php
$config = new \Illuminate\Config\Repository;
$clone = clone $config;

$config->set('foo', 'bar');

var_dump([
    $config->get('foo'),
    $clone->get('foo')
]);
```

**Comment by crcms** [comment]
Of course, I just worry about other object components in laravel, because there are too many associations in laravel, if it is read-only, of course, no problem. If the shared singleton is modified by one of the running requests, subsequent requests will be polluted.
Thank you very much. He helped me a lot after reading your code.
