### ISSUE TITLE
What should i do when i used swoole:http , but some other ext package use like $_SERVER ?

### ISSUE THREAD

**Issue by liuqingliu** [swooletw/laravel-swoole#221]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

2. Please provide your Laravel/Lumen version.

3. Which release version of this package are you using?

4. What did you do? If possible, provide a recipe for reproducing the error.

5. What did you expect to see?

6. What did you see instead?

**Comment by liuqingliu** [comment]
1. PHP 7.2.15 , swoole 4.2.13
2. laravel5.5
3.  Swoole Version  | 4.2.13

**Comment by liuqingliu** [comment]
4. i use overture/wechat for login, then error: Undefined index: HTTP_HOST {"exception":"[object] (ErrorException(code: 0): Undefined index: HTTP_HOST at /xxxx/vendor/overtrue/wechat/src/Kernel/Support/Helpers.php:87
5. i expect no error

**Comment by liuqingliu** [comment]
i know i can't use Super Global Variables like $_SERVER in swoole:http, but how about other ext package ? so many code use this.

**Comment by albertcht** [comment]
Please read [Q&A](https://github.com/swooletw/laravel-swoole/wiki/Z4.-Q&A) before opening an issue. If you insist getting request info from global variables, swoole might not be your choice.

**Comment by liuqingliu** [comment]
Thanks for your answer！
