### ISSUE TITLE
PHP Fatal error for Laravel Nova

### ISSUE THREAD

**Issue by phoenixg** [swooletw/laravel-swoole#222]
1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

swoole: v4.2
php: 7.2.7

2. Please provide your Laravel/Lumen version.

laravel: v5.7.26
Nova: 1.3.2

3. Which release version of this package are you using?

latest `laravel-swoole`, ig. v2.6.4

4. What did you do? If possible, provide a recipe for reproducing the error.

```shell
→ php artisan swoole:http start
Starting swoole http server...
Swoole http server started: <http://127.0.0.1:1215>
```

5. What did you expect to see?

Successfully running via laravel-swoole http artisan command

6. What did you see instead?

```shell
PHP Fatal error:  Cannot declare class App\Nova\Metrics\EarnedAmountPerDay, because the name is already in use in /Users/pig/mine/projects/php/pig-nova/app/Nova/Metrics/PayOrder/EarnedAmountPerDay.php on line 62
```

**Comment by albertcht** [comment]
Please read [Issues Guideline](https://github.com/swooletw/laravel-swoole/wiki/Z2.-Issues-Guideline) before you open an issue.

**Comment by sahilkumar00** [comment]
@phoenixg to override this issue do these changes in composer.json
-in the classmap array enter the folder

```
"classmap": [
            "database/seeds",
            "database/factories",
            "app/pathnametofolder"

        ]
```
-then composer 
`composer dump-autoload  `
