### ISSUE TITLE
api cannot be authenticated by ·Authenticate· middleware.

### ISSUE THREAD

**Issue by lilianjin** [swooletw/laravel-swoole#224]
my config

```php

'instances' => [
	'view',
],

'providers' => [
        AuthServiceProvider::class,
        PaginationServiceProvider::class
]

```
I have encountered a strange problem, the main reason is still not knowing how to effectively debug the program. Swoole has been ignorant for a month or two. I am currently experiencing a problem, I need to restart the service every time I log in, otherwise the api cannot be authenticated by `Authenticate` middleware.

**Comment by albertcht** [comment]
There's no effective way to debug your laravel code in swoole environment. You need to know much about how laravel works and how it runs on swoole server.

**Comment by lilianjin** [comment]
Please see the picture below, very strange question. My head is big. . .

- Prompt login information error? Ok! I will open the token to the new browser tab. . . .
<img width="477" alt="qq20190225-100159 2x" src="https://user-images.githubusercontent.com/21023027/53309760-9b41f200-38e4-11e9-850a-34c16a77627e.png">

- Oh! Magical? It is actually effective, but why did the 401 come from?
![Uploading QQ20190225-100210@2x.png…]()



- Here, what I can think of is the problem of middleware verification! Ok, I will comment on the `AuthenticationException`. Everything is fine. I have a hard time understanding what the problem is. Can you tell me?
![Uploading QQ20190225-100601@2x.png…]()

**Comment by lilianjin** [comment]
Please see the picture below, very strange question. My head is big. . .

- Prompt login information error? Ok! I will open the token to the new browser tab. . . .
<img width="477" alt="qq20190225-100159 2x" src="https://user-images.githubusercontent.com/21023027/53309760-9b41f200-38e4-11e9-850a-34c16a77627e.png">

- Oh! Magical? It is actually effective, but why did the 401 come from?
<img width="1821" alt="qq20190225-100210 2x" src="https://user-images.githubusercontent.com/21023027/53310247-0d1b3b00-38e7-11e9-9638-dbba0ac44fbb.png">


- Here, what I can think of is the problem of middleware verification! Ok, I will comment on the `AuthenticationException`. Everything is fine. I have a hard time understanding what the problem is. Can you tell me?
<img width="709" alt="qq20190225-100601 2x" src="https://user-images.githubusercontent.com/21023027/53310255-16a4a300-38e7-11e9-8dc1-05285cac8169.png">

**Comment by albertcht** [comment]
This issue will be closed shortly unless you can provide more detailed information. And no offense but to be honest, I have difficulty understanding your description.

Please follow the [Issues Guideline](https://github.com/swooletw/laravel-swoole/wiki/Z2.-Issues-Guideline) and [Debug Guideline](https://github.com/swooletw/laravel-swoole/wiki/Z3.-Debug-Guideline) before opening next issue, thanks.

**Comment by lilianjin** [comment]
please closed the  issue. thank
