### ISSUE TITLE
How to use asynchronous tasks ?

### ISSUE THREAD

**Issue by ChenSee** [swooletw/laravel-swoole#225]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
2. Please provide your Laravel/Lumen version.
3. Which release version of this package are you using?

    | Software | Version |
    | --------- | --------- |
    | PHP | `7.2.10` |
    | Swoole | `4.2.12` |
    | Laravel/Lumen | `5.7.27` |
    | Laravel-Swoole | `2.6.4` |

4. What did you do? If possible, provide a recipe for reproducing the error.

`How to use asynchronous tasks ? Is there a specific document to see ? Wiki no tutorial .`

**Comment by albertcht** [comment]
Hi @ChenSee ,

Just change your driver to `swoole` in queue config.

**Comment by ChenSee** [comment]
Hi @albertcht 
How to make a persistent connection to the database，There is a problem, if I make a cross-domain connection, OPTIONS will report an error.  `Swoole\Http\Response::write(): data to send is empty.`

**Comment by noecs** [comment]
@ChenSee See [#194](https://github.com/swooletw/laravel-swoole/issues/194)

**Comment by ChenSee** [comment]
@albertcht 
![image](https://user-images.githubusercontent.com/11918919/53297615-b583bd80-385b-11e9-8f29-4c4a98f6f49a.png)
![image](https://user-images.githubusercontent.com/11918919/53297619-c5030680-385b-11e9-8d1e-e09c83aceea1.png)
When you find this problem, you can't get the parameters first, and you can get the parameters once again. POST will have this problem.

**Comment by albertcht** [comment]
Please refer to #194, and `OPTIONS` with empty response will be supported in the next release.

**Comment by ChenSee** [comment]
@albertcht I have already read it, but nginx can't handle requests with error codes, and the return is empty. Only waiting for your next version.

**Comment by albertcht** [comment]
This has been supported in the newest release `v2.6.5`.

**Comment by ChenSee** [comment]
@albertcht thank you very much
