### ISSUE TITLE
Request not reset

### ISSUE THREAD

**Issue by noecs** [swooletw/laravel-swoole#226]
1. localhost environment
PHP Version      7.2.8                                                                
Swoole Version   4.2.13                                                               
Laravel Version  5.7.27                                                               
Listen IP        127.0.0.1                                                            
Listen Port      5200                                                                 
Server Status    Offline                                                              
Reactor Num      4                                                                    
Worker Num       4                                                                    
Task Worker Num 4                                                                    
Websocket Mode   On                                                                   
PID              None                                                                 
Log Path         /Users/noecs/Desktop/noecsSystemLaravel/storage/logs/swoole_http.log

2. my question:I am using swooletw+laravel5.7+dingo+passport to develop my project. After the service is started every time, the first request is made through the token, and then the API data can be obtained without the token. The first token request is not reset.
I have been reading the debugging guide and issue for a long time, or asking a friend, Unfortunately, they didn't solve my problem.
To this end, I created a new project on github that reproduces the problems I encountered.
[noecsSystemLaravel](https://github.com/noecs/noecsSystemLaravel)

Thank you for your help.

**Comment by albertcht** [comment]
Hi @noecs ,

If you read [Q&A](https://github.com/swooletw/laravel-swoole/wiki/Z4.-Q&A), you will find:

```
We can not guarantee all the third-party package work well with this package. Especially some packages are not designed with the consideration in this use case.
```

If you check the issues of this repo, you will find the following issues are all related to your question:

* https://github.com/swooletw/laravel-swoole/issues/74
* https://github.com/swooletw/laravel-swoole/issues/123
* https://github.com/swooletw/laravel-swoole/issues/137
* https://github.com/swooletw/laravel-swoole/issues/149

Do you really check them?

**Comment by noecs** [comment]
I refer to the configuration of the above problems. I tried adding the following to `swoole_http.php` and failed to solve my problem.
```
...
'instances' => [
        //'auth',
        'router', 'cache'
],
'providers' => [
        Illuminate\Pagination\PaginationServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\AppServiceProvider::class,
        //Solve the error:`Auth guard driver [api] is not defined.`
        Laravel\Passport\PassportServiceProvider::class
],
...
```
Including modifications`App\Providers\AuthServiceProvider`,
```
<?php

namespace App\Providers;

use Carbon\Carbon;
use Laravel\Passport\Passport;
use Illuminate\Support\Facades\Gate;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Auth\AuthManager;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        'App\Model' => 'App\Policies\ModelPolicy',
    ];

    /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();

        //
        Passport::tokensExpireIn(Carbon::now()->addDays(7));

        Passport::refreshTokensExpireIn(Carbon::now()->addDays(14));
    }


    protected function registerAuthenticator()
    {
        $this->app->singleton('auth', function ($app) {
            var_dump('auth resolved');
            // Once the authentication service has actually been requested by the developer
            // we will set a variable in the application indicating such. This helps us
            // know that we need to set any queued cookies in the after event later.
            $app['auth.loaded'] = true;

            return new AuthManager($app);
        });

        $this->app->singleton('auth.driver', function ($app) {
            return $app['auth']->guard();
        });
    }
}
```
The problem still exists.

**Comment by albertcht** [comment]
Please try not to use `dingo` package. Things will become much more complex in its routing system. Try to debug it by yourself and describe how you tracing steps in detail, thanks.

I don't have enough free time to debug everyone's project. The more detailed information you can provide, the higher possibility I can give you a hand.

**Comment by noecs** [comment]
Thanks for your suggestion, I use `laravel5.7+passport7.2` and the request can be reset.
