### ISSUE TITLE
ETA support for Laravel 5.8?

### ISSUE THREAD

**Issue by pingcheng** [swooletw/laravel-swoole#227]
Hi peeps,

Thanks for done such a great package to boost Laravel!

I tried to upgrade to 5.8 and found out the swoole:http was failed to boot up. 

Do you have any ETA for the compatible update for the latest release?

Cheers

**Comment by albertcht** [comment]
Hi @pingcheng ,

Yes, I will check it soon. And I will try to support Laravel 5.8 in the next release.

**Comment by albertcht** [comment]
This has been supported in the newest release `v2.6.5`.

**Comment by pingcheng** [comment]
Hi @albertcht, thx for the quick updating! I'll update the version tonight!

**Comment by pingcheng** [comment]
Thanks! Just updated, everything works smoothly 👍
