### ISSUE TITLE
Can't not find namespace？

### ISSUE THREAD

**Issue by MikeMaldini** [swooletw/laravel-swoole#23]
Well i install this package successfull & i also have install swoole, but when i run `php artisan swoole:http start`  it didn't work：
![a](https://user-images.githubusercontent.com/29230494/39660033-fbec6488-5068-11e8-918f-471ac11ac8e0.png)
![b](https://user-images.githubusercontent.com/29230494/39660035-ffd6daa6-5068-11e8-9a6b-97614a1b90e6.png)
May be give me some help?

**Comment by albertcht** [comment]
Hi, make sure you install swoole extension correctly. Type `php -m | grep swoole` to check it.

**Comment by storyn26383** [comment]
Hi @MikeMaldini, looks ur laravel-swoole doesnt install correctly.

**Comment by MikeMaldini** [comment]
@albertcht @storyn26383  Yeah, it's my laravel cache problem , it work now, thanks 😃
