### ISSUE TITLE
Lumen: Target [Illuminate\Contracts\Http\Kernel] is not instantiable.

### ISSUE THREAD

**Issue by sykorax** [swooletw/laravel-swoole#234]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

| PHP | Swoole |
| --- | --- |
| 7.2.15 | 4.3.0

2. Please provide your Laravel/Lumen version.

```Lumen (5.8.0) (Laravel Components 5.8.*)```

3. Which release version of this package are you using?

```2.5```

4. What did you do? If possible, provide a recipe for reproducing the error.

Using docker i've built an image compiled swool in it.
Starting with docker-compose i've set the ```SWOOLE_HTTP_ACCESS_LOG``` env variable to logaically **true** however starting the container respond with an exception

5. What did you expect to see?

Running the service with access log enabled

6. What did you see instead?

```
server_1  |
server_1  | In Container.php line 962:
server_1  |
server_1  |   Target [Illuminate\Contracts\Http\Kernel] is not instantiable.
server_1  |
server_1  |
grpclumentest_server_1 exited with code 1
```

**Comment by cielu** [comment]
have you ever open websocket ?

**Comment by sykorax** [comment]
@cielu no i have not. 
I'm trying to make it work with gRPC and Envoy proxy.

Anyways i was looking at the code but could not spend enough time to figure out what's going on badly like this.

**Comment by albertcht** [comment]
Hi @sykorax ,

This bug has been fixed in the newest release `v2.6.5.2`. Can you check it if it woks now?

**Comment by sykorax** [comment]
Hey @albertcht,

It's working now. Thank you for the very quick response! :)
Closing so.

**Comment by albertcht** [comment]
Anytime :)
