### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by omsun123** [swooletw/laravel-swoole#24]
I am getting this error 

$ php artisan swoole:http start
Starting swoole http server...
Swoole http server started: <http://127.0.0.1:1215>

In Manager.php line 459:

  Call to undefined function SwooleTW\Http\Server\swoole_set_process_name()

pls help

**Comment by albertcht** [comment]
Hi, make sure you install swoole extension correctly. Type php -m | grep swoole to check it.

**Comment by omsun123** [comment]
I am using windows and xampp. pls help me to install swoole extension.

**Comment by albertcht** [comment]
Swoole doesn't support windows yet.

**Comment by albertcht** [comment]
Yes, you may run Swoole on Window 10's ubuntu environment. But I haven't done that on Windows 10, can't guarantee if it's 100% working.

**Comment by codeitlikemiley** [comment]
its 100% working as it should be :)
