### ISSUE TITLE
Laravel5.6 not support

### ISSUE THREAD

**Issue by BlackDogLi** [swooletw/laravel-swoole#240]
php -v 

PHP 7.3.2 (cli) (built: Feb 14 2019 10:08:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.2, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.2, Copyright (c) 1999-2018, by Zend Technologies

php -ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.0
Built => Mar  7 2019 17:56:06
coroutine => enabled
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2q  20 Nov 2018
http2 => enabled
pcre => enabled
zlib => enabled
brotli => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144

Laravel5.6
在自己的MacBook 上，swoole扩展正常加载，laravel-swoole插件以及相关配置正常设置，项目根目录运行php artsian swoole:http start之后显示http已启动，但是浏览器却无法访问项目

**Comment by BlackDogLi** [comment]
@albertcht what info needed?

**Comment by albertcht** [comment]
Please read issues guideline or other issues, thanks.

**Comment by BlackDogLi** [comment]
@albertcht composer.json:

"require": {
        "php": ">=7.1.3",
        "appstract/laravel-opcache": "^2.0",
        "erusev/parsedown": "^1.6",
        "fideloper/proxy": "~4.0",
        "graham-campbell/exceptions": "^11.0",
        "intervention/image": "^2.4",
        "laravel/framework": "5.6.*",
        "laravel/passport": "^5.0",
        "laravel/tinker": "^1.0",
        "league/html-to-markdown": "^4.6",
        "naux/auto-correct": "^1.0",
        "orangehill/iseed": "^2.5",
        "overtrue/laravel-lang": "^3.0",
        "predis/predis": "^1.1.1",
        "suin/php-rss-writer": "^1.5",
        "swooletw/laravel-swoole": "v2.6.5.3",
        "tom-lingham/searchy": "^2.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.2",
        "barryvdh/laravel-ide-helper": "^2.5",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "phpunit/phpunit": "~7.0",
        "symfony/css-selector": "~4.0",
        "symfony/dom-crawler": "~4.0"
    },


swoole_http.log:

[2019-03-07 12:47:47 $38706.0]	WARNING	swManager_check_exit_status: worker#4[pid=41018] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.3.0, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/issues/2000
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

**Comment by stephenlake** [comment]
@BlackDogLi [Issue Guideline](https://github.com/swooletw/laravel-swoole/wiki/Z2.-Issues-Guideline).

**Comment by albertcht** [comment]
Unable to reproduce until more details provided.
