### ISSUE TITLE
websocket can't trigger disconnect event , this is the reason

### ISSUE THREAD

**Issue by cielu** [swooletw/laravel-swoole#242]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

 php v 7.2.3
 swoolev 4.2.13

2. Please provide your Laravel/Lumen version.

  lumen 5.8.*

3. Which release version of this package are you using?
  
  2.6.5.3

4. What did you do? If possible, provide a recipe for reproducing the error.

### Hi ,   @albertcht    server can't trigger disconnect event , when client close connect websocket .

![image](https://user-images.githubusercontent.com/13715811/54064411-10031d80-424f-11e9-8d68-1835f53cf9eb.png)

###    when I close the client web , websocket really trigger onClose event , but return ;

5. What did you expect to see?

  trigger 'disconnect' event normally

6. What did you see instead?

 can't receive disconnect event

**Comment by albertcht** [comment]
This has been fixed in the release `v2.6.5.4`.
