### ISSUE TITLE
Document swoole queue driver

### ISSUE THREAD

**Issue by ibrunotome** [swooletw/laravel-swoole#248]
As I can see here: https://github.com/swooletw/laravel-swoole/pull/136/files#diff-8e5778decfcfa6a9bd7b4c0b428f8bdcR134

And here: https://github.com/swooletw/laravel-swoole/issues/225#issuecomment-466740321

It's seems that I just need to set the queue driver to `swoole`.

I think that this must be documented.

Also, do you pretend to implement the milliseconds timer in this package?

**Comment by albertcht** [comment]
All other missing info will be documented in [Others](https://github.com/swooletw/laravel-swoole/wiki/Z5.-Others) from now on, thanks for your suggestion.
