### ISSUE TITLE
Uncaught Error: Call to undefined method Symfony\Component\HttpFoundation\ResponseHeaderBag::allPreserveCaseWithoutCookies()

### ISSUE THREAD

**Issue by mouhsinelonly** [swooletw/laravel-swoole#25]
i get this error when i try to access the website

`[Symfony\Component\Debug\Exception\FatalErrorException]
  Uncaught Error: Call to undefined method Symfony\Component\HttpFoundation\ResponseHeaderBag::allPreserveCaseWithoutCookies() in /var/www/html/dares/vendor/swooletw/laravel-s
  woole/src/Server/Response.php:73
  Stack trace:
  #0 /var/www/html/dares/vendor/swooletw/laravel-swoole/src/Server/Response.php(54): SwooleTW\Http\Server\Response->sendHeaders()
  #1 /var/www/html/dares/vendor/swooletw/laravel-swoole/src/Server/Manager.php(189): SwooleTW\Http\Server\Response->send()
  #2 {main}
    thrown`

**Comment by albertcht** [comment]
Hi @mouhsinelonly ,

`allPreserveCaseWithoutCookies()` is available after Symphony 3.4, what's your Laravel's version?

**Comment by mouhsinelonly** [comment]
i am using laravel 5.2

**Comment by albertcht** [comment]
Hi @mouhsinelonly ,

Before Laravel 5.3, `symfony/http-foundation` is too old to use function `allPreserveCaseWithoutCookies()`. I'll try to make it compatible in the next release.

**Comment by albertcht** [comment]
Hi @mouhsinelonly ,

This issue has been fixed in the release `v2.3.2`. You can go check it again.
