### ISSUE TITLE
How can I do right routes and controllers with swoole in laravel?

### ISSUE THREAD

**Issue by vodniciarv** [swooletw/laravel-swoole#253]
I installed everything according to the instructions and the project started:
[![enter image description here][1]][1]

I read [wiki][2] on Github,and  on point 7 was this rout example:

    Websocket::on('connect', function ($websocket, Request $request) {
        // called while socket on connect
        $websocket->emit('message', 'hello world');
    });
    
    Websocket::on('disconnect', function ($websocket) {
        // called while socket on disconnect
    });
    
    Websocket::on('example', function ($websocket, $data) {
        $websocket->emit('message', 'response from example action');
    });
    
    Websocket::on('message', function ($websocket, $data) {
        $websocket->emit('message', 'response from message action');
        // $websocket->push('message', 'response from message action by push');
    });
    
    Websocket::on('test', 'Users/Telegram@connectServers');
    Websocket::on('joinToRoom', 'Users/Telegram@joinToRoom');

Now, when it’s connecting (I use [this][3] for tests) there is just a message `hello word` and every message I used to send, have no answer. 

Why?

How can I do right routes and controllers with **swoole** in **laravel**?

  [1]: https://i.stack.imgur.com/sVuVQ.png
  [2]: https://github.com/swooletw/laravel-swoole/wiki
  [3]: https://chrome.google.com/webstore/detail/web-socket-client/lifhekgaodigcpmnakfhaaaboididbdn

**Comment by albertcht** [comment]
What you need is a socket.io client instead of native websocket client. Try this one: http://amritb.github.io/socketio-client-tool/

**Comment by vodniciarv** [comment]
I can not check because, unfortunately, I have already decided not to use swoole.
Thanks for the answer.
