### ISSUE TITLE
Any similar helper function like dd()?

### ISSUE THREAD

**Issue by pingcheng** [swooletw/laravel-swoole#254]
Hi,

Since the running method switched to daemon mode, the old dd() method is not suitable for debugging anymore.

Just wondering if the package provided an alternative method to do well-formated debug printing? As the outputting format from var_dump is really unreadable sometimes. If not yet, I'll try to replicate the dd() method and submit a pull request if I got time.

Cheers

**Comment by albertcht** [comment]
Hi @pingcheng ,

You can consider using https://github.com/beyondcode/laravel-dump-server as an alternative.

**Comment by pingcheng** [comment]
thank @albertcht 
I added an extra class to mimic the traditional dd() without disrupting the process.
#255 is for the update, feel free to take it if you would like to add it to your official repo
