### ISSUE TITLE
Auth::check() returns true/false randomly

### ISSUE THREAD

**Issue by ahmed-javed** [swooletw/laravel-swoole#258]
1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`) 
`PHP 7.2` and `swoole-4.3.1`

2. Please provide your Laravel/Lumen version. 
Laravel `5.6`

3. Which release version of this package are you using? 
`2.6.5.4`

4. What did you do? If possible, provide a recipe for reproducing the error.
In `.env` Set `SWOOLE_NUM_WORKER = 2`

5. What did you expect to see?
`Auth::check()` to return true

6. What did you see instead?
Each swoole worker returns random values, sometimes it returns `true` and some times `false`.

Auth is resolving for every request.

**Comment by hypernics** [comment]
Do you add `auth` to `instances` in swoole_http config?

```
// Instances here will be cleared on every request.
    'instances' => [
        'auth',
    ],
```

**Comment by ahmed-javed** [comment]
@hypernics yes below are my `instances` and `providers`
`
/*
    |--------------------------------------------------------------------------
    | Instances here will be cleared on every request.
    |--------------------------------------------------------------------------
    */
    'instances' => [
       'auth',
    ],

    /*
    |--------------------------------------------------------------------------
    | Providers here will be registered on every request.
    |--------------------------------------------------------------------------
    */
    'providers' => [
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Auth\AuthServiceProvider::class,
    ],
`
@albertcht please let me know what else info you need

**Comment by aftabnaveed** [comment]
I am having exactly the same issue, when `SWOOLE_NUM_WORKER` is set to more than 1 I worker returns `true`  and the other returns `false` for `Authe::check()`   @albertcht what additional info is needed, can you please suggest? I am happy to provide that.

**Comment by albertcht** [comment]
To make your issue simpler, please refer to [Debug-Guideline](https://github.com/swooletw/laravel-swoole/wiki/Z3.-Debug-Guideline) first and set the worker number to `1`.

Questions:
* How do you verify that your auth instance is being resolved in every request?
* Do you install other third-party packages which are related to routing or authentication?
* Are you able to reproduce this issue in a refresh laravel project?

Also, try to provide a minimal code/project which can reproduce your issue if possible.

**Comment by aftabnaveed** [comment]
Sorry for not being clear. I did follow those guidelines the `Auth::check()` works fine if the number of workers is set to `1`. However, the problem starts when you set it two or more.

**Comment by albertcht** [comment]
> The Auth::check() works fine if the number of workers is set to 1. However, the problem starts when you set it two or more.

This sounds pretty weird if you take a look at [Swoole Structure](https://github.com/swooletw/laravel-swoole/wiki/2.-Swoole-Structure). All the resources are isolated in different workers(processes). If it works fine in one worker, it should work in other workers. There's no reason that your issue only happens in multiple workers.

**Comment by crcms** [comment]
Yes I also have the same problem, 2 workers, 3 people online at the same time, there will often be a drop, when checking
