### ISSUE TITLE
[ERROR]: Headers already sent

### ISSUE THREAD

**Issue by lw9527** [swooletw/laravel-swoole#259]
When using the laravel-swoole, the maatwebsites/excel can not export an excel. The problem is '[ERROR]: Headers already sent'  and the code in the maatwebsites/excel use the function of header() . 
 Is there any solution or suggestion ？ Thanks！

**Comment by serdarozturk** [comment]
Do you use the return statement in your function?

`
return Excel::download(new InvoicesExport, 'invoices.xlsx');
`

I'm using that package. There is no problem.
