### ISSUE TITLE
Form request validation does not work sometimes

### ISSUE THREAD

**Issue by serdarozturk** [swooletw/laravel-swoole#260]
1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
PHP 7.2.15-0ubuntu0.18.04.2

2. Please provide your Laravel/Lumen version.
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.1
Built => Mar 26 2019 13:47:22
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled
Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

3. Which release version of this package are you using?
laravel-swoole - 2.6.5.4
laravel 5.7

4. What did you do? If possible, provide a recipe for reproducing the error.
I can't reproduce this issue on my local and staging env. (staging and production env are same)

5. What did you expect to see?
Data validation success.

6. What did you see instead?
Form requests validation does not work sometimes. (%3-5)
- I Filled all form inputs
- I submitted form
- Form values are returned as never filled. But all form fields filled with old helper after the validation fail redirection page.

Example: https://cdn3.imggmi.com/uploads/2019/4/19/ae27a4b54c33203040675bdaa8942d1d-full.jpg

Our staging and production environment
* Cloudflare (Full SSL) -> Nginx (With SSL Certificate) -> Laravel Swoole (SWOOLE_SOCK_TCP No SSL) (using with supervisord)

Note: number of simultaneous visitors: 50 up to 100 sometimes

**Comment by albertcht** [comment]
Hi @serdarozturk ,

Can you please follow the [Debug Guideline](https://github.com/swooletw/laravel-swoole/wiki/Z3.-Debug-Guideline) and set your worker number to `1` first?

I'm not able to give any other suggestions until there are more details. Especially there's no reproducible steps to follow.
