### ISSUE TITLE
Hi, Albert Chen , I have a question to ask for advice  when I use broadcast() 

### ISSUE THREAD

**Issue by cielu** [swooletw/laravel-swoole#265]
-  If I push to more than one million people,  The system wouldn't be crashed? (Because I thought foreach can't support such amount)

- How about use queue, when push to all people, dispatch a RoomPushJob, like

```
foreach($Rooms as $room){
    dispatch(new RoomPushJob($room));
}

# and RoomPush would be like that

hand(){
   $roomClients = Room::getClients($room);
    foreach($roomClients as $client){
         Websocket::to($client)->emit('event',$data);
    }
}

``

**Comment by albertcht** [comment]
Hi @cielu ,

I'm on vacation now. I will reply this issue after 5/5.

**Comment by albertcht** [comment]
Hi @cielu ,

Thanks for your waiting, currently the websocket server built in this package doesn't provide the ability for horizontal scaling. That means, the max connections totally depends on your server's hardware limitation.

I would suggest you find another alternative such as pusher/pubnub for your requirement.
