### ISSUE TITLE
Enabling Blackfire in Swoole

### ISSUE THREAD

**Issue by SonarSoftware** [swooletw/laravel-swoole#266]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

PHP 7.2.16
Swoole 4.3.3

2. Please provide your Laravel/Lumen version.

5.7

3. Which release version of this package are you using?

2.6

I'm trying to get Blackfire working with Swoole - there's an existing package on https://packagist.org/packages/upscale/swoole-blackfire that enables this. I can't figure out where I can inject it though. Can you help?

**Comment by albertcht** [comment]
Hi @SonarSoftware ,

I haven't tested with that package yet. It looks like you only need to inject the swoole server instance into its profiler like this:

```
// put in somewhere in the service provider
$profiler = new \Upscale\Swoole\Blackfire\Profiler();
$profiler->instrument(app('swoole.server'));
```

**Comment by SonarSoftware** [comment]
Great, thanks - I will give that a shot.
