### ISSUE TITLE
DNS Lookup resolve failed

### ISSUE THREAD

**Issue by lilianjin** [swooletw/laravel-swoole#267]
SwooleTW \ Http \ Coroutine \ ConnectionException (704)
DNS Lookup resolve failed
1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

+-----------------+-----------------------------------------+
| Name            | Value                                   |
+-----------------+-----------------------------------------+
| PHP Version     | 7.3.4                                   |
| Swoole Version  | 4.3.2                                   |
| Laravel Version | 5.8.16                                  |
| Listen IP       | 127.0.0.1                               |
| Listen Port     | 1215                                    |
| Server Status   | Online                                  |
| Reactor Num     | 12                                      |
| Worker Num      | 12                                      |
| Task Worker Num | 0                                       |
| Websocket Mode  | Off                                     |
| PID             | 31424                                   |
| Log Path        | /sites/pay/storage/logs/swoole_http.log |
+-----------------+-----------------------------------------+

```php
/sites/pay/vendor/swooletw/laravel-swoole/src/Coroutine/PDO.php
    protected function setClient($client = null)
    {
        $this->client = $client ?: new \Swoole\Coroutine\Mysql;
    }
 
    /**
     * @param array $options
     *
     * @return $this
     * @throws \SwooleTW\Http\Coroutine\ConnectionException
     */
    protected function connect(array $options = [])
    {
        $this->client->connect($options);
 
        if (! $this->client->connected) {
            $message = $this->client->connect_error ?: $this->client->error;
            $errorCode = $this->client->connect_errno ?: $this->client->errno;
 
            throw new ConnectionException($message, $errorCode);
        }
 
        return $this;
    }
 



80
SwooleTW\Http\Coroutine\ConnectionException 
…/vendor/swooletw/laravel-swoole/src/Coroutine/PDO.php81
79
SwooleTW\Http\Coroutine\PDO connect
…/vendor/swooletw/laravel-swoole/src/Coroutine/PDO.php56
78
SwooleTW\Http\Coroutine\PDO __construct
…/vendor/swooletw/laravel-swoole/src/Coroutine/Connectors/MySqlConnector.php28
77
SwooleTW\Http\Coroutine\Connectors\MySqlConnector createPdoConnection
…/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php46
76
Illuminate\Database\Connectors\Connector createConnection
…/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php24
75
Illuminate\Database\Connectors\MySqlConnector connect
…/vendor/swooletw/laravel-swoole/src/HttpServiceProvider.php218
74
SwooleTW\Http\HttpServiceProvider getNewMySqlConnection
…/vendor/swooletw/laravel-swoole/src/HttpServiceProvider.php187
73
SwooleTW\Http\HttpServiceProvider SwooleTW\Http\{closure}
…/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php120
```

**Comment by albertcht** [comment]
Hi @lilianjin ,

I need the steps to which can reproduce this issue. Also, the coroutine feature provided by this package is not mature yet. I would suggest you not to use coroutine feature at this moment.
