### ISSUE TITLE
Unable to use in high version Laravel and php7.1 environments

### ISSUE THREAD

**Issue by qbhy** [swooletw/laravel-swoole#269]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
PHP => 7.1.12 
swoole Version => 4.3.3

2. Please provide your Laravel/Lumen version.
Laravel 5.8

3. Which release version of this package are you using?
v2.5.0

4. What did you do? If possible, provide a recipe for reproducing the error.
Executed the "php artisan swoole:http start" command

5. What did you expect to see?
normal operation

6. What did you see instead?
![image](https://user-images.githubusercontent.com/24204533/57564826-72120780-73e5-11e9-987a-9b8e52ab9800.png)

**Comment by lilianjin** [comment]
Please use v2.6 or later.

**Comment by qbhy** [comment]
![image](https://user-images.githubusercontent.com/24204533/57755013-5d55ac80-7722-11e9-8a4f-1dee97906350.png)
2.6.0 doc and facts do not match

**Comment by qbhy** [comment]
@albertcht

**Comment by qbhy** [comment]
![image](https://user-images.githubusercontent.com/24204533/57755177-c806e800-7722-11e9-9ab8-54dea5f43bac.png)
