### ISSUE TITLE
For Homestead 

### ISSUE THREAD

**Issue by XuanqiYan** [swooletw/laravel-swoole#270]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

2. Please provide your Laravel/Lumen version.

3. Which release version of this package are you using?

4. What did you do? If possible, provide a recipe for reproducing the error.

5. What did you expect to see?

6. What did you see instead?
 'server' => [
        'host' => env('SWOOLE_HTTP_HOST', '0.0.0.0')
         ....
]

**Comment by albertcht** [comment]
I can't quite understand this issue. Can you give me more detailed description?

**Comment by pingcheng** [comment]
I guess he is looking for how to get swoole work in homestead, if so, you can refer to https://www.jianshu.com/p/b868a247a1a9
