### ISSUE TITLE
Some  question for Request Header param and distributed for this repo

### ISSUE THREAD

**Issue by Ethennoob** [swooletw/laravel-swoole#272]
1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

```
PHP 7.2.17 (cli) (built: Apr 19 2019 02:13:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.17, Copyright (c) 1999-2018, by Zend Technologies
```

2. Please provide your Laravel/Lumen version.

```
"laravel/framework": "5.5.*"
```

3. Which release version of this package are you using?

```
"name": "swooletw/laravel-swoole",
"version": "v2.5.0",
"source": {
       "type": "git",
       "url": "https://github.com/swooletw/laravel-swoole.git",
       "reference": "cbb99140660fc0b5e61685c9c043482a69fee665"
},
```

4. What did you do? If possible, provide a recipe for reproducing the error.

```html
Thank for your repo and help php improve performance ！

I want to get the io header param，because I want to authenticate
 for socket.io by myself，not Laravel official authenticate。

```
```javascript
const ws = io('http://127.0.0.1:1215', {
        transports: ['websocket'],
        //reconnection: true,
        extraHeaders: {
            Authorization: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvbWFsbC1sb2NhbC5ydW95dWJ1eS5jb20iLCJpYXQiOjE1MzkzMzE4ODIsImV4cCI6MTU0NzEwNzg4MiwibmJmIjoxNTM5MzMxODgyLCJqdGkiOiJBeDRZbFZmTE4zNTlxVUtJIiwic3ViIjoxNCwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.0uLObAVukno1MND3VnxRrypCK3YoKTZ0gE3thWt-Dtc'
        },
        query: {
            sid: '5555',
            Authorization: 'xxxxxxxxyyyyyyyy'
        }
    });
```

5. What did you expect to see?

* **_i can't get extraHeaders param ，so how to get request header param？_**

* **_Can this repo be distributed? if not, can you have a plan? I can also participate._**

Sorry my poor English 

Thanks

**Comment by albertcht** [comment]
Hi @Ethennoob ,

Please refer to [Websocket](https://github.com/swooletw/laravel-swoole/wiki/7.-Websocket). You can add your authentication in `connect` callback.

```php
Websocket::on('connect', function ($websocket, $request) {
    // authentication
    // ......
    // disconnect if failed
    $websocket->disconnect();
});
```

**Comment by amirhs712** [comment]
> Hi @Ethennoob ,
> 
> Please refer to [Websocket](https://github.com/swooletw/laravel-swoole/wiki/7.-Websocket). You can add your authentication in `connect` callback.
> 
> ```
> Websocket::on('connect', function ($websocket, $request) {
>     // authentication
>     // ......
>     // disconnect if failed
>     $websocket->disconnect();
> });
> ```

@albertcht How to retrieve `extraHeaders` ? sending tokens in the body instead of the header is not secure. (#151 He had to remove the Authorization header and use the `token` parameter in the `query` option for socket.io.)
