### ISSUE TITLE
Run scheduled tasks on Swoole

### ISSUE THREAD

**Issue by angelocala94** [swooletw/laravel-swoole#273]
No issues, just a question. There is a way to run Laravel scheduler on Swoole? Maybe with [Swoole Async IO](https://www.swoole.co.uk/docs/modules/swoole-async-io)?

**Comment by albertcht** [comment]
Hi @angelocala94 ,

You can refer to [Swoole's Queue Driver](https://github.com/swooletw/laravel-swoole/wiki/Z5.-Sub-Features#swoole-driver-for-queue).

**Comment by angelocala94** [comment]
I mean scheduled tasks (Kernel.php), not Queues.

**Comment by albertcht** [comment]
Hi @angelocala94 ,

Ok, no, this package doesn't support this feature.
