### ISSUE TITLE
Reset LARAVEL_START

### ISSUE THREAD

**Issue by sweebee** [swooletw/laravel-swoole#274]
I'm using Laravel Telescope which uses the LARAVEL_START contant to check the request time. But since its defined on start of swoole i get requests like 3000000ms in Telescope.

Is there a way to reset the LARAVEL_START to get accurate response times?

**Comment by albertcht** [comment]
Hi @sweebee ,

If `LARAVEL_START` is a const variable. In PHP's lifecycle, there's no way to change it.

**Comment by roboticsexpert** [comment]
i think we can do this with https://github.com/zenovich/runkit

do you like to have this feature in this repo?
if you like , i can create merge request for you :)
