### ISSUE TITLE
config swoole.http.server.process_type

### ISSUE THREAD

**Issue by wenjy** [swooletw/laravel-swoole#275]
https://github.com/swooletw/laravel-swoole/blob/d7249f922065c6c85bc1aa21e6b1ecb09909030e/src/HttpServiceProvider.php#L138

It`s swoole_http.server.process_type ?

**Comment by albertcht** [comment]
Hi @wenjy ,

Thanks for your report, I will fix this typo as soon as possible.

**Comment by albertcht** [comment]
Fixed in the release v2.6.61
