### ISSUE TITLE
Laravel Swoole HTTP2

### ISSUE THREAD

**Issue by gofish543** [swooletw/laravel-swoole#276]
How can I enable HTTP2 with this package? I'm injecting ` 'open_http2_protocol' => true` directly into the config, but it still is not serving pages as HTTP2

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
php -v

PHP 7.3.5-1+ubuntu19.04.1+deb.sury.org+1 (cli) (built: May  3 2019 10:01:08) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans
    with Zend OPcache v7.3.5-1+ubuntu19.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

php --ri swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.4
Built => May 19 2019 15:52:58
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1b  26 Feb 2019
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

2. Please provide your Laravel/Lumen version.
Laravel 5.8.17
3. Which release version of this package are you using?
Swoole 2.6.6

**Comment by albertcht** [comment]
Hi @gofish543 ,

According to official documentation, you need to configure the socket type as well.

```php
$serv = new Swoole\Http\Server("127.0.0.1", 9501, SWOOLE_PROCESS, SWOOLE_SOCK_TCP | SWOOLE_SSL);
$serv->set([
    'ssl_cert_file' => $ssl_dir . '/ssl.crt',
    'ssl_key_file' => $ssl_dir . '/ssl.key',
    'open_http2_protocol' => true,
]);
```

Try to set `SWOOLE_SOCK_TCP | SWOOLE_SSL` in `socket_type` of `swoole_http.php`

**Comment by gofish543** [comment]
![image](https://user-images.githubusercontent.com/10394554/58375290-ea63e700-7f14-11e9-8aca-f75f653f9960.png)

**Comment by albertcht** [comment]
Http 2 client doesn't support respond with chunked body.

**Comment by albertcht** [comment]
Try to remove chunk in `Response.php` to see if it works.
