### ISSUE TITLE
How to heat update？

### ISSUE THREAD

**Issue by im-zhangxi** [swooletw/laravel-swoole#277]
docker-compose up info.
![image](https://user-images.githubusercontent.com/18593080/58221934-f1d59580-7d46-11e9-9f30-a844824be967.png)

postman require api. 

![image](https://user-images.githubusercontent.com/18593080/58221939-f8fca380-7d46-11e9-8fc6-25a593e1f1ae.png)

I want to debug. must docker-compose restart.
![image](https://user-images.githubusercontent.com/18593080/58222002-382af480-7d47-11e9-99f0-a7518aa5b5b6.png)

help me!

**Comment by albertcht** [comment]
Please refer to [6.-Commands](https://github.com/swooletw/laravel-swoole/wiki/6.-Commands). Run `php artisan swoole:http restart`.
