### ISSUE TITLE
Error for websocker in lumen

### ISSUE THREAD

**Issue by huangdijia** [swooletw/laravel-swoole#278]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

> PHP 7.3.5 (cli) (built: May  2 2019 12:40:36) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
>     with Zend OPcache v7.3.5, Copyright (c) 1999-2018, by Zend Technologies

> swoole
> 
> Swoole => enabled
> Author => Swoole Team <team@swoole.com>
> Version => 4.3.3
> Built => May 14 2019 09:27:58
> coroutine => enabled
> kqueue => enabled
> rwlock => enabled
> http2 => enabled
> pcre => enabled
> zlib => enabled
> brotli => enabled
> async_redis => enabled
> 
> Directive => Local Value => Master Value
> swoole.enable_coroutine => On => On
> swoole.display_errors => On => On
> swoole.use_shortname => On => On
> swoole.unixsock_buffer_size => 262144 => 262144

2. Please provide your Laravel/Lumen version.

> laravel/lumen-framework               v5.8.7  The Laravel Lumen Framework.

3. Which release version of this package are you using?

> swooletw/laravel-swoole               v2.6.6  High performance HTTP server based on Swoole. Speed up your Laravel and Lumen applications.

4. What did you do? If possible, provide a recipe for reproducing the error.

> Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\Manager in /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php:973
> Stack trace:
> #0 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(911): Illuminate\Container\Container->unresolvablePrimitive(Object(ReflectionParameter))
> #1 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(852): Illuminate\Container\Container->resolvePrimitive(Object(ReflectionParameter))
> #2 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(818): Illuminate\Container\Container->resolveDependencies(Array)
> #3 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(667): Illuminate\Container\Container->build('Illuminate\\Sess...')
> #4 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(615): Illuminate\Container\Container->resolve('Illuminate\\Sess...', Array)
> #5 /Users/hdj/gitroot/hk8591/im/vendor/laravel/lumen-framework/src/Application.php(267): Illuminate\Container\Container->make('Illuminate\\Sess...', Array)
> #6 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(925): Laravel\Lumen\Application->make('Illuminate\\Sess...')
> #7 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(853): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
> #8 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(818): Illuminate\Container\Container->resolveDependencies(Array)
> #9 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(667): Illuminate\Container\Container->build('SwooleTW\\Http\\W...')
> #10 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(615): Illuminate\Container\Container->resolve('SwooleTW\\Http\\W...', Array)
> #11 /Users/hdj/gitroot/hk8591/im/vendor/laravel/lumen-framework/src/Application.php(267): Illuminate\Container\Container->make('SwooleTW\\Http\\W...', Array)
> #12 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/pipeline/Pipeline.php(152): Laravel\Lumen\Application->make('SwooleTW\\Http\\W...')
> #13 /Users/hdj/gitroot/hk8591/im/vendor/swooletw/laravel-swoole/src/Websocket/Middleware/DecryptCookies.php(71): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #14 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/pipeline/Pipeline.php(163): SwooleTW\Http\Websocket\Middleware\DecryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
> #15 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #16 /Users/hdj/gitroot/hk8591/im/vendor/swooletw/laravel-swoole/src/Websocket/Websocket.php(448): Illuminate\Pipeline\Pipeline->then(Object(Closure))
> #17 /Users/hdj/gitroot/hk8591/im/vendor/swooletw/laravel-swoole/src/Websocket/Websocket.php(259): SwooleTW\Http\Websocket\Websocket->setRequestThroughMiddleware(Object(Illuminate\Http\Request))
> #18 /Users/hdj/gitroot/hk8591/im/vendor/swooletw/laravel-swoole/src/Concerns/InteractsWithWebsocket.php(76): SwooleTW\Http\Websocket\Websocket->call('connect', Object(Illuminate\Http\Request))
> #19 {main}

**Comment by albertcht** [comment]
Please provide more description, thanks.

**Comment by huangdijia** [comment]
当我在 routes/websocket.php 中启用任意监听，就报这个错误，关闭就没报了。

**Comment by huangdijia** [comment]
重现步骤

1、创建项目 lumen new new-project

2、复制配置&路由

```bash
mkdir config
cp vendor/swooletw/laravel-swoole/config/swoole_* config/
cp vendor/swooletw/laravel-swoole/routes/websocket.php config/
```

3、注册服务及配置
编辑 bootstrap/app.php，添加

```php
$app->register(SwooleTW\Http\LumenServiceProvider::class);
$app->configure('swoole_http');
$app->configure('swoole_websocket');
```

4、启动服务

```php
php artisan swoole:http start
```

5、连接websocket看到错误如下

> [2019-05-24 11:05:19] dev.ERROR: Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\Manager in /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php:973
> Stack trace:
> #0 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(911): Illuminate\Container\Container->unresolvablePrimitive(Object(ReflectionParameter))
> #1 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(852): Illuminate\Container\Container->resolvePrimitive(Object(ReflectionParameter))
> #2 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(818): Illuminate\Container\Container->resolveDependencies(Array)
> #3 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(667): Illuminate\Container\Container->build('Illuminate\\Sess...')
> #4 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(615): Illuminate\Container\Container->resolve('Illuminate\\Sess...', Array)
> #5 /Users/hdj/gitroot/hk8591/im/vendor/laravel/lumen-framework/src/Application.php(267): Illuminate\Container\Container->make('Illuminate\\Sess...', Array)
> #6 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(925): Laravel\Lumen\Application->make('Illuminate\\Sess...')
> #7 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(853): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
> #8 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(818): Illuminate\Container\Container->resolveDependencies(Array)
> #9 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(667): Illuminate\Container\Container->build('SwooleTW\\Http\\W...')
> #10 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(615): Illuminate\Container\Container->resolve('SwooleTW\\Http\\W...', Array)
> #11 /Users/hdj/gitroot/hk8591/im/vendor/laravel/lumen-framework/src/Application.php(267): Illuminate\Container\Container->make('SwooleTW\\Http\\W...', Array)
> #12 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/pipeline/Pipeline.php(152): Laravel\Lumen\Application->make('SwooleTW\\Http\\W...')
> #13 /Users/hdj/gitroot/hk8591/im/vendor/swooletw/laravel-swoole/src/Websocket/Middleware/DecryptCookies.php(71): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #14 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/pipeline/Pipeline.php(163): SwooleTW\Http\Websocket\Middleware\DecryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
> #15 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #16 /Users/hdj/gitroot/hk8591/im/vendor/swooletw/laravel-swoole/src/Websocket/Websocket.php(448): Illuminate\Pipeline\Pipeline->then(Object(Closure))
> #17 /Users/hdj/gitroot/hk8591/im/vendor/swooletw/laravel-swoole/src/Websocket/Websocket.php(259): SwooleTW\Http\Websocket\Websocket->setRequestThroughMiddleware(Object(Illuminate\Http\Request))
> #18 /Users/hdj/gitroot/hk8591/im/vendor/swooletw/laravel-swoole/src/Concerns/InteractsWithWebsocket.php(76): SwooleTW\Http\Websocket\Websocket->call('connect', Object(Illuminate\Http\Request))
> #19 {main} {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\\Support\\Manager at /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php:973)
> [stacktrace]
> #0 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(911): Illuminate\\Container\\Container->unresolvablePrimitive(Object(ReflectionParameter))
> #1 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(852): Illuminate\\Container\\Container->resolvePrimitive(Object(ReflectionParameter))
> #2 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(818): Illuminate\\Container\\Container->resolveDependencies(Array)
> #3 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(667): Illuminate\\Container\\Container->build('Illuminate\\\\Sess...')
> #4 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(615): Illuminate\\Container\\Container->resolve('Illuminate\\\\Sess...', Array)
> #5 /Users/hdj/gitroot/hk8591/im/vendor/laravel/lumen-framework/src/Application.php(267): Illuminate\\Container\\Container->make('Illuminate\\\\Sess...', Array)
> #6 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(925): Laravel\\Lumen\\Application->make('Illuminate\\\\Sess...')
> #7 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(853): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
> #8 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(818): Illuminate\\Container\\Container->resolveDependencies(Array)
> #9 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(667): Illuminate\\Container\\Container->build('SwooleTW\\\\Http\\\\W...')
> #10 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(615): Illuminate\\Container\\Container->resolve('SwooleTW\\\\Http\\\\W...', Array)
> #11 /Users/hdj/gitroot/hk8591/im/vendor/laravel/lumen-framework/src/Application.php(267): Illuminate\\Container\\Container->make('SwooleTW\\\\Http\\\\W...', Array)
> #12 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/pipeline/Pipeline.php(152): Laravel\\Lumen\\Application->make('SwooleTW\\\\Http\\\\W...')
> #13 /Users/hdj/gitroot/hk8591/im/vendor/swooletw/laravel-swoole/src/Websocket/Middleware/DecryptCookies.php(71): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #14 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/pipeline/Pipeline.php(163): SwooleTW\\Http\\Websocket\\Middleware\\DecryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #15 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/pipeline/Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #16 /Users/hdj/gitroot/hk8591/im/vendor/swooletw/laravel-swoole/src/Websocket/Websocket.php(448): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
> #17 /Users/hdj/gitroot/hk8591/im/vendor/swooletw/laravel-swoole/src/Websocket/Websocket.php(259): SwooleTW\\Http\\Websocket\\Websocket->setRequestThroughMiddleware(Object(Illuminate\\Http\\Request))
> #18 /Users/hdj/gitroot/hk8591/im/vendor/swooletw/laravel-swoole/src/Concerns/InteractsWithWebsocket.php(76): SwooleTW\\Http\\Websocket\\Websocket->call('connect', Object(Illuminate\\Http\\Request))
> #19 {main}
> "}

**Comment by albertcht** [comment]
ok, i will check it.

**Comment by albertcht** [comment]
Unable to reproduce this issue. I guess you uncommented the middleware in `swoole_websocket.php`, didn't you? There's no session in lumen, the middleware over there are just for reference.

**Comment by huangdijia** [comment]
No，I copy config file from package，and I do not anything in swoole_websocket.php

**Comment by albertcht** [comment]
Anyway, as you can see from your log, it was trying to build session manager. But there's no session in lumen, so the error occurred.

```
#4 /Users/hdj/gitroot/hk8591/im/vendor/illuminate/container/Container.php(615): Illuminate\Container\Container->resolve('Illuminate\Sess...', Array)
```

Check and dump the middleware in `swoole_websocket.php` config.

**Comment by huangdijia** [comment]
OK，I try again later，thanks

**Comment by huangdijia** [comment]
Ok now, I remove middlewares from swoole_websocket.php
