### ISSUE TITLE
room

### ISSUE THREAD

**Issue by liumingsongning** [swooletw/laravel-swoole#279]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

2. Please provide your Laravel/Lumen version.

3. Which release version of this package are you using?

4. What did you do? If possible, provide a recipe for reproducing the error.

5. What did you expect to see?

6. What did you see instead?

**Comment by liumingsongning** [comment]
![image](https://user-images.githubusercontent.com/17898154/58319428-752cdf00-7e4c-11e9-9c9e-267ba0620d8a.png)
room 是个共享的表吗？为什么我两个用户登录，都add到了同一个room，但获取的时候只能获取到各自的room信息呢？

**Comment by liumingsongning** [comment]
![image](https://user-images.githubusercontent.com/17898154/58319924-20d62f00-7e4d-11e9-83e5-626c21cf00f7.png)

**Comment by liumingsongning** [comment]
把websokcet的驱动改成redis就好了，难道是swoole-table 的问题？而且第一个客户端和第三个客户端会分在同一room， 二，四会分在同一room，难道你们没遇到过这个问题？

**Comment by albertcht** [comment]
Can you provide a detailed description and reproducible steps? thanks.

**Comment by albertcht** [comment]
This bug has been confirmed, will be fixed in the next release.

**Comment by albertcht** [comment]
Fixed in the release `v2.6.61`.
