### ISSUE TITLE
Uncaught Error: Call to a member function fire() on null in vendor/swooletw/laravel-swoole/src/Server/Manager.php:336

### ISSUE THREAD

**Issue by emielmolenaar** [swooletw/laravel-swoole#28]
Thank you for this great package!

I am running Swoole 2.1.3 on PHP 7.2.5 with Laravel 5.6.20 and seeing a Uncaught Error: Call to a member function fire() on null in vendor/swooletw/laravel-swoole/src/Server/Manager.php:336 in my Laravel logs. Has something to do with events, any idea?

**Comment by albertcht** [comment]
Hi @emielmolenaar ,

Thanks for your report, I'll fix it soon in the next release.

**Comment by albertcht** [comment]
Hi @emielmolenaar ,

This issue has been fixed in the release `v2.3.2`. You can go check it again.

**Comment by emielmolenaar** [comment]
Thank you very much @albertcht !

**Comment by albertcht** [comment]
Anytime :)

**Comment by TenMediaBln** [comment]
Hi! 

I'm getting:

Uncaught Error: Call to a member function fire() on null in /var/app/current/vendor/swooletw/laravel-swoole/src/Server/Manager.php:239

running on PHP 7.1.15 / Laravel 5.5 / laravel-swoole 2.3.9.

Sounds similar, is this a new issue or is it related to this one?

**Comment by albertcht** [comment]
Hi @TenMediaBln ,

No, I don't think they're relevant. Please follow [Debug Guideline](https://github.com/swooletw/laravel-swoole/wiki/Z3.-Debug-Guideline) and try to dump some data before line 239:

```php
var_dump(get_class($this->app));
var_dump($this->app['events']);
```

If any of these is null, that means maybe there's somewhere in your code causes this bug. And you can open another issue and provide more details.
