### ISSUE TITLE
【bug】php artisan swoole:http infos

### ISSUE THREAD

**Issue by legeng** [swooletw/laravel-swoole#281]
Task Worker Num  show count bug！

Your code is as follows：

1、src/Commands/HttpServerCommand.php:232
['Task Worker Num', $isWebsocket ? $taskWorkerNum : 0]

2、src/HttpServiceProvider.php:152
// only enable task worker in websocket mode and for queue driver
if ($config->get('queue.default') !== 'swoole' && ! $this->isWebsocket) {            
     unset($options['task_worker_num']);
}

**Comment by albertcht** [comment]
Fixed in the release `v2.6.61`.

**Comment by legeng** [comment]
@albertcht  I want to know, why only enable task worker in websocket mode and for queue driver ? The official document of swoole has no such restrictions. Please enlighten me . thanks
