### ISSUE TITLE
laravel-permissions

### ISSUE THREAD

**Issue by prolic** [swooletw/laravel-swoole#284]
Anyone experience with running laravel-swoole together with https://github.com/spatie/laravel-permission? The problem I have is, that when I edit some permissions in the database, the laravel app still uses the old configuration, even when I delete the cache. It's somwhere stored in the app's state, but I don't know where exactly.

For now, when I edit permissions in the database, I need to restart swoole.

Any help is highly appreciated.

**Comment by albertcht** [comment]
Please refer to [Debug-Guideline](https://github.com/swooletw/laravel-swoole/wiki/Z3.-Debug-Guideline).
