### ISSUE TITLE
managerPid not set!

### ISSUE THREAD

**Issue by cielu** [swooletw/laravel-swoole#285]
![image](https://user-images.githubusercontent.com/13715811/59021987-824fc200-887f-11e9-8017-afd3f89027b1.png)

**Comment by albertcht** [comment]
Hi @cielu ,

Please refer to https://github.com/swooletw/laravel-swoole/releases and try:

```
Delete storage/swoole.pid file if you encounter an error after upgrading to `2.6.61`.
```
