### ISSUE TITLE
Run with in supervisor

### ISSUE THREAD

**Issue by sweebee** [swooletw/laravel-swoole#287]
I'm trying to run it with supervisor:

```
[program:swoole]
command=php /home/http/app/current/artisan swoole:http start
redirect_stderr=true
autostart=true
autorestart=true
user=http
numprocs=1
process_name=%(program_name)s_%(process_num)s

```

It works but I get these errors:

```
Starting swoole http server...
Swoole http server started: <http://127.0.0.1:1215>
> (You can run this command to ensure the swoole_http_server process is running: ps aux|grep "swoole")
Failed! swoole_http_server process is already running.
Failed! swoole_http_server process is already running.
Failed! swoole_http_server process is already running.
Failed! swoole_http_server process is already running.
```

What to do?

**Comment by pingcheng** [comment]
Try change this config value to false and try again
```
swoole_http.php.server.options.daemonize
```

**Comment by Quiss** [comment]
@pingcheng to false state, same behavior

**Comment by albertcht** [comment]
Do you check `ps aux|grep swoole` before running with supervisor?

**Comment by gofish543** [comment]
I ran into this same issue a few weeks ago. You *must* set daemonize to false.

**Comment by sweebee** [comment]
Thanks that works. But i'm using deployer to deploy the application.

when the deployment is finished it should restart. but it wont run in the background when i run:

```php artisan swoole:http restart```

**Comment by pingcheng** [comment]
> Thanks that works. But i'm using deployer to deploy the application.
> 
> when the deployment is finished it should restart. but it wont run in the background when i run:
> 
> `php artisan swoole:http restart`

is there any supporting information such as console output, and also how the deployment process works, is it like a ci/cd?

**Comment by sweebee** [comment]
Yes, for now this works for me:

```
task('swoole', 'php artisan swoole:http restart > /dev/null 2>&1 &')->onStage('swoole');
```

without ``` > /dev/null 2>&1 &``` it keeps "running", so the deployment will never finish because it wait s for swoole:http restart to be finshed.

**Comment by pingcheng** [comment]
i see, since you changed the `swoole_http.php.server.options.daemonize` to `false`

the `restart` command would stop the server and try to `start` it again, the trick part is you have  `false` on `daemonize`, the command would "block" the console forever, so your deployer think this command is still running. Therefore, your deployment would never finish.

You mentioned you used `supervisor` to start the server, so the *correct* way to restart the server is using `supervisorctl` command such as
```
supervisorctl restart *your_process_name*
```

hope it helps

**Comment by sweebee** [comment]
Got it. running ```php artisan swoole:http stop``` makes the swoole server stop while supervisor will start it again within seconds (-1s).
