### ISSUE TITLE
The websocket connection could not find the login info

### ISSUE THREAD

**Issue by zhongjq** [swooletw/laravel-swoole#288]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

PHP 7.2.19-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May 31 2019 11:16:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.3
Built => May 15 2019 12:12:22
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
http2 => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

2. Please provide your Laravel/Lumen version.
Laravel 5.7

3. Which release version of this package are you using?
v2.6.61

4. What did you do? If possible, provide a recipe for reproducing the error.
```php
Websocket::on('connect', function ($websocket, Request $request) {
    // called while socket on connect
    $user = $request->user();
    dump($user);
    if ($user){
        $websocket->loginUsing($user);
    }
});
```
5. What did you expect to see?
print the login user info

6. What did you see instead?
![image](https://user-images.githubusercontent.com/1228323/59480298-ad936c00-8e92-11e9-90ac-e2feb69089ba.png)

**Comment by nasservb** [comment]
i have the same problom

**Comment by zhongjq** [comment]
I observed that there seems to be a problem with the session. The server that passed the websocket generated a new session
Now I use the temporary method, which is to pass a login session
Client
```javascript
socket.on('connect', function () {
    socket.emit('login', "{{auth()->user()->id ?? 0}}");
});
```
Server
```php
Websocket::on('login', function ($websocket, $data) {
    if ($data){
        $websocket->loginUsingId($data);
    }
});
```

**Comment by fengxin2017** [comment]
same problem in laravel5.8.
the problem caused by ```SwooleTW\Http\Websocket\Middleware\StartSession::class,``` 
```
public function handle($request, Closure $next)
 {
      if ($this->sessionConfigured()) {
          $request->setLaravelSession($this->startSession($request));
      }

      return $next($request);
  }

// there is not option named session on laravel5.8. so add a option named session whatever just not null will fix it.
protected function sessionConfigured()
  {
      return Arr::get($this->manager->getSessionConfig(), 'session') !== null;
  }
```
