### ISSUE TITLE
Hot reload option is not working on Ubuntu 18.04 with fswatch 1.14.0

### ISSUE THREAD

**Issue by ghost** [swooletw/laravel-swoole#292]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

PHP 7.2.19-0ubuntu0.19.04.1 (cli) (built: Jun  4 2019 14:44:42) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.19.04.1, Copyright (c) 1999-2018, by Zend Technologies

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.4
Built => Jun  7 2019 18:38:06
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

2. Please provide your Laravel/Lumen version.

"laravel/framework": "5.8.*",

3. Which release version of this package are you using?

"swooletw/laravel-swoole": "^2.6"

4. What did you do? If possible, provide a recipe for reproducing the error.

I've installed fswatch via apt-get on Ubuntu 18.04, the version is fswatch 1.14.0.

I've started a fresh laravel project, installed laravel-swoole, added the provider, created the config file with:

php artisan vendor:publish --tag=laravel-swoole

and changed the hot_reload option to true:

    'hot_reload' => [
        'enabled' => env('SWOOLE_HOT_RELOAD_ENABLE', true),

I've changed laravel environment to development too, but when I start the swoole server with the command:

php artisan swoole:http start

And change some files, the server doesn't update them unless I restart the server.

What can I try to do? am I missing some step?

EDIT: I saw that the fswatch process starts together with swoole:

giovanni 12422  0.0  0.3 155340 25588 pts/0    S+   09:44   0:00 php artisan swoole:http start
giovanni 12423  0.0  0.0  11856  1968 pts/0    S+   09:44   0:00 fswatch -rtx -e .* -i \.php$ /home/giovanni/laravel

If there's something more I can try to debug this issue, please tell me.

**Comment by mxp100** [comment]
not work and in ubuntu 19.10

**Comment by albertcht** [comment]
I will check it out.

**Comment by albertcht** [comment]
This bug has been confirmed due to different fswatch output in different operating systems.

in ubuntu:
```
Sun 15 Sep 2019 12:59:06 PM UTC /root/laravel-benchmark/routes/api.php Updated
```

in macOS:
```
Sun Sep 15 20:54:55 2019 /Users/Albert/Projects/lumen58/vendor/swooletw/laravel-swoole/src/HotReload/FSProcess.php PlatformSpecific Updated IsFile
```

and the regex for the output is: '/^([\S+]{3}\s+[\S+]{3}\s+[\d+]{1,2}\s+[\d+]{2}:[\d+]{2}:{0,2}:[\d+]{2}:{0,2}\s+[\d+]{0,4})\s*(\/[\S+]*)\s+([\S+*\s+]*)/mi'
