### ISSUE TITLE
How to fire client-side callbacks from server ?

### ISSUE THREAD

**Issue by imanghafoori1** [swooletw/laravel-swoole#294]
Hi
I am using the laravel-swoole package for production and I appreciate your efforts.

But I came across something that was possible in node.js but not in swoole.

here we are emiting the client-side  event and pass a closure as payload

https://github.com/imanghafoori1/chat/blob/00dac755e25dd51834694961c26b8a20ecc594c9/index.html#L100

and on the server-side, the closure is passed to us, and we execute that closure.
`callback(true);`

https://github.com/imanghafoori1/chat/blob/00dac755e25dd51834694961c26b8a20ecc594c9/app.js#L18

is it possible to replace the node script with laravel swoole in this case ?

**Comment by albertcht** [comment]
Since the language for frontend and node.js are all `javascript`. But it's impossible to do that between javascript and PHP.
