### ISSUE TITLE
Is the laravel Redis facade non-blocking in laravel-swoole ?

### ISSUE THREAD

**Issue by imanghafoori1** [swooletw/laravel-swoole#297]
When I look at the service provider of the package I see that for sql queries it swaps the default laravel mysql driver with a non-blocking version named `"mysql-coroutine"`;

but for redis connections I do not see any swapping for something.
According to :
https://www.swoole.co.uk/docs/modules/swoole-async-redis-client

we should use swoole_redis class to interact with redis server in a non-blocking fashion. right ?
So should I use this class and avoid laravel Redis facade ?

**Comment by albertcht** [comment]
It's highly suggest not to use async or coroutine clients with this package at this moment. Since there's context switching problem for singleton instances.

**Comment by albertcht** [comment]
Coroutine feature is still in development and not for production yet.

**Comment by imanghafoori1** [comment]
So do you recommend using the blocking version of redis with swoole? or to avoid it ?

**Comment by albertcht** [comment]
Yes, please use blocking redis client in this package.

**Comment by imanghafoori1** [comment]
Wouldn't this be too bad for high traffic web site ? I think this is not affordable.

In advance, thanks for your answers.

**Comment by albertcht** [comment]
If you use redis as cache, you may consider using swoole table or apcu for multi-layer caching as an alternative.

**Comment by albertcht** [comment]
That will be no I/O consuming for cache purpose.
