### ISSUE TITLE
php7.2 Undefined offset bug fix

### ISSUE THREAD

**Issue by axiref** [swooletw/laravel-swoole#298]
1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.5
Built => Jul  2 2019 11:21:26
coroutine => enabled
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2s  28 May 2019
http2 => enabled
pcre => enabled
zlib => enabled
brotli => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144

2. Please provide your Laravel/Lumen version.
laravel 5.8

3. Which release version of this package are you using?
^2.6

4. What did you do? If possible, provide a recipe for reproducing the error.
```
php artisan swoole:http start
```

5. What did you expect to see?

ErrorException  : Undefined offset: 1
[$masterPid, $managerPid] = $pidManager->read();

6. What did you see instead?
ErrorException

I try to fix this problem, in`swooletw/laravel-swoole/src/Server/PidManager.php `,Line 58, add a line:

```php
isset($pids[1]) ?: $pids[1] = null;
```

Fix the problem

**Comment by rozbo** [comment]
php7.3.5 +1

**Comment by albertcht** [comment]
Thanks for your suggestion, I will be more careful about the breaking changes and version convention in the future.

And I release a new version for making pid file compatible with older versions.

**Comment by axiref** [comment]
> Thanks for your suggestion, I will be more careful about the breaking changes and version convention in the future.
> 
> And I release a new version for making pid file compatible with older versions.

Some things are getting worse!
I updated the package and got it "Undefined offset: 0" error
In PidManager.php, i see
```php
return [
            'masterPid' => $pids[0] ?? null,
            'managerPid' => $pids[1] ?? null
        ];
```
but in HttpServerCommand.php, Such deconstruction:
```php
[$masterPid, $managerPid] = $pids;
```
But its subscript is not a number, but masterPid, managerPid
so i see "Undefined offset: 0"

And...It does not automatically create a `swoole_http.pid` file
I manually created the file, entered some Numbers, and got the above error

**Comment by albertcht** [comment]
Is your `HttpServerCommand.php` up-to-date? https://github.com/swooletw/laravel-swoole/commit/5e2706999788814ac0dfcdbd34e8e93bad0d71e2

**Comment by axiref** [comment]
I reinstalled the package and still got the this error
I noticed the `isRunning` function in ` HttpServerCommand.php`, Is still
```php
[$masterPid, $managerPid] = $pids;
```
Although the showInfos function has made the fix...

**Comment by axiref** [comment]
I reinstalled the package and still got the this error
I noticed the `isRunning` function in ` HttpServerCommand.php`, Is still
```php
[$masterPid, $managerPid] = $pids;
```
Although the showInfos function has made the fix...

**Comment by axiref** [comment]
[this line](https://github.com/swooletw/laravel-swoole/blob/eafc1cfaa481ba6d855448c17de34f5108fd5e6d/src/Commands/HttpServerCommand.php#L289)

**Comment by albertcht** [comment]
Thanks for your reminding, fix it in the newest release.
