### ISSUE TITLE
Uncaught SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by shenjiayu** [swooletw/laravel-swoole#30]
Possible issue while accessing the `/horizon/dashboard` horizon.

Commands to run:
1. `php artisan horizon`
2. `php artisan queue:work --tries=3 --sleep=3`
3. `php artisan swoole:http start`

I have successfully accessed `/horizon/dashboard` using the regular valet dev environment.

Please investigate and thanks for your effort on this project.

**Comment by albertcht** [comment]
Hi @shenjiayu ,

Can you provide more detail about `Uncaught SyntaxError: missing ) after argument list` ? If you can provide a filename, line number will be great.

**Comment by albertcht** [comment]
Hi @shenjiayu ,

Ok, I think I understand what your title is talking about. However, `Uncaught SyntaxError: missing ) after argument list` is a js error shown on the console, but I can't find any error on PHP side.

**Comment by shenjiayu** [comment]
@albertcht Yes, It occurred on front-end. Last time I saw the similar issue was using the nginx container in docker-machine which required to set `sendfile off;` in nginx config.

But this time, I just started the server by running `php artisan swoole:http start` without using nginx as the ingress.

Could you reproduce the error on your side?

**Comment by albertcht** [comment]
Hi @shenjiayu ,

Yes, the same js error happens on my side. I'm curious about the reason causing this error as well.

**Comment by albertcht** [comment]
Hi @shenjiayu ,

Yes, the reason causing this issue is `sendfile`, Swoole server uses same `sendfile` kernel function to send files. But now sure why `sendfile` causes a js exception.

The better solution will be using Nginx to process static files, and Swoole only process non-static requests.
