### ISSUE TITLE
emit error

### ISSUE THREAD

**Issue by rajaie90149018** [swooletw/laravel-swoole#300]
hi
i try to emit to one user but be emit for last user connected to server too.
my code:
`
Websocket::on('connect', function ($websocket, Request $request) {   
  Websocket::join("JAVAD");
   $ab=Room::getClients("JAVAD");
   foreach($ab as $k){
	    Websocket::to($k)->emit('startGame',"ERRRRR");
		echo 'emit to '. $k."\n";//
   }
});
`

*****************************
when i emit to startGame for first connection , recive ERRRRR and when connect second user , first user recive one ERRRRR but second user recive two ERRRR.

**Comment by rajaie90149018** [comment]
im resolve this by change emit function in : 
swooletw/laravel-swoole/src/Websocket/Websocket.php
 
from : 
`    public function emit(string $event, $data): bool
    {
        $fds = $this->getFds();
        $assigned = ! empty($this->to);

        // if no fds are found, but rooms are assigned
        // that means trying to emit to a non-existing room
        // skip it directly instead of pushing to a task queue
        if (empty($fds) && $assigned) {
            return false;
        }
	
        $result = App::make(Server::class)->task([
            'action' => static::PUSH_ACTION,
            'data' => [
                'sender' =>$this->sender,    
                'fds' => $fds,
                'broadcast' => $this->isBroadcast,
                'assigned' => $assigned,
                'event' => $event,
                'message' => $data,
            ],
        ]);

        $this->reset();

        return $result !== false;
    }`

To : 
`    public function emit(string $event, $data): bool
    {
        $fds = $this->getFds();
        $assigned = ! empty($this->to);

        // if no fds are found, but rooms are assigned
        // that means trying to emit to a non-existing room
        // skip it directly instead of pushing to a task queue
        if (empty($fds) && $assigned) {
            return false;
        }

        $result = App::make(Server::class)->task([
            'action' => static::PUSH_ACTION,
            'data' => [
                'sender' =>-1,    
                'fds' => $fds,
                'broadcast' => $this->isBroadcast,
                'assigned' => $assigned,
                'event' => $event,
                'message' => $data,
            ],
        ]);

        $this->reset();

        return $result !== false;
    }`

because emit function push to sender and fds but this is wrrong
please help me to complete this.

**Comment by albertcht** [comment]
Read the document, please.

If you want to send to all clients in a room
```
Websocket::to('message')->emit('message', "test");
```

If you want to broadcast to other clients in this room (except sender)
```
Websocket::broadcast()->to('message')->emit('message', "test");
```

In your sample code, you called `emit` function several times. A sender id will be appended to senders list if you don't use `broadcast`. So the sender received several messages. That's it.

**Comment by jackchow123456** [comment]
1
