### ISSUE TITLE
laravel 5.8 removed "fire",  change to "dispatch"

### ISSUE THREAD

**Issue by crystal9002** [swooletw/laravel-swoole#301]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
7.1

2. Please provide your Laravel/Lumen version.
5.8

3. Which release version of this package are you using?
v2.6.61

4. What did you do? If possible, provide a recipe for reproducing the error.
php artisan swoole:http start

5. What did you expect to see?

6. What did you see instead?

**Comment by albertcht** [comment]
Which part are you talking about? Events? The events in this package should all be trigged by `dispatch` function.

**Comment by axiref** [comment]
So you should update your PHP version
`laravel-swoole` Request your PHP version >= 7.2
So that you can get the fix, u can use the `dispatch()`

**Comment by crystal9002** [comment]
sorry, my mistake. After upgraded my php & composer,  It works.
