### ISSUE TITLE
This is too slow for swoole

### ISSUE THREAD

**Issue by johnlanz** [swooletw/laravel-swoole#305]
Why is this framework too slow?
I've tried to test it with wrk (https://github.com/wg/wrk) on my 6 year old pc.
ordinary/basic swoole i got: 200k request per second
swoole using siler rest api (no database, just array to json): 100k rps
laravel-swoole without database: 9k rps
Its weird because zend expressive swoole is the same as you guys (around 10k rps)
My question is why is it too slow? 
I wanted to use it and my requirements is around 50k api request a second, is it possible?

**Comment by johnlanz** [comment]
another thing swoole with middleware on it like fastroute, etc i got 190k rps, so it shouldn't be 9k rps for laravel right?

**Comment by albertcht** [comment]
Dude, this is Laravel.

**Comment by johnlanz** [comment]
If its not possible in laravel. It is possible to make it more faster in lumen right?

**Comment by albertcht** [comment]
The benchmark for Lumen is supposed to be better than Laravel.
