### ISSUE TITLE
socket.io not working continuously

### ISSUE THREAD

**Issue by nasservb** [swooletw/laravel-swoole#306]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
PHP 7.3.6-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May 31 2019 11:06:48) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.6-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
------------
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.5
Built => Jun 21 2019 10:24:46
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1c  28 May 2019
http2 => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

2. Please provide your Laravel/Lumen version.

laravel/framework": "5.8.*"

3. Which release version of this package are you using?

"swooletw/laravel-swoole": "^2.6"

4. What did you do? If possible, provide a recipe for reproducing the error.

i run swoole server by 
php artisan swoole:http start
and after several minuts socket.io server does not work .

5. What did you expect to see?

after several time after every request server not work and no response . 

6. What did you see instead?
 socket.emit('requestMatch',{token: token }); 
no response
i use some timer in code . i think timer count is max after some minuets.

**Comment by albertcht** [comment]
Can you give more specific description? Or provide more debug steps/results?

**Comment by nasservb** [comment]
i have some timer in game and two player want to join room and play the game .
 when every player play rand changed . every player have a 10 sec turn . 
when turn finished rand must be switched by timer . 
my game work fine but after several hour that not work and every request generate error like : 

[2019-07-11 18:00:46 $29792.0]	WARNING	swManager_check_exit_status: worker#3[pid=30474] abnormal exit, status=255, signal=0

you could see all the project here : 
https://github.com/nasservb/swoole_socketio_game

/route/websocket.php 
and 
/app/http/controllers/gameControllers.php 
is the main project files . 
thank you for your response.

**Comment by albertcht** [comment]
Thanks, I will go check it.

**Comment by albertcht** [comment]
`status=255` means there's `Fatal Error` in your PHP code. I doubt something in `websocket.php` breaks the process.

**Comment by nasservb** [comment]
why this code is running without error when i restart swoole server . i think some bug in swoole(timer) or laravel-swoole raise that error because i put all the code of functions in try/catch block but that error raise again .

**Comment by mxp100** [comment]
remember all exception and dies is destroy swoole process,
as idea my be extend Laravel Exception Handler for swoole?

**Comment by albertcht** [comment]
I think Laravel's original exception handler can catch this unexpected exception. You can check Laravel's error log to see if there's any clues.

**Comment by nasserniazy** [comment]
> I think Laravel's original exception handler can catch this unexpected exception. You can check Laravel's error log to see if there's any clues.

this is laravel log : 
`[2019-07-11 18:00:46 $29792.0]	WARNING	swManager_check_exit_status: worker#3[pid=30474] abnormal exit, status=255, signal=0`

**Comment by albertcht** [comment]
Hi @nasserniazy , this is Swoole's error log. I need the error log of Laravel.

**Comment by mxp100** [comment]
check with swoole table instead redis
may be trouble with this:
https://github.com/swooletw/laravel-swoole/blob/8b6ffc002a0afafa27ba204d6725a15e7d5a6ae9/src/Websocket/Rooms/RedisRoom.php#L48

**Comment by mxp100** [comment]
may be it's restarting workers by timeout?
