### ISSUE TITLE
websocket for swoole 4.4.0 is not work

### ISSUE THREAD

**Issue by zhongjq** [swooletw/laravel-swoole#307]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
php 7.3.7
swoole 4.4.0

2. Please provide your Laravel/Lumen version.
5.7.*

3. Which release version of this package are you using?
2.6.63

4. What did you do? If possible, provide a recipe for reproducing the error.

websocket is not work

log

ErrorException: Swoole\WebSocket\Server::push(): the connected client of connection[5] is not a websocket client or closed in /mnt/data/wwwroot/test.qtopay.net/vendor/swooletw/laravel-swoole/src/Websocket/SocketIO/WebsocketHandler.php:36
Stack trace:
#0 /mnt/data/wwwroot/test.qtopay.net/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Swoole\\WebSocke...', '/mnt/data/wwwro...', 36, Array)
#1 [internal function]: Raven_Breadcrumbs_ErrorHandler->handleError(2, 'Swoole\\WebSocke...', '/mnt/data/wwwro...', 36, Array)
#2 /mnt/data/wwwroot/test.qtopay.net/vendor/swooletw/laravel-swoole/src/Websocket/SocketIO/WebsocketHandler.php(36): Swoole\WebSocket\Server->push(5, '0{"sid":"NWQyYW...')
#3 /mnt/data/wwwroot/test.qtopay.net/vendor/swooletw/laravel-swoole/src/Concerns/InteractsWithWebsocket.php(95): SwooleTW\Http\Websocket\SocketIO\WebsocketHandler->onOpen(5, Object(Illuminate\Http\Request))
#4 {main}

5. What did you expect to see?

6. What did you see instead?

degrade swoole to 4.3.5   it's work success

**Comment by albertcht** [comment]
I will check it soon.

**Comment by mxp100** [comment]
add to nginx config
`proxy_http_version 1.1;`

**Comment by zhongjq** [comment]
> add to nginx config
> `proxy_http_version 1.1;`

thanks, it's work

**Comment by zhongjq** [comment]
> add to nginx config
> `proxy_http_version 1.1;`

@mxp100  Thanks, It's work!
