### ISSUE TITLE
Can't acces swoole.websocket facade in swoole job

### ISSUE THREAD

**Issue by mxp100** [swooletw/laravel-swoole#309]
PHP: 7.2.19
Swoole: 4.4.0
Laravel: 5.8.28
Laravel-swoole: 2.6.63
Queue connection: swoole

Dispatch task:
 ```php
public function connect(Websocket $websocket, Request $request)
{
    $fd = $websocket->getSender();
    dispatch(new Ping($fd))->delay(3);
}
```
Job handler:
```php 
public function handle()
{
    Websocket::to($this->fd)->emit('test');
}
```

Exception:
```
ReflectionException: Class swoole.websocket does not exist in /home/yuriy/PhpstormProjects/swoole-game/vendor/laravel/framework/src/Illuminate/Container/Container.php:790
Stack trace:
#0 /home/yuriy/PhpstormProjects/swoole-game/vendor/laravel/framework/src/Illuminate/Container/Container.php(790): ReflectionClass->__construct('swoole.websocke...')
#1 /home/yuriy/PhpstormProjects/swoole-game/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\Container\Container->build('swoole.websocke...')
#2 /home/yuriy/PhpstormProjects/swoole-game/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\Container\Container->resolve('swoole.websocke...', Array)
#3 /home/yuriy/PhpstormProjects/swoole-game/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\Container\Container->make('swoole.websocke...', Array)
#4 /home/yuriy/PhpstormProjects/swoole-game/vendor/laravel/framework/src/Illuminate/Container/Container.php(1225): Illuminate\Foundation\Application->make('swoole.websocke...')
#5 /home/yuriy/PhpstormProjects/swoole-game/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(175): Illuminate\Container\Container->offsetGet('swoole.websocke...')
#6 /home/yuriy/PhpstormProjects/swoole-game/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(144): Illuminate\Support\Facades\Facade::resolveFacadeInstance('swoole.webso
```

**Comment by albertcht** [comment]
Hi @mxp100 ,

Because there are no full swoole bindings in task workers. You can try to remove the following code in `Manager.php`:

```
if ($server->taskworker) {
    $this->setProcessName('task process');

    return;
}
```

**Comment by mxp100** [comment]
please, add to debug issue, my resolution:
`        /** @var \Swoole\WebSocket\Server $server */
        $server = app(Server::class);

        /** @var Manager $manager */
        $manager = app(Manager::class);

        $manager->pushMessage($server, [
            'sender'    => $sender,
            'fds'       => [],
            'broadcast' => $broadcast,
            'assigned'  => false,
            'event'     => $event,
            'message'   => $message,
        ]);`

**Comment by mxp100** [comment]
May be create fake facade for task-workers? with normal fluent syntax?

**Comment by albertcht** [comment]
Hi @mxp100, does my solution above work for you?

**Comment by mxp100** [comment]
I check you solution later...

**Comment by mxp100** [comment]
`ErrorException: Swoole\Server::task(): Server->task() cannot use in the task-worker in /home/yuriy/PhpstormProjects/swoole-game/vendor/swooletw/laravel-swoole/src/Websocket/Websocket.php:183
`

**Comment by mxp100** [comment]
PR: https://github.com/swooletw/laravel-swoole/pull/319

**Comment by albertcht** [comment]
Hi @mxp100 , I will check it.

**Comment by albertcht** [comment]
merged in the release `v2.6.64`.

**Comment by junshenshi** [comment]
@mxp100  hi  Have you solved this problem  ：swoole.websocket does not exist

**Comment by mxp100** [comment]
may be you not say yes for support websocket?

**Comment by vodka0629** [comment]
same problem, it is not fixed yet
