### ISSUE TITLE
DB::getQueryLog() method Generate duplicate logs

### ISSUE THREAD

**Issue by jackchow123456** [swooletw/laravel-swoole#310]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

php:7.3.4  swoole:4.3.3

2. Please provide your Laravel/Lumen version.

5.6.39

3. Which release version of this package are you using?

v2.5.0

4. What did you do? If possible, provide a recipe for reproducing the error.

i use the DB::getQueryLog() method

5. What did you expect to see?

Multiple requests, I want to see the query statement that is not repeated.

6. What did you see instead?

When I first requested, I saw a query statement.
When I requested it for the second time, I saw two query statements.
And so on

**Comment by mxp100** [comment]
try add 'log' to swoole config "instances"

**Comment by jackchow123456** [comment]
no work.

**Comment by jackchow123456** [comment]
resolved that , create the self Resetters to handle it.

**Comment by mxp100** [comment]
in debug issue, solved similar problem with auth has the same solution for you with singleton for Log

**Comment by roboticsexpert** [comment]
> resolved that , create the self Resetters to handle it.

would you create merge request for that to any body use it ?
