### ISSUE TITLE
Menu items and dashboard cards are duplicated each page reload

### ISSUE THREAD

**Issue by juberjj** [swooletw/laravel-swoole#312]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

![image](https://user-images.githubusercontent.com/16324958/61646001-f6172400-ac9f-11e9-9422-cec6e305428e.png)

![image](https://user-images.githubusercontent.com/16324958/61645987-ebf52580-ac9f-11e9-8cf4-45b852941aed.png)

2. Please provide your Laravel/Lumen version.

![image](https://user-images.githubusercontent.com/16324958/61646021-08915d80-aca0-11e9-89b3-a1cb8959752d.png)

3. Which release version of this package are you using?

Latest

4. What did you do? If possible, provide a recipe for reproducing the error.

Just hooked swoole to an existing application. All works fine but Nova interactions.

5. What did you expect to see?

Page render accordingly

6. What did you see instead?

![image](https://user-images.githubusercontent.com/16324958/61646138-6d4cb800-aca0-11e9-8ca0-c828da0567df.png)

Many thanks in advance

**Comment by mxp100** [comment]
see https://github.com/laravel/nova-issues/issues/1013

**Comment by juberjj** [comment]
Solution provided on link above did fix my problem.
Hoping Nova Team can merge that code and have that implemented asap.
