### ISSUE TITLE
Menu items not rendering on Voyager

### ISSUE THREAD

**Issue by juberjj** [swooletw/laravel-swoole#313]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

![image](https://user-images.githubusercontent.com/16324958/61865007-62756b80-aeca-11e9-8ce6-28e0c6e28f76.png)

![image](https://user-images.githubusercontent.com/16324958/61865056-7620d200-aeca-11e9-966d-310253ded1ce.png)

2. Please provide your Laravel/Lumen version.
Laravel - 5.8.23

3. Which release version of this package are you using?

Latest

4. What did you do? If possible, provide a recipe for reproducing the error.

Just serving an existing php voyager app .

5. What did you expect to see?

Components should render accordingly
![image](https://user-images.githubusercontent.com/16324958/61872508-6c539a80-aedb-11e9-93cb-e2a8496385dc.png)

6. What did you see instead?

Missing menu elements

![image](https://user-images.githubusercontent.com/16324958/61872552-8a20ff80-aedb-11e9-8bff-5beb9a7c9537.png)

If I do the same with php artisan serve the page renders ok.

**Comment by mxp100** [comment]
see debug issues, may be Voyager using static classes or properties, added voyager render classes to instances(config/swoole_http.php)

**Comment by juberjj** [comment]
@mxp100  Could you please elaborate if possible?
