### ISSUE TITLE
"file_get_contents('php://input')"can't get data

### ISSUE THREAD

**Issue by Nicholas003** [swooletw/laravel-swoole#315]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

php -v：7.2
php --ri swoole：4.3.3
2. Please provide your Laravel/Lumen version.

Laravel：5.8

3. Which release version of this package are you using?

"swooletw/laravel-swoole": "^2.6"

4. What did you do? If possible, provide a recipe for reproducing the error.

"file_get_contents('php://input')" cannot get data after opening the service

5. What did you expect to see?

I want to get data normally.

6. What did you see instead?

I see a blank.

------------------------------------------
I went online to search for this problem, it seems to be caused by swoole, the swoole callback can be obtained through "$request->rawContent()", but now there is no callback

**Comment by pingcheng** [comment]
try using helper `request()->getContent();`
