### ISSUE TITLE
Laravel Socialite - Callback return the expected code but page won't render as it does using php artisan serve

### ISSUE THREAD

**Issue by juberjj** [swooletw/laravel-swoole#317]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
PHP 7.3.7
Swoole 4.4.2

2. Please provide your Laravel/Lumen version.
Laravel 5.8.23

3. Which release version of this package are you using?

Latest

4. What did you do? If possible, provide a recipe for reproducing the error.
Trying to connect to a cloud provider through APIs

![image](https://user-images.githubusercontent.com/16324958/62366861-f0cb9c00-b51f-11e9-92a4-123006b2c48f.png)

5. What did you expect to see?

Page should render the folder structure once user is logged in

6. What did you see instead?
Although I get a 200 back no content is returned
![image](https://user-images.githubusercontent.com/16324958/62366979-4607ad80-b520-11e9-9b05-07d9cbef76d2.png)

Serving the app with php artisan serve it works accordingly

Any help is very much appreciated

**Comment by mxp100** [comment]
see debug issue authorization

**Comment by albertcht** [comment]
Can you provided more detailed info and your debug steps?
