### ISSUE TITLE
StreamedResponse returns 0 bytes if SWOOLE_OB_OUTPUT is set to false.

### ISSUE THREAD

**Issue by sikhlana** [swooletw/laravel-swoole#318]
1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

`PHP 7.3.7-2+ubuntu18.04.1+deb.sury.org+1` and `swoole-4.4.0`

2. Please provide your Laravel/Lumen version.

`Laravel 5.8.30`

3. Which release version of this package are you using?

`2.6.63`

4. What did you do? If possible, provide a recipe for reproducing the error.

These is the related environment variable:

`SWOOLE_OB_OUTPUT=false`

I tried downloading a file from my S3 bucket using the `Storage::download()` facade, which returns a StreamedResponse object.

5. What did you expect to see?

The response body should have been 4.2MB in size.

6. What did you see instead?

The response body was of zero bytes.

---

If I set `SWOOLE_OB_OUTPUT` to `true` the download is working as expected.

**Comment by albertcht** [comment]
@sikhlana ,

I think it uses `ob` series functions for its download function. Then it makes sense you need to set `SWOOLE_OB_OUTPUT` to `true`.

**Comment by sikhlana** [comment]
Isn't it possible to directly pass the stream as the HTTP response instead of using `OB`?

**Comment by albertcht** [comment]
This is how traditional PHP implements output buffering.

**Comment by sikhlana** [comment]
That I know. I also understand that `StreamedResponse` implementations use `echo` and such to output data. So maybe ignore the environment variable when there is a `StreamedResponse` instance and directly use output buffering? Because normally I don't want to use output buffering if I can't help it.

**Comment by albertcht** [comment]
Then you have to rewrite the behavior of `StreamedResponse` on your own. I think setting `SWOOLE_OB_OUTPUT` to `true` will be much easier.
