### ISSUE TITLE
websocket can not  get auth user in laravel5.8

### ISSUE THREAD

**Issue by fengxin2017** [swooletw/laravel-swoole#320]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
```7.2.21-1+ubuntu18.04.1+deb.sury.org+1``` and  ```swoole-4.4.3```

2. Please provide your Laravel/Lumen version.
```laravel5.8.31```

3. Which release version of this package are you using?
```2.6```

4. What did you do? If possible, provide a recipe for reproducing the error.
```
Websocket::on('connect', function ($websocket, Request $request) {
    $user = auth()->user();  
    dump($user);
});
```

5. What did you expect to see?
```
Websocket::on('connect', function ($websocket, Request $request) {
    $user = auth()->user();  // get the  authorized user 
});
```

6. What did you see instead?
```
Websocket::on('connect', function ($websocket, Request $request) {
    $user = auth()->user(); 
   //here, always return null 
    dump($user); 
});
```
### there is not option named session on laravel5.8. so add a option named session whatever just not null will fix it. did i missed somthing in doc? 

```
SwooleTW\Http\Websocket\Middleware\StartSession

public function handle($request, Closure $next)
 {
    if ($this->sessionConfigured()) {
        $request->setLaravelSession($this->startSession($request));
    }

    return $next($request);
 }

// problem here
protected function sessionConfigured()
{
    return Arr::get($this->manager->getSessionConfig(), 'session') !== null;
}

```

**Comment by albertcht** [comment]
Hi @fengxin2017 ,

The middleware provided in this package is just for demonstration, but may not be compatible for all versions of Laravel.

You can implement your own middleware based on your real case.

**Comment by fengxin2017** [comment]
@albertcht got it thanks a lot.
