### ISSUE TITLE
Request for socket json support

### ISSUE THREAD

**Issue by amirhs712** [swooletw/laravel-swoole#321]
I know from the wiki that only `text` type data is supported.
I can receive JSON data from clients, but the server can't send JSON string.

Also, the namespace feature of `Socket.io` is crucial for systems which use API versioning.

It would be nice to have these features supported.

**Comment by mxp100** [comment]
by default SocketIOParser (see config swoole_websocket.php) work with json

**Comment by amirhs712** [comment]
@mxp100 I tested it many times, no luck.
Here's my code:

`websocket.php`

`Websocket::on('message', function ($websocket, $data){
    $websocket->emit('message', ['from' => 'server']);
});
`

View:

```
var socket = io.connect('ws://app', {
        transports: ['websocket'],
        reconnection: true,
        query: {
            'token': 'XXXX'
        }
});
```

    socket.on('message', function (data) {
        console.log('New Message: ' + data);
    });

    socket.emit('message', 'Hello world');

Now, when the server tries to send a JSON message, nothing is triggered on the client-side (which indicates that the `message` event was not sent in the first place).
BUT if I replace `$websocket->emit('message', ['from' => 'server']);` with
`$websocket->emit('message', 'Received');` the event is triggered.

I can see that `SocketIOParser` encodes arrays or objects for WebSocket push (That's why I'm not using json_encode on the websocket->emit function to encode the array), but I can't understand why I'm not getting any response.

By the way, I can receive JSON string from clients, but can't send them.

**Comment by mxp100** [comment]
You see http status 101 in network debug?
may be you problem in connect url string?
and in console.log return: "New message: [object Object]"

**Comment by amirhs712** [comment]
> You see http status 101 in network debug?
> may be you problem in connect url string?
> and in console.log return: "New message: [object Object]"

I have many events running on this server, there is no 101, the socket is connected & Authenticated, and no there is no console log. (I have a BreakPoint on the line)
