### ISSUE TITLE
Having Performance Issues:  Nginx > Swoole Req/s

### ISSUE THREAD

**Issue by nickpoulos** [swooletw/laravel-swoole#325]
I am not seeing the expected performance from my Swoole server vs Nginx. Details below. 

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

**PHP**
PHP 7.3.6-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May 31 2019 11:06:48) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.6-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

**Swoole**
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.3
Built => Aug 16 2019 19:37:39
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1c  28 May 2019
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

2. Please provide your Laravel/Lumen version.

"laravel/framework": "5.8.*",
       
3. Which release version of this package are you using?

 "swooletw/laravel-swoole": "^2.6"

4. What did you do? If possible, provide a recipe for reproducing the error.

**Setup:** 
- Laravel Homestead with port 1215 fwd'd
- Clean Laravel 5.8 install with this package installed. 
- Setup a few test routes
- run php artisan swoole:http start

At this point I can see my server running correctly, and can access the swoole version in my host machine browser as expected. 

5. What did you expect to see?
 
After running wrk load-testing on Nginx vs Swoole I expected Swoole to handily beat Nginx

6. What did you see instead?

However I was seeing results opposite of what I expected, see below: 

**Nginx** 

```
wrk -t12 -c400 -d30s http://laravel-swoole.local/api/big-json
Running 30s test @ http://laravel-swoole.local/api/big-json
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   113.21ms  215.39ms   2.00s    94.38%
    Req/Sec   286.55    125.71     1.19k    71.16%
  101615 requests in 30.10s, 57.53MB read
  Socket errors: connect 0, read 0, write 0, timeout 784
  Non-2xx or 3xx responses: 101543
Requests/sec:   3375.80
Transfer/sec:      1.91MB
```
**Swoole**
```
wrk -t12 -c400 -d30s http://laravel-swoole.local:1215/api/big-json
Running 30s test @ http://laravel-swoole.local:1215/api/big-json
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.29s   236.93ms   2.00s    79.32%
    Req/Sec    38.37     29.43   220.00     72.22%
  8956 requests in 30.10s, 58.29MB read
  Socket errors: connect 0, read 0, write 0, timeout 123
  Non-2xx or 3xx responses: 8833
Requests/sec:    297.51
Transfer/sec:      1.94MB
```

**Comment by hypernics** [comment]
Non-2xx or 3xx responses: 101543 vs Non-2xx or 3xx responses: 8833

**Comment by nickpoulos** [comment]
Ah I see thanks for the response, I did not notice that.  All I saw in the swole_http.log were a bunch of 1004 errors:
```
[2019-08-19 23:55:37 *31174.1]  NOTICE  swFactoryProcess_finish (ERRNO 1004): send 3222 byte failed, because connection[fd=54] is closed
```
which means the client cancelled the request according to [what I have read](https://github.com/swoole/swoole-src/issues/2407).  

So I assumed the test was too much to handle, toned them down a bit, and got:

```
⇢wrk -t4 -c100 http://laravel-swoole.local:1215
Running 10s test @ http://laravel-swoole.local:1215
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   457.20ms  136.33ms 779.94ms   78.10%
    Req/Sec    40.67     34.08   181.00     77.51%
  835 requests in 10.09s, 2.57MB read
  Socket errors: connect 0, read 0, write 0, timeout 100
Requests/sec:     82.72
Transfer/sec:    260.41KB


⇢ wrk -t4 -c100 http://laravel-swoole.local
Running 10s test @ http://laravel-swoole.local
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.45s   341.83ms   1.97s    77.94%
    Req/Sec    19.38     13.45    70.00     77.34%
  625 requests in 10.04s, 1.95MB read
  Socket errors: connect 0, read 0, write 0, timeout 4
Requests/sec:     62.23
Transfer/sec:    198.35KB
```

Does this seem about right?

**Comment by albertcht** [comment]
Hi @nickpoulos ,

Yes, it is.

**Comment by aftabnaveed** [comment]
I am getting a similar problem here

```
[2019-11-11 01:07:25 *21704.1]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 954 byte failed, because connection[fd=56] is closed
[2019-11-11 01:07:25 *21704.1]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 1176 byte failed, because connection[fd=60] is closed
[2019-11-11 01:07:25 *21704.1]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 1175 byte failed, because connection[fd=64] is closed
[2019-11-11 01:07:34 *21704.1]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 983 byte failed, because connection[fd=65] is closed
[2019-11-11 01:07:34 *21704.1]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 1757 byte failed, because connection[fd=66] is closed
[2019-11-11 01:07:47 *21704.1]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 944 byte failed, because connection[fd=67] is closed
[2019-11-11 01:07:47 *21704.1]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 1180 byte failed, because connection[fd=70] is closed
[2019-11-11 01:08:04 *21706.3]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 985 byte failed, because connection[fd=83] is closed
[2019-11-11 01:08:04 *21706.3]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 948 byte failed, because connection[fd=84] is closed
[2019-11-11 01:08:04 *21706.3]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 1453 byte failed, because connection[fd=85] is closed
```

Under what circumstances will the client cancel a request?

**Comment by aftabnaveed** [comment]
This issue happens when I have an increased load on the server. It gradually starts slowing down and eventually get those notices and then killing the website altogether. This seems to be an issue/misconfiguration with the Swoole.

**Comment by erdemkose** [comment]
When I try to benchmark the Swoole vs PHP-FPM, I always turn off Laravel debugging. You can raise the log level to `error`. 

Also make sure you use production configuration for a fair comparison. 

- Disable nginx's access log
- Enable opcache
- Set `opcache.validate_timestamps=0`
- Run `php artisan optimize`

**Comment by erdemkose** [comment]
Are you sure you are testing nginx vs Swoole? Make sure that the ports you are testing are used by both of them and not only by one of them. Try changing Swoole's HTTP port and try again.

**Comment by nickpoulos** [comment]
Thanks for the replies @albertcht and @erdemkose.

I was hoping the performance gains would be more than > 20 req/s using Swoole, but I suppose it could have to do with: 

- maybe environment not resourceful enough? It is using the default Laravel Homestead Vagrant box, although both Nginx and Swoole are using the same resources so it should be apples to apples that way still. 

- as @erdemkose mentioned, maybe I have to turn off or tone down the debug settings/development environment settings. Making some of the changes he suggested. 

I would hope its not a Swoole port problem, things are responding as they should, so I thought I had things setup properly in that regard. 

Any other thought's greatly appreciated. What kind of performance gains should I be seeing from Swoole on a basic http test here?

**Comment by erdemkose** [comment]
> I am getting a similar problem here
> 
> ```
> [2019-11-11 01:07:25 *21704.1]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 954 byte failed, because connection[fd=56] is closed
> [2019-11-11 01:07:25 *21704.1]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 1176 byte failed, because connection[fd=60] is closed
> [2019-11-11 01:07:25 *21704.1]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 1175 byte failed, because connection[fd=64] is closed
> [2019-11-11 01:07:34 *21704.1]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 983 byte failed, because connection[fd=65] is closed
> [2019-11-11 01:07:34 *21704.1]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 1757 byte failed, because connection[fd=66] is closed
> [2019-11-11 01:07:47 *21704.1]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 944 byte failed, because connection[fd=67] is closed
> [2019-11-11 01:07:47 *21704.1]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 1180 byte failed, because connection[fd=70] is closed
> [2019-11-11 01:08:04 *21706.3]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 985 byte failed, because connection[fd=83] is closed
> [2019-11-11 01:08:04 *21706.3]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 948 byte failed, because connection[fd=84] is closed
> [2019-11-11 01:08:04 *21706.3]	NOTICE	swFactoryProcess_finish (ERRNO 1004): send 1453 byte failed, because connection[fd=85] is closed
> ```
> 
> Under what circumstances will the client cancel a request?

This is how `wrk` works. When the benchmark time limit is reached, it closes the open connections. And since you used `-c100`, there are lots of open connections at one moment.

I usually benchmark with `wrk -t4 -c10 -d60`.

**Comment by erdemkose** [comment]
> Any other thought's greatly appreciated. What kind of performance gains should I be seeing from Swoole on a basic http test here?

The performance gain depends on the project. My project is a microservice that each endpoint runs only 1 or 2 database queries. If you have more IO operations for a single request, then you will be limited by the IO.

According to the benchmarks that I run on my local computer:
`nginx+phpfpm: 206 Requests/second`
`nginx+Swoole: 1070 Requests/second`

These numbers will change on production servers because they are deeply optimized. So I expect a performance gain around 200%-300%.

**Comment by nickpoulos** [comment]
Yes of course, generally speaking db/io are almost always going to be the bottleneck in a real world system.  These were Hello World responses so was expecting more. So I will have to check some things out, because a 200-300% boost is more like it!
