### ISSUE TITLE
Hot Reload not working

### ISSUE THREAD

**Issue by dyanakiev** [swooletw/laravel-swoole#328]
1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
```
PHP 7.3.8-1+0~20190807.43+debian10~1.gbp7731bf (cli) (built: Aug  7 2019 19:47:21) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.8-1+0~20190807.43+debian10~1.gbp7731bf, Copyright (c) 1999-2018, by Zend Technologies
```

```
                                                                    
swoole                                                              
                                                                    
Swoole => enabled                                                   
Author => Swoole Team <team@swoole.com>                             
Version => 4.4.5                                                    
Built => Aug 30 2019 19:37:35                                       
coroutine => enabled                                                
epoll => enabled                                                    
eventfd => enabled                                                  
signalfd => enabled                                                 
cpu_affinity => enabled                                             
spinlock => enabled                                                 
rwlock => enabled                                                   
sockets => enabled                                                  
openssl => OpenSSL 1.1.1c  28 May 2019                              
http2 => enabled                                                    
pcre => enabled                                                     
mutex_timedlock => enabled                                          
pthread_barrier => enabled                                          
futex => enabled                                                    
mysqlnd => enabled                                                  
async_redis => enabled                                              
                                                                    
Directive => Local Value => Master Value                            
swoole.enable_coroutine => On => On                                 
swoole.enable_library => On => On                                   
swoole.enable_preemptive_scheduler => Off => Off                    
swoole.display_errors => On => On                                   
swoole.use_shortname => On => On                                    
swoole.unixsock_buffer_size => 8388608 => 8388608 
```

2. Please provide your Laravel/Lumen version.
Lumen latest, swoole latest, larave-swoole latest..

3. Which release version of this package are you using?
latest

4. What did you do? If possible, provide a recipe for reproducing the error.
create project lumen, require swoole, start swoole

--
So hot reload is not working for somereason i set it to true from the config, im using windows wsl with debian and php 7.3

**Comment by dyanakiev** [comment]
Also having hot reload enabled causes consistent 10% cpu usage from the task process

**Comment by dyanakiev** [comment]
Thats weird.. changing twig files is instantly, but modifying controller is not detected.

**Comment by dyanakiev** [comment]
I found something else, im really confused..
I set session variable every user keeps its own for his own session its storred correctly.
The weird part is that on every reload the csrf token and session key is changing, but still it provides the right data for the user.

**Comment by neovdr** [comment]
Exact same issue myself. Tested both on Windows with WSL and Mac OS

**Comment by albertcht** [comment]
I can't reproduce this issue on my Mac OS. This hot reload feature is based on `fswatch`, so make sure you've installed `fswatch`.

> I don't know if `fswatch` supports WSL and I don't have a windows environment.

**Comment by albertcht** [comment]
`fswatch` seems doesn't work in WSL. See https://github.com/emcrisostomo/fswatch/issues/132

**Comment by regy42** [comment]
I partially solved it by adding a file watch to restart the container for me, will see it i's usable for development https://www.jetbrains.com/help/phpstorm/using-file-watchers.html#ws_file_watchers_bedore_you_start
