### ISSUE TITLE
SSL Issue

### ISSUE THREAD

**Issue by opcodespace** [swooletw/laravel-swoole#329]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

`PHP 7.2.19-0ubuntu0.18.04.2 (cli) (built: Aug 12 2019 19:34:28) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies`

----
```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.5
Built => Sep  1 2019 06:31:20
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1  11 Sep 2018
http2 => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

2. Please provide your Laravel/Lumen version.
`Lumen - 5.8`

3. Which release version of this package are you using?
Latest version

4. What did you do? If possible, provide a recipe for reproducing the error.

Without ssl, everything working well. Thanks to you. 
I am getting error after adding ssl (self signed).
https://cm.linkingphase.com:1215

5. What did you expect to see?
With ssl want to run without error in browser. 

6. What did you see instead?
In firefox I am getting following error
`An error occurred during a connection to cm.linkingphase.com:1215. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG`

Thanks again.

**Comment by pingcheng** [comment]
add a nginx in the front and config ssl in nginx
hide laravel behind the nginx

**Comment by opcodespace** [comment]
> add a nginx in the front and config ssl in nginx
> hide laravel behind the nginx

Thanks for your response. I have added following code. It seems to me it is working. 

```location /swoole {
        rewrite ^/swoole(.*) /$1 break;
        proxy_pass http://127.0.0.1:1215;
    }```

![2019-09-06_1-49-06](https://user-images.githubusercontent.com/23176703/64375954-eb92cd00-d048-11e9-8515-8851b3eb2586.png)
