### ISSUE TITLE
Uncaught Error: Call to undefined method Symfony\Component\HttpFoundation\Cookie::isRaw()

### ISSUE THREAD

**Issue by mouhsinelonly** [swooletw/laravel-swoole#33]
other issue in laravel 5.2

`[Symfony\Component\Debug\Exception\FatalErrorException]
  Uncaught Error: Call to undefined method Symfony\Component\HttpFoundation\Cookie::isRaw() in /var/www/html/dares/vendor/swooletw/laravel-swoole/src/Server/Response.php:89
  Stack trace:
  #0 /var/www/html/dares/vendor/swooletw/laravel-swoole/src/Server/Response.php(54): SwooleTW\Http\Server\Response->sendHeaders()
  #1 /var/www/html/dares/vendor/swooletw/laravel-swoole/src/Server/Manager.php(269): SwooleTW\Http\Server\Response->send()
  #2 {main}
    thrown`

**Comment by albertcht** [comment]
Hi @mouhsinelonly ,

Yes, I'm working on it.

**Comment by albertcht** [comment]
Hi @mouhsinelonly ,

This has been fixed in the release `v2.3.3`, and I test it with Laravel 5.2 this time. It should work now.
