### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by dickwu** [swooletw/laravel-swoole#330]

**Comment by sauriio** [comment]
any news on this??

**Comment by albertcht** [comment]
I will try to simply add 6.0 to composer.json on develop branch. Laravel 6.0 is a big version, and I can't guarantee if everything on Laravel 6.0 works.

**Comment by albertcht** [comment]
You can try to install from develop branch to see if it works on Laravel 6:

```
composer require swooletw/laravel-swoole:dev-master
```

**Comment by sauriio** [comment]
Everything seems to be working on Lumen 6!

**Comment by vpillinger** [comment]
Found a minor issue in Lumen 6: #348

**Comment by Arkanius** [comment]
Already supports
