### ISSUE TITLE
the response time is eight hours short in swoole_http.log when timezone is Asia/Shanghai

### ISSUE THREAD

**Issue by hugtale** [swooletw/laravel-swoole#331]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

```
PHP 7.3.9 (cli) (built: Sep  3 2019 06:49:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
```

```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.4
Built => Sep  6 2019 22:00:36
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1c  28 May 2019
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

2. Please provide your Laravel/Lumen version.

```
Laravel Framework 5.8.35
```

3. Which release version of this package are you using?

```
v2.6.64
```

4. What did you do? If possible, provide a recipe for reproducing the error.

set config `access_log` to `true`.

5. What did you expect to see?

my current timezone is `Asia/Shanghai`,but the Datetime Object is null when it is formated to `Y-m-d H:i:s`.

6. What did you see instead?

the response time is eight hours short in swoole_http.log when timezone is Asia/Shanghai.

the Method about the DateTime Object is ` SwooleTW\Http\Server\AccessOutput->log()`

**Comment by pingcheng** [comment]
ssh into your server, use this command see what your server's time is
```bash
date
```

**Comment by hugtale** [comment]
my mac time  is `2019年 9月 9日 星期一 08时59分26秒 CST`,the system of my docker container is `Mon Sep  9 09:01:46 CST 2019`,the `data.timezone` in `php.ini` file is `Asia/Shanghai`,the config `timezone` in Laravel frmework is `Asia/Shanghai`,the function `date_default_timezone_get ` returns `Asia/Shanghai`,I'm sure I have found this bug and something is wrong in `SwooleTW\Http\Server\AccessOutput`.

my chienglish is poor,hahahahaahahahahahahaha~

**Comment by albertcht** [comment]
Hi @hezachary ,

The messages in `swoole_http.log` come from swoole's kernel directly. The only thing this package did is setting the log path.

I can't reproduce this issue on my environment and I'm not sure the timezone swoole refers to either.

**Comment by albertcht** [comment]
`SwooleTW\Http\Server\AccessOutput` is related to debug output to your console. It's not related to any messages in `swoole_http.log`.
