### ISSUE TITLE
Can UDP be supported?

### ISSUE THREAD

**Issue by shijunti19** [swooletw/laravel-swoole#332]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

2. Please provide your Laravel/Lumen version.

3. Which release version of this package are you using?

4. What did you do? If possible, provide a recipe for reproducing the error.

Can UDP be supported?

5. What did you expect to see?

6. What did you see instead?

**Comment by albertcht** [comment]
Hi @shijunti19 ,

HTTP is based on TCP. Not sure what you mean?

**Comment by shijunti19** [comment]
@albertcht https://wiki.swoole.com/wiki/page/477.html

https://github.com/hhxsv5/laravel-s

![image](https://user-images.githubusercontent.com/5392211/64929454-fd4e4e80-d858-11e9-9880-cf27416b54dd.png)

There are several other modes of swoole

**Comment by albertcht** [comment]
This package focuses on running laravel application on Swoole, not integrating evrey Swoole's feature into this package. So there's no plan for supporting UDP server in this package yet.
