### ISSUE TITLE
How to Close Task Scheduling

### ISSUE THREAD

**Issue by shijunti19** [swooletw/laravel-swoole#333]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
7.3

2. Please provide your Laravel/Lumen version.

Laravel

3. Which release version of this package are you using?

new

4. What did you do? If possible, provide a recipe for reproducing the error.

How to Close Task Scheduling
I just want to use planned tasks to perform, not swoole.

![image](https://user-images.githubusercontent.com/5392211/64918709-af900280-d7d4-11e9-93bf-e6cd54974977.png)
If it does not close, it will repeat execution.

5. What did you expect to see?

6. What did you see instead?

**Comment by albertcht** [comment]
Hi @shijunti19 ,

Can you provide more details about your question since you question is too ambiguous.

If you don't want to use `swoole` as your queue driver, and just replace to another driver  in your config.
