### ISSUE TITLE
can not install on laravel6

### ISSUE THREAD

**Issue by xiaopenggithub** [swooletw/laravel-swoole#337]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

2. Please provide your Laravel/Lumen version.

3. Which release version of this package are you using?

4. What did you do? If possible, provide a recipe for reproducing the error.

5. What did you expect to see?

6. What did you see instead?

**Comment by agclqq** [comment]
I had a similar problem.

**php -v**
PHP 7.2.20 (cli) (built: Sep  5 2019 11:28:21) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.20, Copyright (c) 1999-2018, by Zend Technologies

**php --ri swoole**

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.7
Built => Sep 27 2019 11:20:17
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

**Install laravel and all is well**
`composer create-project --prefer-dist laravel/laravel . `

**Laravel version:** `laravel/laravel (v6.0.2)`

**There are some problems with installing laravel-swoole**
`composer require swooletw/laravel-swoole`

**The specific questions are as follows**
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v6.0.4
    - Conclusion: don't install laravel/framework v6.0.4
    - ...
    - don't install illuminate/http v5.8.35|don't install laravel/framework v6.0.4
    - don't install illuminate/http v5.8.4|don't install laravel/framework v6.0.4
    - don't install illuminate/http v5.8.8|don't install laravel/framework v6.0.4
    - don't install illuminate/http v5.8.9|don't install laravel/framework v6.0.4
    - Installation request for laravel/framework (locked at v6.0.4, required as ^6.0) -> satisfiable by laravel/framework[v6.0.4].
    - Installation request for swooletw/laravel-swoole ^2.6 -> satisfiable by swooletw/laravel-swoole[v2.6.0, v2.6.1, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.5.1, v2.6.5.2, v2.6.5.3, v2.6.5.4, v2.6.6, v2.6.61, v2.6.62, v2.6.63, v2.6.64].


Installation failed, reverting ./composer.json to its original content.
```

Swoole does not yet seem to support laravel6.0!!!

**Comment by albertcht** [comment]
I will try to simply add 6.0 to `composer.json` on develop branch. Laravel 6.0 is a big version, and I can't guarantee if everything on Laravel 6.0 works.

**Comment by albertcht** [comment]
You can try to install from develop branch to see if it works on Laravel 6:

```
composer require swooletw/laravel-swoole:dev-develop
```

**Comment by albertcht** [comment]
Follow #330 .
