### ISSUE TITLE
 There is a problem. I don't know if it is configured. 

### ISSUE THREAD

**Issue by missbefore** [swooletw/laravel-swoole#342]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
php 7.2
swoole 4.4.7
2. Please provide your Laravel/Lumen version.
5.8

3. Which release version of this package are you using?
2.6

4. What did you do? If possible, provide a recipe for reproducing the error.
use dingo and laravel-passport

The result of each request is the same. Even if the transfer parameter is changed, the server receives the previous parameter

And it is often the case that the parameter is empty, but the web end does pass the parameter

5. What did you expect to see?

 Is it my configuration problem ? Or incompatible with which packages ？

6. What did you see instead?

**Comment by albertcht** [comment]
Hi @missbefore ,

You can find related topics in closed issues. Dingo uses its own router, thus it's not compatible with this package.

**Comment by missbefore** [comment]
ok，thanks
