### ISSUE TITLE
Timeline for new release?

### ISSUE THREAD

**Issue by neovdr** [swooletw/laravel-swoole#344]
Any news on when a new release will be tagged for this package? Can't move to laravel 6 without the fixes that are currently unreleased.

Would really prefer not to have to fork this repo just to bring in some extra changes.

**Comment by albertcht** [comment]
Hi @neovdr ,

I've tagged `v2.6.65` to the latest master commit.

**Comment by neovdr** [comment]
Much appreciated!!
