### ISSUE TITLE
CORS not working on laravel swoole

### ISSUE THREAD

**Issue by kinglexy** [swooletw/laravel-swoole#346]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

PHP 7.3.8 (cli) and 
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.4-alpha
Built => Aug 14 2019 17:47:03
coroutine => enabled
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2s  28 May 2019
http2 => enabled
pcre => enabled
zlib => enabled
brotli => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144

2. Please provide your Laravel/Lumen version.

"laravel/lumen-framework": "5.8.*",

3. Which release version of this package are you using?

 4.4.4-alpha

4. What did you do? If possible, provide a recipe for reproducing the error.

It doesn't respond to calls from a vue app

5. What did you expect to see?
Expected to return the main post response

6. What did you see instead?
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9501/....... (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)

**Comment by kinglexy** [comment]
I tried it on normal php apache, it works fine, but on swoole, it doesn't

**Comment by kinglexy** [comment]
What other info is required please.

**Comment by kinglexy** [comment]
I am using laravel swoole, and my routes/web.php looks like this
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It is a breeze. Simply tell Lumen the URIs it should respond to
| and give it the Closure to call when that URI is requested.
|
*/

use App\Mail\WelcomeMail;
use Illuminate\Support\Facades\Mail;

header('Access-Control-Allow-Origin:  *');
header('Access-Control-Max-Age:  86400');
header('Access-Control-Allow-Methods:  POST, GET, OPTIONS, PUT, PATCH, DELETE');
header('Access-Control-Allow-Credentials: true');
header('Access-Control-Allow-Headers: Content-Type, X-Requested-With, Accept, X-Auth-Token, Origin, Authorization');

$router->get('/', function () use ($router) {...

**Comment by vpillinger** [comment]
This does not work because the router file is not the place to set return headers. Add an echo statement to this file and you will notice that it is never output. That is because this file is run only 1 time: at startup.

**Comment by kinglexy** [comment]
Alright, which library works best for CORS on lumen, because I have tried barryvdh/laravel-cors and spatie/laravel-cors but both doesn't work

**Comment by vpillinger** [comment]
Just set the headers in a Middleware or in your controller method instead of your route file, and configure your nginx proxy to pass those headers forward if need be.

**Comment by kinglexy** [comment]
It works now, thank you so much...
