### ISSUE TITLE
Cannot modify header information - headers already sent by

### ISSUE THREAD

**Issue by ritaswc** [swooletw/laravel-swoole#347]
1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
```
PHP 7.1.30 (cli) (built: Jul 13 2019 15:25:55) ( NTS )
CentOS Linux release 7.6.1810 (Core)

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.8
Built => Oct 21 2019 19:53:52
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```
2. Please provide your Laravel/Lumen version.
```
Laravel Framework 5.8.35
phpoffice/phpspreadsheet  v1.9.0
```

3. Which release version of this package are you using?
```
v2.6.65
```

4. What did you do? If possible, provide a recipe for reproducing the error.

![TIM截图20191023114853.png](https://i.loli.net/2019/10/23/h35fsmtQv1caWKV.png)
### **laravel with php-fpm is ok**

5. What did you expect to see?

download a xlsx file
![TIM截图20191023114929.png](https://i.loli.net/2019/10/23/dwpxe2gcnl9D73X.png)

6. What did you see instead?

Cannot modify header information - headers already sent by
![1_看图王.png](https://i.loli.net/2019/10/23/jgCv3KbmdYsXIzc.png)

**Comment by ritaswc** [comment]
Any body here??

**Comment by albertcht** [comment]
Do you read [Z1.-Notices](https://github.com/swooletw/laravel-swoole/wiki/Z1.-Notices) before opening this issue?
