### ISSUE TITLE
Route Group Do Not Work on Lumen 6

### ISSUE THREAD

**Issue by vpillinger** [swooletw/laravel-swoole#348]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
php - 7.2.24
swoole - 4.4.8

2. Please provide your Laravel/Lumen version.
6.2.0

3. Which release version of this package are you using?
2.6.65

4. What did you do? If possible, provide a recipe for reproducing the error.
Create a route group in a routing file

5. What did you expect to see?
The group prefix to be added to the route.
Middleware should be applied to the route.

6. What did you see instead?
The route is registered, but without the group prefix.
Additionally, route group middle does not work either.

**Comment by albertcht** [comment]
Hi @vodniciarv ,

Can you provide your routes file? I can't reproduce this issue with the following route:

```php
$router->group(['prefix' => 'admin'], function () use ($router) {
    $router->get('/', function () {
        return ['foo' => 'bar'];
    });
});
```
