### ISSUE TITLE
can i use extra parameter for  daemon?

### ISSUE THREAD

**Issue by xiaopenggithub** [swooletw/laravel-swoole#350]
when running the command `php artisan swoole:http start`,the terminal is blocked。

can i use extra parameter for  daemon?

**Comment by damonto** [comment]
https://github.com/swooletw/laravel-swoole/blob/c79eb3f63e128be11b418b7ff811f3a5351c38ed/config/swoole_http.php#L26

Set `SWOOLE_HTTP_DAEMONIZE=true`
