### ISSUE TITLE
push message in the command and jobs will be warnning:swoole.websocket does not exist

### ISSUE THREAD

**Issue by xianbaihong** [swooletw/laravel-swoole#355]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
php-7.2.15
swoole-4.4.12

2. Please provide your Laravel/Lumen version.
laravel 5.8

3. Which release version of this package are you using?
2.6.65

4. What did you do? If possible, provide a recipe for reproducing the error.
Websocket::broadcast()->emit('message', json_encode($data));

5. What did you expect to see?
![image](https://user-images.githubusercontent.com/41822023/69698781-3a6c7200-1121-11ea-946c-8daa4f07bb36.png)

6. What did you see instead?

**Comment by albertcht** [comment]
How do you run your server and where do you trigger the broadcast function?
