### ISSUE TITLE
DB listen issue

### ISSUE THREAD

**Issue by derrck** [swooletw/laravel-swoole#358]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
PHP:7.2.6
Swoole:4.2.1

2. Please provide your Laravel/Lumen version.
Lumen:5.7.8

3. Which release version of this package are you using?
Laravel-swoole: v2.5.0

4. What did you do? If possible, provide a recipe for reproducing the error.
Add a SQL listen in AppServiceProvider.php
app/Providers/AppServiceProvider.php
public function boot()
{
    DB::listen(function ($query) {
        Log::channel('sqllog')->info(
            $query->sql,
            $query->bindings,
            $query->time
        );
    });
}

5. What did you expect to see?
single SQL

6. What did you see instead?
Start swoole server and test my api then check the sql log file.
first time call api, I seen one sql
second time call api, I senn two new sql (two same sql)
third time call api, I senn 3 new sql (3 same sql)
look like it did not clear before listen? If I restart swoole server, it will begin at 1->2->3
Should I set some "instances" in swoole_http config file?

part of sql log file:
-----
[2019-12-04 11:07:58] dev.INFO: select `sign` from `xxx` where (`type` = ? and `d_id` = ?) limit 1 ["BASE_URL","1998"]
[2019-12-04 11:08:09] dev.INFO: select `sign` from `xxx` where (`type` = ? and `d_id` = ?) limit 1 ["BASE_URL","1998"]
[2019-12-04 11:08:09] dev.INFO: select `sign` from `xxx` where (`type` = ? and `d_id` = ?) limit 1 ["BASE_URL","1998"]
[2019-12-04 11:08:18] dev.INFO: select `sign` from `xxx` where (`type` = ? and `d_id` = ?) limit 1 ["BASE_URL","1998"]
[2019-12-04 11:08:18] dev.INFO: select `sign` from `xxx` where (`type` = ? and `d_id` = ?) limit 1 ["BASE_URL","1998"]
[2019-12-04 11:08:18] dev.INFO: select `sign` from `xxx` where (`type` = ? and `d_id` = ?) limit 1 ["BASE_URL","1998"]

**Comment by codercms** [comment]
@derrck it seems like your AppServiceProvider is registered on each request. Can you show your swoole_http config?
Can't reproduce this issue with default swoole_http config.

**Comment by derrck** [comment]
@codercms Thanks
`<?php

return [
    /*
    |--------------------------------------------------------------------------
    | HTTP server configurations.
    |--------------------------------------------------------------------------
    |
    | @see https://www.swoole.co.uk/docs/modules/swoole-server/configuration
    |
    */
    'server' => [
        'host' => env('SWOOLE_HTTP_HOST', '127.0.0.1'),
        'port' => env('SWOOLE_HTTP_PORT', '1215'),
        'public_path' => base_path('public'),
        // Determine if to use swoole to respond request for static files
        'handle_static_files' => env('SWOOLE_HANDLE_STATIC', true),
        'options' => [
            'pid_file' => env('SWOOLE_HTTP_PID_FILE', base_path('storage/logs/swoole_http.pid')),
            'log_file' => env('SWOOLE_HTTP_LOG_FILE', base_path('storage/logs/swoole_http.log')),
            'daemonize' => env('SWOOLE_HTTP_DAEMONIZE', false),
            // Normally this value should be 1~4 times larger according to your cpu cores.
            'reactor_num' => env('SWOOLE_HTTP_REACTOR_NUM', swoole_cpu_num()),
            'worker_num' => env('SWOOLE_HTTP_WORKER_NUM', swoole_cpu_num()),
            'task_worker_num' => env('SWOOLE_HTTP_TASK_WORKER_NUM', swoole_cpu_num()),
            // The data to receive can't be larger than buffer_output_size.
            'package_max_length' => 20 * 1024 * 1024,
            // The data to send can't be larger than buffer_output_size.
            'buffer_output_size' => 10 * 1024 * 1024,
            // Max buffer size for socket connections
            'socket_buffer_size' => 128 * 1024 * 1024,
            // Worker will restart after processing this number of request
            'max_request' => 3000,
            // Enable coroutine send
            'send_yield' => true,
            // You must add --enable-openssl while compiling Swoole
            'ssl_cert_file' => null,
            'ssl_key_file' => null,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Enable to turn on websocket server.
    |--------------------------------------------------------------------------
    */
    'websocket' => [
        'enabled' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Console output will be transferred to response content if enabled.
    |--------------------------------------------------------------------------
    */
    'ob_output' => true,

    /*
    |--------------------------------------------------------------------------
    | Instances here will be cleared on every request.
    |--------------------------------------------------------------------------
    */
    'instances' => [
        //
        "events",
        "Database",
        "DB",
        "listen",
        'log',
        'cache',
    ],

    /*
    |--------------------------------------------------------------------------
    | Providers here will be registered on every request.
    |--------------------------------------------------------------------------
    */
    'providers' => [
        Illuminate\Pagination\PaginationServiceProvider::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Define your swoole tables here.
    |
    | @see https://www.swoole.co.uk/docs/modules/swoole-table
    |--------------------------------------------------------------------------
    */
    'tables' => [
       
    ]
];
`

**Comment by codercms** [comment]
@derrck you should remove "db" from the "instances" section. And it should be registred in the "pre_resolved" section. 
Try this config - https://github.com/swooletw/laravel-swoole/blob/master/config/swoole_http.php , this should help.

P.S. You can read more about the "instances" section here - https://github.com/swooletw/laravel-swoole/wiki/2.-Swoole-Structure#sandbox-container

**Comment by derrck** [comment]
@codercms Thank you very much, I missed "**pre_resolved**", remove "db" from "pre_resolved" then it worked!

**Comment by derrck** [comment]
Remove "db" from "pre_resolved"

**Comment by huangxingle2009** [comment]
![image](https://user-images.githubusercontent.com/4972859/91108181-d5db4500-e6a9-11ea-8498-15f0991cada4.png)
do not work in laravel  6+
![image](https://user-images.githubusercontent.com/4972859/91108200-e5f32480-e6a9-11ea-954c-7d4a14c503a1.png)

**Comment by derrck** [comment]
> ![image](https://user-images.githubusercontent.com/4972859/91108181-d5db4500-e6a9-11ea-8498-15f0991cada4.png)
> do not work in laravel 6+
> ![image](https://user-images.githubusercontent.com/4972859/91108200-e5f32480-e6a9-11ea-954c-7d4a14c503a1.png)

I'm using laravel 5
