### ISSUE TITLE
Unauthorized requests passed without check!!

### ISSUE THREAD

**Issue by AbbasovMakrov** [swooletw/laravel-swoole#359]
When using middleware (auth:api) and removing header Authorization the response gives data it should be to give unauthorized response .
Laravel : 6.2.0
Swoole : 2.6

**Comment by MostafaRabia** [comment]
Same here
Larave 5.8

And I don't have any auth from the project, unless if i authnticated someone like:
`\Auth::loginUsingId($id);`
It works, without it nothing is come!
