### ISSUE TITLE
when i start swoole for a few days , it return error with mysql connect , laravel return  "message": "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

### ISSUE THREAD

**Issue by JamesKid** [swooletw/laravel-swoole#361]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
php version:   7.3.10 
swoole version: 4.4.12

2. Please provide your Laravel/Lumen version.

laravel version:  6.5.2

3. Which release version of this package are you using?
  "swooletw/laravel-swoole": "^2.6",

4. What did you do? If possible, provide a recipe for reproducing the error.
when i start swoole for a few days , it return error with mysql connect , laravel return  "message": "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away,   and i need to run php artisan swoole:http reload then it's ok . 

5. What did you expect to see?
            

6. What did you see instead?

**Comment by HenkPoley** [comment]
From other long running servers that use MySQL, this usually means a new MySQL connection needs to be set up. Often the object that you use to connect with the database has boolean which states that the last query had a problem, then the next query will re-connect.

I'm not sure if Laravel(-swoole) would do any of that, if you would just retry te query.

**Comment by codercms** [comment]
@HenkPoley to be sure, Laravel it does:
* https://github.com/illuminate/database/blob/master/Connection.php#L621
* https://github.com/illuminate/database/blob/master/Connection.php#L716
* https://github.com/illuminate/database/blob/master/DetectsLostConnections.php

@JamesKid can you reproduce your issue with these steps?
0. Set swoole workers count to 1 (`config/swoole_http.php`, 'worker_num')
1. Run HTTP request when your app is connected to MySQL
2. Stop MySQL server and run HTTP request again, you should get MySQL server has gone away
3. Start MySQL server and run HTTP request again, it should be fine now

**Comment by ritaswc** [comment]
Yes，I HAVE the same question
```
PDOStatement::execute(): MySQL server has gone away (SQL: select * from `xxxx` where `freeze_end_time` < 2020-05-04 16:02:00 and `status` = 0 and `xxxx`.`delete_time` is null order by `id` asc limit 100 offset 0 for update)
```

**Comment by martyrs** [comment]
any workarounds for this?

**Comment by Arkanius** [comment]
Unable to reproduce here as well

**Comment by jsnoriegam** [comment]
Got the same issue, as far as I can tell it happens after an severe error occurs, the database connection stays open even when the server killed the connection, and keeps showing General error: 2006 MySQL server has gone away.
