### ISSUE TITLE
Lumen Oauth Authorization Issue

### ISSUE THREAD

**Issue by Kreateyou** [swooletw/laravel-swoole#364]
1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

**- PHP 7.2.24**
**- Swoole Version => 4.4.2**

2. Please provide your Laravel/Lumen version.

- **Lumen (6.2.0) (Laravel Components ^6.0)**

3. Which release version of this package are you using?

**- Swoole Version => 4.4.2**

4. What did you do? If possible, provide a recipe for reproducing the error.

> I have installed passport Outh2 provider however i have noted that the access token issued is throwing unautheticated error for the first few initial requests (1-3) however when i use the php artisan serve the same token is not throwing this errors 

5. What did you expect to see?

> Authentication to be accepted for first and subsequent request until token expiry

6. What did you see instead?

> Valid token not being authenticated for the first 1-3 request though it is allowed on the the following request after x number of attempts to use the same token

**Comment by codercms** [comment]
@Kreateyou you should add PassportServiceProvider to the list of providers which will be registered on every request (`config/swoole_http.php`, 'providers' section). https://github.com/swooletw/laravel-swoole/issues/123#issuecomment-414349117
