### ISSUE TITLE
DYNAMIC ROUTES NOT FOUND

### ISSUE THREAD

**Issue by Kreateyou** [swooletw/laravel-swoole#374]
1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

```
PHP 7.2
Swoole 4.4.15

```

2. Please provide your Laravel/Lumen version.

 Laravel Framework Lumen (6.2.0) (Laravel Components ^6.0)

3. Which release version of this package are you using?
2.6

4. What did you do? If possible, provide a recipe for reproducing the error.

 Registering dynamic routes  in Service provider using the following approach

```
 $this->app->router->group(['namespace' => $this->getNamespace()], function ($app) use ($path) {
         
            require $path_to_routes_php;
  });
```

5. What did you expect to see?
All routes in` $path_to_routes_php; `to be accessible 
When i serve using `php -S localhost:8000 -t ./public` the routes are accessible

6. What did you see instead?
**Page NotFound Exception** when i serve using `php artisan swoole:http start`

**Comment by phucps89** [comment]
I have this issue too in lumen 6.3.
Anyone fixed?

**Comment by folkevil** [comment]
I got the same problem, using Laravel with nWidard/laravel-modules, routes from Modules didn't found.

**Comment by jimanx2** [comment]
Same here got same issue when using caffeinated/modules. 

I managed to get around it by replacing Route::group(....) to $this->app->router->group(....) in RouteServiceProvider.php

**Comment by hsynnt** [comment]
I got same error, anyone did fixed it

**Comment by hsynnt** [comment]
> I got the same problem, using Laravel with nWidard/laravel-modules, routes from Modules didn't found.

Did you find any solution for this ?
