### ISSUE TITLE
Deploy with Apache Server

### ISSUE THREAD

**Issue by Niroj11** [swooletw/laravel-swoole#380]
I have tested this by serving the application and I have seen significant results.

I just need to know how can I deploy this with apache?

**Comment by albertcht** [comment]
How do you integrate apache server with this package?
Are you using apache server only as a proxy server in front of Swoole Server?

**Comment by mRamadan0101** [comment]
<VirtualHost *:80> 
  ProxyPreserveHost On
  ProxyRequests Off
  ServerName www.example.com
  ServerAlias example.com
  ProxyPass / http://localhost:1215/example/
  ProxyPassReverse / http://localhost:1215/example/
</VirtualHost>

**Comment by Arkanius** [comment]
Don't forget to start your swoole process at each deploy. (php artisan swoole:http start)

See: https://github.com/swooletw/laravel-swoole/wiki/6.-Commands
