### ISSUE TITLE
Laravel 7 request error

### ISSUE THREAD

**Issue by MostafaRabia** [swooletw/laravel-swoole#389]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
`PHP 7.4.3 (cli) (built: Feb 23 2020 07:24:48) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies`

`swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.16
Built => Mar 11 2020 16:30:30
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608`

2. Please provide your Laravel/Lumen version.
7.2

3. Which release version of this package are you using?
Last, ^2.6

4. What did you do? If possible, provide a recipe for reproducing the error.
```
php artisan optimize:clear
php artisan optimize
```
then using my project, but request returns null!

5. What did you expect to see?
request returns with my inputs

6. What did you see instead?
$request->all(); => null!

If i did `php artisan optimize:clear` it works, and in apache it works.

**Comment by caiokawasaki** [comment]
Same here

**Comment by meditic** [comment]
same problem here.
after I run "php artisan route:clear" and reload swoole, it works
@albertcht

**Comment by Arkanius** [comment]
You app isn't loaded at memory when you run this command (that's why it works after reload swoole). Don't forget that swoole will load your application just once. If these files (the cached ones) exists when you start your swoole then they will be loaded in your RAM, else they won't.
