### ISSUE TITLE
Target [App\Contract\SendOrder\SendOrderInterface] is not instantiable

### ISSUE THREAD

**Issue by lxyzsl** [swooletw/laravel-swoole#390]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
php 7.2
swoole 4.4.14

2. Please provide your Laravel/Lumen version.

laravel 5.8

3. Which release version of this package are you using?

laravel-swoole:2.6

4. What did you do? If possible, provide a recipe for reproducing the error.

![image](https://user-images.githubusercontent.com/17881085/77999056-a75c7680-7364-11ea-8d8b-d4e3c5497ecf.png)
![image](https://user-images.githubusercontent.com/17881085/77999083-b3e0cf00-7364-11ea-978b-fd07ded411a9.png)

But it's normal in FPM

5. What did you expect to see?

6. What did you see instead?

**Comment by Arkanius** [comment]
Please, provide your exception. It looks like a problem with your laravel installation (I couldn't reproduce)
