### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by MostafaRabia** [swooletw/laravel-swoole#391]
If i ran swoole in ip and port like this:
MY_SERVER_IP:MY_SSL_PORT
Without apache or nginx, is it right? it's working, but it's right?

And if in production i need to update website, how can i update it? If i restarted swoole it will cause anything? Or what should i do?

And very thanks.

**Comment by mRamadan0101** [comment]
> Without apache or nginx, is it right? it's working, but it's right?

i dont think that bec php install apache2 when installing 

i think at least u need apache2 to create and run your server

**Comment by mRamadan0101** [comment]
> And if in production i need to update website, how can i update it? If i restarted swoole it will cause anything? Or what should i do?
restart swoole server when pull anything 
in some cases u will stop server and run ` composer  dump-autoload ` to fix any issue

**Comment by MostafaRabia** [comment]
@mRamadan0101 
I run it already without apache or nginx, I have server that has ip and domain for this ip.
Just i put my ip server in:
SWOOLE_HTTP_HOST=MY_SERVER_IP
SWOOLE_HTTP_PORT=MY_SSL_SERVER 443

And it's running, so is it right thing to do?

And if i used nginx, what will nginx do that swoole won't do?
If i user nginx, will my project run with swoole and its speed or nginx?
In other words, Where is swoole if i used apache or nginx?

"restart swoole server when pull anything
in some cases u will stop server and run composer dump-autoload to fix any issue"
Thanks for it, But it won't cause anything?

**Comment by mRamadan0101** [comment]
> I run it already without apache or nginx, I have server that has ip and domain for this ip.
how to set root files for laravel if u didnt use nginx or apache server

**Comment by mRamadan0101** [comment]
> And if i used nginx, what will nginx do that swoole won't do?
> If i user nginx, will my project run with swoole and its speed or nginx?
> In other words, Where is swoole if i used apache or nginx?

you can see swoole performance before and after using it 
for me i dont know how to use only swoole as a server without nginx but i see performance is differente  before and after it

**Comment by MostafaRabia** [comment]
@mRamadan0101 

> how to set root files for laravel if u didnt use nginx or apache server

What do you mean?

And thanks for last comment.

**Comment by mRamadan0101** [comment]
in nginx server you can setup your root folder that contain public folder in your laravel project and then open index.php to start your project 
how can make it with swoole ?

**Comment by MostafaRabia** [comment]
@mRamadan0101 
Swoole public folder is public, it contains index.php and my styles, Just i run my server and all is fine.

**Comment by mRamadan0101** [comment]
>  Swoole public folder is public, it contains index.php and my styles, Just i run my server and all is fine.

can you explain more and how to set swoole folder as a root directory

**Comment by MostafaRabia** [comment]
@mRamadan0101 

What i did is define:
SWOOLE_HTTP_HOST=127.0.0.1
SWOOLE_HTTP_PORT=1215
In .env file, to change it on the server to what i need.

And in config:
        'server' => [
        'host' => env('SWOOLE_HTTP_HOST', '127.0.0.1'),
        'port' => env('SWOOLE_HTTP_PORT', '1215'),
        'public_path' => base_path('public'),

And public path has:
![image](https://user-images.githubusercontent.com/25965798/79365462-f7356300-7f4a-11ea-98bf-2488914e6e26.png)

Then everything going right.

**Comment by mRamadan0101** [comment]
@MostafaRabia 
so this mean ur project will run only with port 1215 not 80 ?

**Comment by MostafaRabia** [comment]
@mRamadan0101 
No, i changed it to 443 ssl port in server

**Comment by mRamadan0101** [comment]
>  No, i changed it to 443 ssl port in server

i understand now 
thanks for your replies

**Comment by MostafaRabia** [comment]
@mRamadan0101 
Thanks, now what's your opinion? Is it right way?

**Comment by mRamadan0101** [comment]
>  Thanks, now what's your opinion? Is it right way?

yes right way only swoole server is faster than using nginx or apache with proxy

**Comment by MostafaRabia** [comment]
@mRamadan0101 
Thanks, and there is no security issuses?

**Comment by Arkanius** [comment]
@MostafaRabia I like to use nginx as a proxy to swoole. Nginx runs with an event loop (same as swoole), with it you won't get performance issues. 

About security, all reports about swoole security that I've ever seen wasn't swoole problem but the way that the users were using it. Check: https://github.com/swooletw/laravel-swoole/wiki/9.-Nginx-Configuration
