### ISSUE TITLE
Predis\Connection\ConnectionException: Error while writing bytes to the server

### ISSUE THREAD

**Issue by zhongjq** [swooletw/laravel-swoole#396]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

PHP 7.3.6-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May 31 2019 11:06:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.6-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.17
Built => Apr  2 2020 18:42:34
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
pcre => enabled
zlib => 1.2.8
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

2. Please provide your Laravel/Lumen version.

Laravel 5.8

3. Which release version of this package are you using?

2.6.67

4. What did you do? If possible, provide a recipe for reproducing the error.

swoole_websocket.php

'default' => 'redis',

'setting' => [
    'redis' => [
            'server' => [
                'host' => env('REDIS_HOST', '127.0.0.1'),
                'password' => env('REDIS_PASSWORD', null),
                'port' => env('REDIS_PORT', 6379),
                'database' => 1,
                'persistent' => true,
                'read_write_timeout' => 0,
            ],
            'options' => [
                //
            ],
            'prefix' => 'swoole:',
    ],
]

5. What did you expect to see?

normal running

6. What did you see instead?

When running online, the following error is reported after a while

Predis\Connection\ConnectionException: Error while writing bytes to the server. [tcp://127.0.0.1:6379] in /mnt/data/wwwroot/qtopay.net/vendor/predis/predis/src/Connection/AbstractConnection.php:155Stack trace:
#0 /mnt/data/wwwroot/qtopay.net/vendor/predis/predis/src/Connection/StreamConnection.php(298): Predis\Connection\AbstractConnection->onConnectionError('Error while wri... ')#1 /mnt/data/wwwroot/qtopay.net/vendor/predis/predis/src/Connection/StreamConnection.php(394): Predis\Connection\StreamConnection->write('*2\r\n$8\r\nSMEMBER...')
#2 /mnt/data/wwwroot/qtopay.net/vendor/predis/predis/src/Connection/AbstractConnection.php(110): Predis\Connection\StreamConnection-                                       >writeRequest(Object(Predis\Command\SetMembers))#3 /mnt/data/wwwroot/qtopay.net/vendor/predis/predis/src/Client.php(331): Predis\Connection\AbstractConnection->executeCommand(Object(Predis\Command\SetMembers))
#4 /mnt/data/wwwroot/qtopay.net/vendor/predis/predis/src/Client.php(314): Predis\Client->executeCommand(Object(Predis\Command\SetMembers))
#5 /mnt/data/wwwroot/qtopay.net/vendor/swooletw/laravel-swoole/src/Websocket/Rooms/RedisRoom.php(222): Predis\Client->__call('smembers', Array)
#6 /mnt/data/wwwroot/qtopay.net/vendor/swooletw/laravel-swoole/src/Websocket/Rooms/RedisRoom.php(195): SwooleTW\Http\Websocket\Rooms\RedisRoom->getValue('215221', 'fds')
#7 /mnt/data/wwwroot/qtopay.net/vendor/swooletw/laravel-swoole/src/Websocket/Rooms/RedisRoom.php(119): SwooleTW\Http\Websocket\Rooms\RedisRoom->getRooms(215221)#8 /mnt/data/wwwroot/qtopay.net/vendor/swooletw/laravel-swoole/src/Websocket/Websocket.php(151): SwooleTW\Http\Websocket\Rooms\RedisRoom->delete(215221, Array)
#9 /mnt/data/wwwroot/qtopay.net/vendor/swooletw/laravel-swoole/src/Concerns/InteractsWithWebsocket.php(174): SwooleTW\Http\Websocket\Websocket->leave()
#10 {main}

**Comment by Arkanius** [comment]
Well, it looks like an issue with your local redis configuration and installation. Try to test with an external redis resource (e.g Elastic Cache)  and see what happens please
