### ISSUE TITLE
laravel7 request 问题

### ISSUE THREAD

**Issue by hanyue2020** [swooletw/laravel-swoole#400]
我这边直接用fpm通过postman请求是可以获取到 request的参数
但是如果访问swoole 就获取不到，但是打印出来是有的。正常的登陆请求一直提示我手机号不存在
![photo_2020-04-18_16-53-49](https://user-images.githubusercontent.com/5828315/79633017-6a321a00-8195-11ea-93db-9cebcb315930.jpg)

**Comment by Arkanius** [comment]
English post please
