### ISSUE TITLE
Room Message cannot received by its own sender

### ISSUE THREAD

**Issue by b0091309** [swooletw/laravel-swoole#403]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

Ans: 
PHP 7.4.3 
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.17
Built => Apr 22 2020 11:40:27
coroutine => enabled
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1g  21 Apr 2020
pcre => enabled
zlib => 1.2.11
brotli => E16777223/D16777223
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144

2. Please provide your Laravel/Lumen version.

Ans: 
Laravel Framework 6.18.0

3. Which release version of this package are you using?

Ans: 
"swooletw/laravel-swoole": "^2.6",

4. What did you do? If possible, provide a recipe for reproducing the error.

There have 3 user(different fd) inside the room named 'test'
broadcast()->to('test')->emit(message)
User A send message then UserB, UserC can received
But User A cannot received his own message.
Is that normal?

5. What did you expect to see?

It would better can received all the message even from sender itself

6. What did you see instead?

UserA broadcast message to room 'test'
UserB can received
UserC can received
UserA cannot received it own message

**Comment by Arkanius** [comment]
As far as i know broadcast is only used to tell everyone except for yourself.
