### ISSUE TITLE
Hot Reload for Docker is not working

### ISSUE THREAD

**Issue by csmtcy** [swooletw/laravel-swoole#405]
I'm creating a Dockerfile for the swoole environment, others are working fine just left the hot reload function. I tried with both fswatch and inotify with no lucks. Every time i edit the files the inotify / fswatch doesn't trigger the action, but sometimes it works on storage cache view.

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
PHP Version     | 7.2.1  
Swoole Version  | 4.5.0  

2. Please provide your Laravel/Lumen version.
Laravel Version | 7.7.1

3. Which release version of this package are you using?
^2.6

4. What did you do? If possible, provide a recipe for reproducing the error.
I tried to use the custom sh script with no lucks also 

fswatch (Referred from LaravelS)
```
#!/usr/bin/env bash
WORK_DIR=$1
if [ ! -n "${WORK_DIR}" ] ;then
    WORK_DIR="."
fi

echo "Restarting LaravelS..."
php artisan swoole:http reload

echo "Starting fswatch..."
LOCKING=0
fswatch -e ".*" -i "\\.php$" -r ${WORK_DIR} | while read file
do
    if [[ ! ${file} =~ .php$ ]] ;then
        continue
    fi
    if [ ${LOCKING} -eq 1 ] ;then
        echo "Reloading, skipped."
        continue
    fi
    echo "File ${file} has been modified."
    LOCKING=1
    php artisan swoole:http reload
    LOCKING=0
done
exit 0
```

Dockerfile 
```
FROM php:7.2.1-cli

# RUN docker-php-source extract \
#    # do important things \
#    && docker-php-source delete

#RUN apt-get update
#RUN apt-get install libbz2-dev

RUN apt-get update && apt-get install -y libbz2-dev libpng-dev libfreetype6-dev libjpeg* inotify-tools wget gnupg2

RUN wget https://github.com/emcrisostomo/fswatch/releases/download/1.14.0/fswatch-1.14.0.tar.gz
RUN tar -xzvf fswatch-1.14.0.tar.gz
RUN cd fswatch-1.14.0 && ./configure && make && make install && ldconfig

RUN docker-php-ext-configure gd \
        --enable-gd-native-ttf \
        --with-freetype-dir=/usr/include/freetype2 \
        --with-png-dir=/usr/include \
        --with-jpeg-dir=/usr/include

RUN docker-php-ext-install \
        pdo_mysql gd exif mbstring zip mysqli

# install mongodb ext
RUN pecl install mongodb swoole \
        && docker-php-ext-enable mongodb swoole

# RUN a2enmod rewrite

WORKDIR /var/www/html

#php -i | grep curl

RUN chown -R www-data:www-data /var/www/html

EXPOSE 1215
```

5. What did you expect to see?
It should be triggered when i edit any php files inside the project recursively

6. What did you see instead?
It doesn't really get triggered every time i edit / create / delete the files.

**Comment by Arkanius** [comment]
Try to use: https://github.com/swooletw/watcher
