### ISSUE TITLE
watcher.js hot reload is error

### ISSUE THREAD

**Issue by szwss** [swooletw/laravel-swoole#413]
| PHP Version     | 7.4.5                                          |
| Swoole Version  | 4.5.1                                          |
| Laravel Version | 5.8.38                                         |
| Listen IP       | workspace                                      |
| Listen Port     | 1215                                           |
| Server Status   | Online                                         |
| Reactor Num     | 6                                              |
| Worker Num      | 6                                              |
| Task Worker Num | 0                                              |
| Websocket Mode  | Off                                            |
| Master PID      | 1276                                           |
| Manager PID     | 1277                                           |
| Log Path        | /var/www/dazhehui/storage/logs/swoole_http.log

run node watcher.js

PID 1276,1277 is not alive.

**Comment by szwss** [comment]
I use laradock, I use the built-in
SWOOLE_HOT_RELOAD_ENABLE = true
Hot update is invalid
I only update the code immediately if worker_num = 1, max_request = 1
I want to use a better solution today, watcher.js, but I also get an error and cannot be used

**Comment by Arkanius** [comment]
@szwss try to check this: https://github.com/swooletw/laravel-swoole/issues/418

**Comment by szwss** [comment]
@Arkanius thank you very mach
