### ISSUE TITLE
Swoole is suspended when an exception occurs

### ISSUE THREAD

**Issue by hawkcraw** [swooletw/laravel-swoole#422]
PHP Version : 7.2.24-0ubuntu0.18.04.6  
Swoole Version  : 4.4.5-alpha  
Laravel Version : 5.7.3

when APP_DEBUG = true (failed)
The page has been waiting(Fake death) when an laravel exception occurs
e.g. Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException

when APP_DEBUG = false (success)
The page show "Whoops, looks like something went wrong." when an laravel exception occurs

I want laravel can show exception detail, but it doest work

Is it because the exception information is too large?, swoole doesn't work

**Comment by Arkanius** [comment]
I coudn't reproduce it here. Can you share your exception as an example?
