### ISSUE TITLE
I can't connect to my server when I use swoole+grpc

### ISSUE THREAD

**Issue by lixidong** [swooletw/laravel-swoole#425]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
 PHP version: 7.2.26
 Swoole version: 4.5.2

2. Please provide your Laravel/Lumen version.
 Laravel version: 5.8.38

3. Which release version of this package are you using?
2.6

4. What did you do? If possible, provide a recipe for reproducing the error.
I have a go server and  use php as client.
I can get data when I don't use swoole but php-fpm.

5. What did you expect to see?
I can get data when I don't use swoole but php-fpm.

6. What did you see instead?
time-out

**Comment by muGua123** [comment]
Add grpc.enable_fork_support=on to the php.ini file

**Comment by albertcht** [comment]
How do you use your grpc client?
