### ISSUE TITLE
laravel.ERROR: Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by gliese436-b** [swooletw/laravel-swoole#426]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

PHP：7.3.2
Swoole：4.4.8

2. Please provide your Laravel/Lumen version.

Laravel：6.2

3. Which release version of this package are you using?

  "swooletw/laravel-swoole": "^2.6"

4. What did you do? If possible, provide a recipe for reproducing the error.

 setcookie('token',null,time() - 1,'/','.test.cn');

OR

 header("Location:https://xxx.comt");

5. What did you expect to see?

6. What did you see instead?

laravel.ERROR: Cannot modify header information - headers already sent

**Comment by mxp100** [comment]
use via response, this is bug of laravel (not laravel-swoole)
Example: response()->cookie() or response()->header()

**Comment by Arkanius** [comment]
As @mxp100 said, after start using swoole you need to use Laravel's response, request, etc.

Check: https://github.com/swooletw/laravel-swoole/wiki/Z1.-Notices
