### ISSUE TITLE
When there are multiple works, the result of room:: getrooms is wrong

### ISSUE THREAD

**Issue by nyg123** [swooletw/laravel-swoole#430]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
PHP 7.4.7 
swoole 4.4.16

2. Please provide your Laravel/Lumen version.
Laravel v5.8.35

3. Which release version of this package are you using?
v2.6.67

4. What did you do? If possible, provide a recipe for reproducing the error.

Errors are only reproduced in worker_num>1
`Room::add(1,1);`
`Room::add(2,2);`

in one request 
`$room1 = Room::getRooms(1);`
and execute in another
`$room2 = Room::getRooms(2);`

When two requests are made at the same time, the results are exchanged

5. What did you expect to see?
`$room1==[1]`
`$room2==[2]`

6. What did you see instead?
`$room1==[2]`
`$room2==[1]`

**Comment by albertcht** [comment]
Hi @nyg123 ,

Unable to reproduce this issue.
