### ISSUE TITLE
Doctrine EntityManager lost db connection

### ISSUE THREAD

**Issue by bogvsdev** [swooletw/laravel-swoole#432]
When running laravel swoole on server along with "laravel-doctrine/orm": "1.6.*" found that it's entity manager can loose connection and that would block whole application from correct work. Only restarting swoole server can resolve this issue.

While examining this issue found similar problem for symfony and solution https://github.com/pixelfederation/doctrine-resettable-em-bundle. The question is how can I add similar solution to laravel when it's running on swoole?

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

PHP 7.4.8, Swoole 4.5.2

2. Please provide your Laravel/Lumen version.

Laravel Framework 7.20

3. Which release version of this package are you using?

Version 2.6

4. What did you do? If possible, provide a recipe for reproducing the error.
Used app functionality and nothing that would harm swoole server or mysql server.

5. What did you expect to see?

Working application

6. What did you see instead?

Database connection errors in application and error in swoole_http.log
`WARNING swSignalfd_onSignal (ERRNO 707): Unable to find callback function for signal Broken pipe: 13`

**Comment by Arkanius** [comment]
Try to check this out: https://alejandrocelaya.blog/2019/11/04/how-to-properly-handle-a-doctrine-entity-manager-on-an-expressive-application-served-with-swoole/
