### ISSUE TITLE
Has this project been discontinued?

### ISSUE THREAD

**Issue by danilofalcao** [swooletw/laravel-swoole#435]
Hi All,

I'm under the impression this project has been discontinued by its maintainers. Should we (community) fork it and continue its development somewhere else/another repo?

Trying to reach out to @youchenlee and @albertcht again.

**Comment by wesdrass** [comment]
yeah, why not

**Comment by Arkanius** [comment]
Unfortunatelly that's what it looks like. There some simple PR's to be merged (like Laravel 8) that don't even needs to be reviewed. I think that the mainteiners should find another maintainer (from community) in order to keeps the repo alive

**Comment by albertcht** [comment]
Hi @danilofalcao ,

Thanks for your your concern about this project. Indeed, this project is not in active contribution in 2020. And I think you're right, this project needs more maintainers to keep it going.

The maintainers this project requires need to have deep understandings about Laravel's lifecycle and base components. Besides, they need to figure out the differences between Swoole and traditional PHP. If there's anyone who is interested in maintaining this project, please let me know.

Before there are new maintainers' help. I will still try to keep reviewing and merging new coming pull requests.

**Comment by albertcht** [comment]
By the way, I've merged a couple pull requests including the support for Laravel 8. However, this package is not fully tested in Laravel 8, it's not guaranteed 100 % compatible with it.

I will publish the new release very soon.

**Comment by danilofalcao** [comment]
Thanks @albertcht! Much appreciated.

**Comment by Arkanius** [comment]
Hi @albertcht, I might be able to give you some help. I know how Laravel works and I'm deeply studing about swoole for now. I think I can help with issues management (answers, labels, some tests) and with some PR's. I can run some tests with Laravel 8 at this moment as well.

**Comment by albertcht** [comment]
Hi @Arkanius ,

Much appreciated for your help on this package!
