### ISSUE TITLE
SQLSTATE[08004] [1040] Too many connections

### ISSUE THREAD

**Issue by muGua123** [swooletw/laravel-swoole#436]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

PHP 7.2.5 (cli) (built: May  5 2018 00:18:54) ( NTS )
Swoole Version => 4.5.2

2. Please provide your Laravel/Lumen version.

Laravel Framework 7.14.1

3. Which release version of this package are you using?

v2.6.67

4. What did you do? If possible, provide a recipe for reproducing the error.

When I use the default configuration, the data cannot be synchronized to the database. I guess it is contaminated, so I added lluminate\Database\DatabaseServiceProvider::class to the providers of swoole_http.php. The previous problem was solved, but there were too many connections

![image](https://user-images.githubusercontent.com/25149926/94509675-5bbd5380-0247-11eb-9f1d-86407a23b06e.png)

![image](https://user-images.githubusercontent.com/25149926/94505866-a1c1e980-023e-11eb-9f96-871fbfd0f140.png)

5. What did you expect to see?

I hope that every time Illuminate\Database\DatabaseServiceProvider::class is reinjected into the sandbox, the sandbox can close the mysql connection established to process the previous request

6. What did you see instead?

I found it didn't

**Comment by Arkanius** [comment]
What do you mean by?
> When I use the default configuration, the data cannot be synchronized to the database. I guess it is contaminated

What happens when you don't use the DatabaseServiceProvider at providers config?

> I hope that every time Illuminate\Database\DatabaseServiceProvider::class is reinjected into the sandbox, the sandbox can close the mysql connection established to process the previous request

I think it already happens by using db.factory at **pre_resolved** array

**Comment by muGua123** [comment]
> What do you mean by?
> 
> > When I use the default configuration, the data cannot be synchronized to the database. I guess it is contaminated
> 
> What happens when you don't use the DatabaseServiceProvider at providers config?
> 
> > I hope that every time Illuminate\Database\DatabaseServiceProvider::class is reinjected into the sandbox, the sandbox can close the mysql connection established to process the previous request
> 
> I think it already happens by using db.factory at **pre_resolved** array

hi, thanks, I removed db.factory from providers, but every new request increases the number of mysql connections
![image](https://user-images.githubusercontent.com/25149926/94509367-aab6b900-0246-11eb-8de7-c6e7a636edca.png)
![image](https://user-images.githubusercontent.com/25149926/94509408-c28e3d00-0246-11eb-938c-08df0280db4f.png)

**Comment by Arkanius** [comment]
What happens when you don't use the DatabaseServiceProvider at providers config? I mean, do you still get the to many connections error?

**Comment by muGua123** [comment]
> What happens when you don't use the DatabaseServiceProvider at providers config? I mean, do you still get the to many connections error?

If I do not add DatabaseServiceProvider to the providers array, too many connections will not appear. But the system runs for a period of time, it will happen that the data will not persist to the mysql database, but only exist in the memory, and no error message can be found in the log. I guess it is contaminated, so I added the DatabaseServiceProvider to the providers array

**Comment by Arkanius** [comment]
Could you past here how you're inserting the data?

**Comment by muGua123** [comment]
> Could you past here how you're inserting the data?



> Could you past here how you're inserting the data?

Hi brother, I found that there is a place where the transaction did not roll back, and the function directly returned, which affected the subsequent transaction. I am now correcting it and removing the DatabaseServiceProvider from the providers array.
