### ISSUE TITLE
Async insert queries in mysql?

### ISSUE THREAD

**Issue by Troodi** [swooletw/laravel-swoole#438]
How to use and config swoole for make async insert queries? I just try find docs but can't. I was tryed use driver mysql-coroutine, but got error: `Unsupported driver [mysql-coroutine]`. Possible make async?

**Comment by Arkanius** [comment]
Hum, I think [mysql-coroutine] isn't support at this moment.

How did you try to connect?

**Comment by albertcht** [comment]
Hi @Troodi ,

Like what @Arkanius said, coroutine feature in laravel is not safe. I suggest not to use coroutine or async io in this project.
