### ISSUE TITLE
Swoole Caching

### ISSUE THREAD

**Issue by samehhamdy** [swooletw/laravel-swoole#440]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
PHP 7.4.8
SWOOLE 4.5.2

2. Please provide your Laravel/Lumen version.
^7.0

3. Which release version of this package are you using?
^2.6

4. What did you do? If possible, provide a recipe for reproducing the error.
laravel swoole caching problem 
there is proplem with me that i have a production web app laravel app on apache web server on ubuntu 18.04 and its perfomance is very good but when i run swoole web server  the web app became slow and not cashing like apache and assets files like css and js take longer than on apache     

5. What did you expect to see?

i expect more performane and more speed than apache

6. What did you see instead?

very slow app

**Comment by Arkanius** [comment]
>  when i run swoole web server the web app became slow and not cashing like apache and assets files like css and js take longer than on apache

How are you running it?

**Comment by samehhamdy** [comment]
> > when i run swoole web server the web app became slow and not cashing like apache and assets files like css and js take longer than on apache
> 
> How are you running it?

I need it for swoole websockets and as it speed up app but the that's not happened

**Comment by Arkanius** [comment]
Did you make sure that you're running the event loop? It looks like a problem in your environment. Also, it doesn't look like a cache  issue. 

Are you trying to run apache + swoole?

**Comment by samehhamdy** [comment]
is it possible run swoole on apache

> Did you make sure that you're running the event loop? It looks like a problem in your environment. Also, it doesn't look like a cache issue.
> 
> Are you trying to run apache + swoole?

is it possible to run swoole on apache ?

**Comment by Arkanius** [comment]
The recomendation is to run with a web server serving it as a proxy: https://github.com/swooletw/laravel-swoole/wiki/9.-Nginx-Configuration

See: https://github.com/swoole/swoole-src/issues/1376

**Comment by samehhamdy** [comment]
solved by nginx with swoole
