### ISSUE TITLE
Laravel 7 auth not working 

### ISSUE THREAD

**Issue by mrmarchone** [swooletw/laravel-swoole#442]
i have more than one guard , laravel/swooleTw take the default gurad (web) ? how to make take any guard ?!

**Comment by Arkanius** [comment]
Need an example. Please follow the issue template

**Comment by mrmarchone** [comment]
$request->user() return with null

**Comment by Arkanius** [comment]
Well, I'm running my apps in production using Laravel 7 and I use the *$request->user()* without problems. Please, try to give more info about your issue
