### ISSUE TITLE
Assistance with laravel-swoole and Laravel Nova optimal settings

### ISSUE THREAD

**Issue by lagerroos** [swooletw/laravel-swoole#444]
1. Please provide your PHP and Swoole version.
PHP 7.4.11, Swoole 4.5.4

2. Please provide your Laravel/Lumen version.
8.11.2

3. Which release version of this package are you using?
2.6.68

4. What did you do? If possible, provide a recipe for reproducing the error.
I'm trying to get Laravel Nova to authenticate users separately. As for now, as soon as one user logs in - any user can access that session. In other words, Swoole does not authorize users individually as intended.

5. What did you expect to see?
Limited sessions not publically open.

6. What did you see instead?
Se above. Here's my swoole_http.php:

```
<?php

use App\Http\Middleware\Authenticate;
use Laravel\Nova\Http\Middleware\Authorize;
use Laravel\Nova\Http\Middleware\BootTools;
use Laravel\Nova\Http\Middleware\DispatchServingNovaEvent;

return [
    /*
    |--------------------------------------------------------------------------
    | HTTP server configurations.
    |--------------------------------------------------------------------------
    |
    | @see https://www.swoole.co.uk/docs/modules/swoole-server/configuration
    |
    */
    'server' => [
        'host' => env('SWOOLE_HTTP_HOST', '127.0.0.1'),
        'port' => env('SWOOLE_HTTP_PORT', '1210'),
        'public_path' => base_path('public'),
        // Determine if to use swoole to respond request for static files
        'handle_static_files' => env('SWOOLE_HANDLE_STATIC', true),
        'access_log' => env('SWOOLE_HTTP_ACCESS_LOG', false),
        // You must add --enable-openssl while compiling Swoole
        'socket_type' => SWOOLE_SOCK_TCP || SWOOLE_SSL,
        'process_type' => SWOOLE_PROCESS,
        'options' => [
            'pid_file' => env('SWOOLE_HTTP_PID_FILE', base_path('storage/logs/swoole_http.pid')),
            'log_file' => env('SWOOLE_HTTP_LOG_FILE', base_path('storage/logs/swoole_http.log')),
            'daemonize' => env('SWOOLE_HTTP_DAEMONIZE', false),
            // Normally this value should be 1~4 times larger according to your cpu cores.
            'reactor_num' => env('SWOOLE_HTTP_REACTOR_NUM', swoole_cpu_num()),
            'worker_num' => env('SWOOLE_HTTP_WORKER_NUM', swoole_cpu_num()),
            'task_worker_num' => env('SWOOLE_HTTP_TASK_WORKER_NUM', swoole_cpu_num()),
            // The data to receive can't be larger than buffer_output_size.
            'package_max_length' => 20 * 1024 * 1024,
            // The data to send can't be larger than buffer_output_size.
            'buffer_output_size' => 10 * 1024 * 1024,
            // Max buffer size for socket connections
            'socket_buffer_size' => 128 * 1024 * 1024,
            // Worker will restart after processing this number of requests
            'max_request' => 3000,
            // Enable coroutine send
            'send_yield' => true,
            // You must add --enable-openssl while compiling Swoole
            'ssl_cert_file' => '/etc/letsencrypt/live/gustav.cdn.altitude.events/fullchain.pem',
            'ssl_key_file' => '/etc/letsencrypt/live/gustav.cdn.altitude.events/privkey.pem',
            'ssl_cert_file' => null,
            'ssl_key_file' => null,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Enable to turn on websocket server.
    |--------------------------------------------------------------------------
    */
    'websocket' => [
        'enabled' => env('SWOOLE_HTTP_WEBSOCKET', true),
    ],

    /*
    |--------------------------------------------------------------------------
    | Hot reload configuration
    |--------------------------------------------------------------------------
    */
    'hot_reload' => [
        'enabled' => env('SWOOLE_HOT_RELOAD_ENABLE', false),
        'recursively' => env('SWOOLE_HOT_RELOAD_RECURSIVELY', true),
        'directory' => env('SWOOLE_HOT_RELOAD_DIRECTORY', base_path()),
        'log' => env('SWOOLE_HOT_RELOAD_LOG', true),
        'filter' => env('SWOOLE_HOT_RELOAD_FILTER', '.php'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Console output will be transferred to response content if enabled.
    |--------------------------------------------------------------------------
    */
    'ob_output' => env('SWOOLE_OB_OUTPUT', true),

    /*
    |--------------------------------------------------------------------------
    | Pre-resolved instances here will be resolved when sandbox created.
    |--------------------------------------------------------------------------
    */
    'pre_resolved' => [
        'view', 'files', 'session', 'session.store', 'routes',
        'db', 'db.factory', 'cache', 'cache.store', 'config', 'cookie',
        'encrypter', 'hash', 'router', 'translator', 'url', 'log',
    ],

    /*
    |--------------------------------------------------------------------------
    | Instances here will be cleared on every request.
    |--------------------------------------------------------------------------
    */
    'instances' => [
        Laravel\Nova\Http\Middleware\Authenticate::class,
        DispatchServingNovaEvent::class,
        BootTools::class,
        Authorize::class,
        Authenticate::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Providers here will be registered on every request.
    |--------------------------------------------------------------------------
    */
    'providers' => [
        Illuminate\Pagination\PaginationServiceProvider::class,
    	Spatie\Ssr\SsrServiceProvider::class,
        App\Providers\NovaServiceProvider::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Resetters for sandbox app.
    |--------------------------------------------------------------------------
    */
    'resetters' => [
        SwooleTW\Http\Server\Resetters\ResetConfig::class,
        SwooleTW\Http\Server\Resetters\ResetSession::class,
        SwooleTW\Http\Server\Resetters\ResetCookie::class,
        SwooleTW\Http\Server\Resetters\ClearInstances::class,
        SwooleTW\Http\Server\Resetters\BindRequest::class,
        SwooleTW\Http\Server\Resetters\RebindKernelContainer::class,
        SwooleTW\Http\Server\Resetters\RebindRouterContainer::class,
        SwooleTW\Http\Server\Resetters\RebindViewContainer::class,
        SwooleTW\Http\Server\Resetters\ResetProviders::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Define your swoole tables here.
    |
    | @see https://www.swoole.co.uk/docs/modules/swoole-table
    |--------------------------------------------------------------------------
    */
    'tables' => [
        // 'table_name' => [
        //     'size' => 1024,
        //     'columns' => [
        //         ['name' => 'column_name', 'type' => Table::TYPE_STRING, 'size' => 1024],
        //     ]
        // ],
    ],
];


```

And NovaServiceProvider.php:

```
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Gate;
use Laravel\Nova\Cards\Help;
use Laravel\Nova\Events\ServingNova;
use Laravel\Nova\Nova;
use Laravel\Nova\NovaApplicationServiceProvider;

class NovaServiceProvider extends NovaApplicationServiceProvider
{
    public static $model = 'App\\Users\\User';

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        $this->routes();

        Nova::serving(function (ServingNova $event) {
            $this->authorization();
            $this->registerExceptionHandler();
            $this->resources();
            Nova::cards($this->cards());
            Nova::dashboards($this->dashboards());
            Nova::tools($this->tools());
        });
    }

    /**
     * Configure the Nova authorization services.
     *
     * @return void
     */
    protected function authorization()
    {
        Nova::auth(function ($request) {
            $user = auth()->user();
            return app()->environment('local') ||
                (isset($user->id) && $user->access() >= 1024);
        });
    }

    /**
     * Register the Nova routes.
     *
     * @return void
     */
    protected function routes()
    {
        Nova::routes()
                ->withAuthenticationRoutes()
                ->withPasswordResetRoutes()
                ->register();
    }

    /**
     * Register the Nova gate.
     *
     * This gate determines who can access Nova in non-local environments.
     *
     * @return void
     */
    protected function gate()
    {
        Gate::define('viewNova', function ($user) {
            return $user->access() >= 1024;
        });
    }

    /**
     * Get the cards that should be displayed on the default Nova dashboard.
     *
     * @return array
     */
    protected function cards()
    {
        return [
            new Help,
        ];
    }

    /**
     * Get the extra dashboards that should be displayed on the Nova dashboard.
     *
     * @return array
     */
    protected function dashboards()
    {
        return [];
    }

    /**
     * Get the tools that should be listed in the Nova sidebar.
     *
     * @return array
     */
    public function tools()
    {
        return [];
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}

```

**Comment by Arkanius** [comment]
Hi!

Please, try to add **'auth'** at yours **pre_resolved** key at config/swoole_http.php

**Comment by lagerroos** [comment]
Hey @Arkanius, big thanks for your reply. I actually saw your recent PR and tested adding 'auth' to the pre_resolved with no difference, still experiencing the same issue. Could there be something else spooky in work here? If you or anyone else have an example repository setup that maybe would help me figure this out.

**Comment by lagerroos** [comment]
For the record, I use Passport.

**Comment by Arkanius** [comment]
> Don't know if this affects Nova login in any certain way..
Well, I think it shouldn't. Could you try to check if your requests are reaching your Nova middleware?

**Comment by lagerroos** [comment]
Hey @Arkanius, not quite sure how to test if the request reaches the Nova middleware, but I put some logs there.
The request both passes Novas builtin authentication middleware and my NovaServiceProvider, logging the user object I can see that it's the same user indicating that the Swoole exception for Nova isn't working properly.

What I can conclude after some tests are the following:
- Logging on to Nova directly towards the Swoole server 127.0.0.1:1210 and then in incognito trying the same server address **does not work** meaning that I'm prompted with login in incognito.
- If I log in with NGINX site domain.com involved, the incognito browsing 127.0.0.1:1210 is also logged in.
- The result is the same if I point both instances to domain.com.  It's only using 127.0.0.1:1210 on both this issue does not occur.

I'm starting to wonder if the issue lies in cookies and the domain set as APP_URL in .env (which in this case is domain.com).

For reference, I'm attaching my NGINX config:

```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
server {
    listen 443 ssl;
    include /etc/nginx/snippets/self-signed-domain.com.conf;
    include /etc/nginx/snippets/ssl-params.conf;
    server_name domain.com;
    root /var/www/html/public;
    index index.php;

    location = /index.php {
        # Ensure that there is no such file named "not_exists"
        # in your "public" directory.
        try_files /not_exists @swoole;
    }
    # any php files must not be accessed
    #location ~* \.php$ {
    #    return 404;
    #}
    location / {
        try_files $uri $uri/ @swoole;
    }

    location @swoole {
        set $suffix "";

        if ($uri = /index.php) {
            set $suffix ?$query_string;
        }

        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header Scheme $scheme;
        proxy_set_header SERVER_PORT $server_port;
        proxy_set_header REMOTE_ADDR $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        proxy_buffer_size   128k;
        proxy_buffers   4 256k;
        proxy_busy_buffers_size   256k;

        # IF https
        # proxy_set_header HTTPS "on";

        proxy_pass http://127.0.0.1:1210$suffix;
    }
}
```

**Comment by lagerroos** [comment]
@Arkanius I'm getting back here since I actually managed to get this to work by adding 'auth' to 'instances' config option. Do you see any problems with this configuration? Adding 'web' worked too, but my guess is that using that approach makes Swoole meaningless. I can't see how 'auth' would make the effect, what do you think? Any opinions?

**Comment by Arkanius** [comment]
@lagerroos  Sounds a little weird to me that adding "auth" at "instances" solved your problem because it's already at "pre_resolved" isn't it? I don't see it as a problem, just looks like sandbox will clean the "auth" instance twice.

> Do you see any problems with this configuration?

No at all, like I said, it's a little weird imo, because it should be working when "auth" was applied at "pre_resolved", but I don't think it is a problem.

Good job by solving it!

**Comment by lagerroos** [comment]
Since this is still open I'm going to drop my question here.
I've been using nova for a while with Swoole now. It's slowing down the whole application and I have to restart swoole every 15 min. Not optimal. I'm therefore trying to split out nova to php-fpm - no need for swoole and all it's beauty if I'm going to be honest.

Here's my try to an nginx conf which does not work.

`map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
server {
    server_name domain.com;
    root /var/www/html/domain-staging/public/;
    index index.php;
    location = /index.php {
        # Ensure that there is no such file named "not_exists"
        # in your "public" directory.
        try_files /not_exists @swoole;
    }
    location / {
        try_files $uri $uri/ @swoole;
    }
    location /nova/ {
        try_files $uri $uri/ /index.php?$query_string;
        #try_files $uri $uri/ =404; #@swoole;
        location ~ \.php$ {
            fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            include fastcgi_params;
        }
    }
    location @swoole {
        set $suffix "";
        if ($uri = /index.php) {
            set $suffix ?$query_string;
        }
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header Scheme $scheme;
        proxy_set_header SERVER_PORT $server_port;
        proxy_set_header REMOTE_ADDR $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        # IF https
        proxy_set_header HTTPS "on";
        proxy_pass http://127.0.0.1:1216$suffix;
    }
gzip on;
gzip_disable "msie6";
gzip_comp_level 6;
gzip_min_length 1100;
gzip_buffers 16 8k;
gzip_proxied any;
gzip_types
    text/plain
    text/css
    text/js
    text/xml
    text/javascript
    application/javascript
    application/json
    application/xml
    application/rss+xml
    image/svg+xml;
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
    if ($host = domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    server_name domain.com;
    listen 80;
    return 404; # managed by Certbot
}
server {
    if ($host = www.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
        listen 80;
        server_name domain.com www.domain.com;
    return 404; # managed by Certbot
}`

**Comment by Arkanius** [comment]
Please, open another issue about it. I'll close this one since the issue problem is done
