### ISSUE TITLE
PHP 8.0 Support?

### ISSUE THREAD

**Issue by jiangjiang0228** [swooletw/laravel-swoole#454]
I have updated PHP to version 8.0
so... you know

**Comment by Arkanius** [comment]
Hi @jiangjiang0228 !

I'm looking foward to it! Unfortunatelly, I hadn't enough time to test PHP 8 with this package yet, but we have a [branch](https://github.com/swooletw/laravel-swoole/tree/improvement/php8) with php8 support. Do you want to help we to test it? :)

**Comment by jiangjiang0228** [comment]
@Arkanius 
Thx! 
Im using the branch

**Comment by Arkanius** [comment]
Nice! Please, let us know if your app is working properly as it was with the early versions of php

**Comment by slava-vishnyakov** [comment]
Thanks! Just in case anyone is Googling this:

```composer require swooletw/laravel-swoole:dev-improvement/php8``` seems to work

**Comment by kocoten1992** [comment]
Anyone get into any issue ? I've using for a while, didn't got any trouble, just want to let you know!

**Comment by Arkanius** [comment]
@kocoten1992 nice to hear that!

**Comment by amcsi** [comment]
I can confirm that the php8 branch has been working for me fine for a few weeks. It's a personal project though where the website isn't visited often.

**Comment by Arkanius** [comment]
Nice to hear that. So, I think that in a couple weeks it's a good time to release the support to php8

**Comment by Arkanius** [comment]
Nice job. are you using websockets or your app is request based?

**Comment by Arkanius** [comment]
Applied as https://github.com/swooletw/laravel-swoole/releases/tag/v2.8.0

Thanks everyone!
