### ISSUE TITLE
Why predis and not phpredis?

### ISSUE THREAD

**Issue by fibis** [swooletw/laravel-swoole#458]
Laravel recommends more and more `phpredis` as redis driver then `predis`. Is there a reason why `predis` is a requirement for this package and can it be dropped?

**Comment by Arkanius** [comment]
At the time that this package was created the default redis driver of Laravel was predis. After some times the official support of predis was dropped and Laravel recommended everyone to change predis to phpredis. Luckily, they gave up of dropping support to redis.
