### ISSUE TITLE
why every worker make the application , but not share?

### ISSUE THREAD

**Issue by chinawilon** [swooletw/laravel-swoole#46]
```php 
    /**
     * Create application.
     */
    protected function createApplication()
    {
        return $this->application = Application::make($this->framework, $this->basePath);
    }

```
Or, when the worker create application, why not pass the current manger container property. it's makes me confused.

like this.
```php 
    /**
     * Create application.
     */
    protected function createApplication()
    {
        return $this->application = Application::make($this->framework, $this->basePath, $this->container);
    }

```

**Comment by albertcht** [comment]
Hi @chinawilon ,

First, workers cannot share one app container because they are in different processes.

To create(load) a new app is to ensure the original container will not be affected in the request. If anyone did something strange during the request process, for example, unsetting some essential singleton properties, that might cause the whole application crashed.

**Comment by chinawilon** [comment]
hi @albertcht 

感谢你的回答，但是我依然有个疑问。

![image](https://camo.githubusercontent.com/5d7808facc40cb47a23056827d38afa639d7b3ec/68747470733a2f2f692e696d6775722e636f6d2f675150747377462e706e67)

从Swoole Structure 的这张图可以看出，如果一开始application就在master进程里面，那么它将会复制一份到manager进程，然后manager在fork新的worker进程的时候，同样也会复制一份最原始的那个application，我们知道父子进程之间的内存遵守COW（写时复制）， 那也就是说，不管request请求里面如何改变application，都不会影响到manager进程里面的application。也就是说新的worker同样会得到最原始的那个application。不知道是不是我理解错了，还请求指教下。

**Comment by albertcht** [comment]
Hi @chinawilon ,

目前一個 worker 中會含有：一個主架構用的 container，一個 laravel application，每次處理請求時會由 laravel application 經由 sandbox clone 出一份新的 application 去給 http kernel 處理，這個時候 request 過程中會有可能對 laravel application 中預先綁定的 singleton 進行污染，但是 container 無論如何是被隔離開來，在 request 中碰不到的，因此可以確保程式的穩定性

雖說新的 worker 可以獲得一份新的 application，但關鍵點就在於 worker 不會在處理一次請求後就被幹掉重新由 manager 再 fork 一份出來，一個 worker 會被預期處理至少上千個以上的請求，所以以上的情況就會存在
