### ISSUE TITLE
Question about pecl install swoole settings

### ISSUE THREAD

**Issue by MazzMazz** [swooletw/laravel-swoole#466]
When `pecl install swoole` we see the following:

enable sockets supports? [no] : 
enable openssl support? [no] : 
enable http2 support? [no] : 
enable mysqlnd support? [no] : 
enable json support? [no] : 
enable curl support? [no] : 

Is any of this necessary? If not could you update the install wiki for it?

**Comment by Arkanius** [comment]
Hi, you don't need these supports in case of basic utilization of laravel. We'll talk about update the docs but I think it makes sense.

Thanks!
