### ISSUE TITLE
Is this a BUG?

### ISSUE THREAD

**Issue by liamhao** [swooletw/laravel-swoole#472]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

php -v:
```
PHP 8.0.3 (cli) (built: Mar  2 2021 16:37:06) ( NTS gcc x86_64 )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
```
php --ri swoole
```
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.4
Built => Mar 11 2021 14:37:01
coroutine => enabled with boost asm context
trace_log => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```
2. Please provide your Laravel/Lumen version.

php artisan --version
```
Laravel Framework 8.26.1
```

3. Which release version of this package are you using?

composer.json
```
"require": {
    "swooletw/laravel-swoole": "^2.7"
}
```

4. What did you do? If possible, provide a recipe for reproducing the error.

![image](https://user-images.githubusercontent.com/31812811/111018559-844f9900-83f4-11eb-975f-d38cc5bc8e15.png)

5. What did you expect to see?

just donot see this ErrorException forever.

6. What did you see instead?

![image](https://user-images.githubusercontent.com/31812811/111018611-d2649c80-83f4-11eb-800b-3d05213bdcbd.png)

**Comment by Arkanius** [comment]
It is really a bug related to PHP8 deprecation. 

see https://github.com/swooletw/laravel-swoole/pull/4739

**Comment by Arkanius** [comment]
Rollback in https://github.com/swooletw/laravel-swoole/releases/tag/v2.12.1
