### ISSUE TITLE
How app() will work?

### ISSUE THREAD

**Issue by evsign** [swooletw/laravel-swoole#477]
Could you please explain how laravel helper `app(...)` would work?
In doc and in some issues i've seen how has been said that using facades is safe and each request will be bound to the separate container instance, but i don't understand how it will work safely with `app(...)` function.

Currently laravel `app(...)` function looks like this:
```php
function app($make = null, array $parameters = [])
{
    if (is_null($make)) {
        return Container::getInstance();
    }

    return Container::getInstance()->make($make, $parameters);
}
```

and `Containe::getInstance()`:
```php
public static function getInstance()
{
    if (is_null(static::$instance)) {
        static::$instance = new static;
    }

    return static::$instance;
}
```

As i see he stores himself in global static property which could be overwritten if some of request start concurrency io work. Swoole will pause one coroutine and start another where new request can come and container instance will be reseted.

**Comment by evsign** [comment]
Also maybe it's related to https://github.com/swooletw/laravel-swoole/issues/395

**Comment by Arkanius** [comment]
Hi there,

swoole "rebinds" the app container instance at each request. The app is a default rebinding. You can see other cleanings, resets and rebinds at config file.

**Comment by evsign** [comment]
Worker is not asynchronous?

**Comment by Arkanius** [comment]
Yes, but each request has his own container binded
