### ISSUE TITLE
unable to allocate memory

### ISSUE THREAD

**Issue by pslxx** [swooletw/laravel-swoole#478]
`[2021-03-20 13:37:19] production.ERROR: Swoole\Table::set(): failed to set('17478'), unable to allocate memory {"userId":10000109,"exception":"[object] (ErrorException(code: 0): Swoole\\Table::set(): failed to set('17478'), unable to allocate memory at /www/wwwroot/api/vendor/swooletw/laravel-swoole/src/Websocket/Rooms/TableRoom.php:180)`

**Comment by Arkanius** [comment]
Hi, please reopen with our issue template
