### ISSUE TITLE
Bug ! http requests fired room->delete and it collapses

### ISSUE THREAD

**Issue by pslxx** [swooletw/laravel-swoole#479]
http requests completed will fire websocket leave Event

then leave event will preform room->delete method

but room delete only reset  one row that fd as key,,value is empty array

so   the table of fds will More and more big

And then it collapses

![image](https://user-images.githubusercontent.com/8417207/112302357-f61dc180-8cd5-11eb-95b7-ab45e3bf8385.png)

**Comment by Arkanius** [comment]
Please, follow our issue guideline

**Comment by pslxx** [comment]
@Arkanius Can you tell me why this happens and how to fix it

tks~

**Comment by Arkanius** [comment]
I'm not sure if I understood your problem. The fd should be the same for all connections.

**Comment by pslxx** [comment]
> I'm not sure if I understood your problem. The fd should be the same for all connections.

OK,but Http request fired Websocket leave event,  then Websocket leave fired Table::delete method

Table::delete dont remove expired fd,,,,,
