### ISSUE TITLE
WSS protocol is required

### ISSUE THREAD

**Issue by LostNCG** [swooletw/laravel-swoole#48]
Please answer these questions before submitting your issue. Thanks!

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
php => 7.1.17
swoole => 2.1.3

2. Please provide your Laravel/Lumen version.
laravel => 5.6.21

3. Which release version of this package are you using?
version 2.3.6

4. What did you do? If possible, provide a recipe for reproducing the error.
I need to implement secure websocket (WSS), as I can see, laravel-swoole facade didn't provide any config options or method to make it happens.
Currently, I modified the source code on Server/Manager.php line 144
```php
        $this->server = new $server($host, $port, SWOOLE_PROCESS, SWOOLE_SOCK_TCP | SWOOLE_SSL);
```
5. What did you expect to see?
allow to create wss server.

6. What did you see instead?
Modified the source code so WSS can be used, this should be fix.

**Comment by albertcht** [comment]
Hi @LostNCG ,

This feature has been merged in to the release [v2.3.7](https://github.com/swooletw/laravel-swoole/releases/tag/v2.3.7). You can go check it.
