### ISSUE TITLE
Why is it true

### ISSUE THREAD

**Issue by pslxx** [swooletw/laravel-swoole#480]
![image](https://user-images.githubusercontent.com/8417207/112315294-f83b4c80-8ce4-11eb-806b-f201254da334.png)
![image](https://user-images.githubusercontent.com/8417207/112315335-01c4b480-8ce5-11eb-8405-380cab11d802.png)

why?  http request isServerWebsocket return true?

**Comment by pslxx** [comment]
![image](https://user-images.githubusercontent.com/8417207/112932718-00fea900-9151-11eb-8f5f-9ca35fe7b332.png)
![image](https://user-images.githubusercontent.com/8417207/112932724-03610300-9151-11eb-9c28-c1760dff4cd8.png)
![image](https://user-images.githubusercontent.com/8417207/112932725-04923000-9151-11eb-9584-783f97ab17e8.png)



Then the swoole table exploded

**Comment by pslxx** [comment]
Duplicate of #478

**Comment by danilopolani** [comment]
You should definitely review the guidelines to submit an issue. There's no description, you didn't follow the Issue template, the title is meaningless.

What's the point of this discussion? What's the issue? What's the expected behaviour?

**Comment by pslxx** [comment]
> You should definitely review the guidelines to submit an issue. There's no description, you didn't follow the Issue template, the title is meaningless.
> 
> What's the point of this discussion? What's the issue? What's the expected behaviour?

The http request violates the leave event of websocket,
Then call the delete method of RoomClass,
But the delete method did not delete fd, which caused more and more fd of the swoole table, and finally could not allocate memory.

**Comment by daniilpanov** [comment]
Have you solved this problem?

**Comment by pslxx** [comment]
> 你解决了这个问题吗？

no . i am use custom room driver and rewrite delete method
