### ISSUE TITLE
Question about Facade

### ISSUE THREAD

**Issue by AkioSarkiz** [swooletw/laravel-swoole#484]
1. PHP 8, swoole 4.6.6
2. Laravel 8
3. 2.8.1
4. It's not error.
5. -
6. -
7. I have a question. When Websocket facade is available? When I tested this package, have error when I send a message from the "tinker". But, when I send a message from the route, this error not showed. I don't found the answer, when Facade Websoket is initialized.

Error message from tinker:
```
 Target class [swoole.websocket] does not exist.
```

**Comment by Arkanius** [comment]
The main difference is: when running swoole you "changed" your way to run php applications by running it in a console event loop way, this means, every request won't boot your framework again, it'll boot just once and will be reused by other requests. When running with tinker you're not passing by swoole (swolle http: start)
