### ISSUE TITLE
Question: How does this repo compare to Laravel Octane?

### ISSUE THREAD

**Issue by siddjain** [swooletw/laravel-swoole#485]
Between laravel-swoole (this repository) and:
https://github.com/laravel/octane
which is the more mature bug-free product? will both continue to be developed independently? what does future roadmap look like?

**Comment by Arkanius** [comment]
Hi There! 

Well, Swoole isn't a new tool. Laravel took so long to create a solution based on Swoole. With this package, the community could get the advantages of Swoole with the laravel ecosystemm. At this time Octane only accepts the php 8, so, the community will need to keep using the package.

About the future, well, IMO I think Octane will be the first option with the help of all Laravel community (and that's great) and all packages that brings Swoole to Laravel will be less relevant
