### ISSUE TITLE
Controller method as callback not working in websocket route file

### ISSUE THREAD

**Issue by LostNCG** [swooletw/laravel-swoole#49]
Please answer these questions before submitting your issue. Thanks!

Please provide your PHP and Swoole version. (php -v and php --ri swoole)
php => 7.1.17
swoole => 2.1.3

Please provide your Laravel/Lumen version.
laravel => 5.6.21

Which release version of this package are you using?
version 2.3.6

What did you do? If possible, provide a recipe for reproducing the error.
1. create a controller name WebSocketController by using artisan command
```
php artisan make:controller WebSocketController
```
2. create a new function in this controller
```php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class WebSocketController
{
    public function connect($websocket, $request)
    {      
        $websocket->emit('message', "welcome to connect");
    }
}
```
3. modify connect event callback from closure function to string in route/websocket.php
```php
Websocket::on('connect', 'WebSocketController@connect');
```
4. run swoole command reload the code logic
```
php artisan swoole:http reload
```
5. connect to websocket on client side successfully.

What did you see instead?
No message received. (should show "welcome to connect")

**Comment by albertcht** [comment]
Hi @LostNCG ,

Thanks for your bug report, I'm working on it.

**Comment by LostNCG** [comment]
@albertcht , ya, you are right. I miss the namespace
