### ISSUE TITLE
Can i use Coroutine in laravel swoole?

### ISSUE THREAD

**Issue by ilbeygi** [swooletw/laravel-swoole#500]
**Hi**

I want use coroutine in **laravel swoole**.

I google this, But don't found any solution.

please help me.

tanks.

**Comment by Arkanius** [comment]
@ilbeygi Hi!

It isn't recomended. Laravel's environment isn't prepared for coroutines. I recommend you to take a look at [[hyperf](https://github.com/hyperf/hyperf). This framework implements full "power" of swoole
