### ISSUE TITLE
Support for phpredis

### ISSUE THREAD

**Issue by Alexx23** [swooletw/laravel-swoole#508]
This Issue does not attempt to report an error.
It is a suggestion that would surely be highly supported.

I propose that this project stop using predis, and start using phpredis instead. This is supposed to be a high performance HTTP server based on Swoole. Phpredis provide a lot of better performance.
Maybe you could offer that the user of your project decides what to use.

Thanks.

**Comment by Arkanius** [comment]
Agreed! We could work on this!

**Comment by Alexx23** [comment]
When do you think it could be ready?

**Comment by Arkanius** [comment]
Unfortunatelly all mainteiners are really busy on the private life towork on that in the sort time. 

If you want to, we could help you to send this PR in order to contribute to our package :)
