### ISSUE TITLE
Class swoole.room does not exist, anything missed?

### ISSUE THREAD

**Issue by LostNCG** [swooletw/laravel-swoole#51]
Please answer these questions before submitting your issue. Thanks!
> skip first 3 questions unrelated

4. What did you do? If possible, provide a recipe for reproducing the error.
```php
use SwooleTW\Http\Websocket\Facades\Room;
dd(Room::getRooms(5));
```

5. What did you expect to see?
rooms of specific fd

6. What did you see instead?
error shown, Class swoole.room does not exist
![image](https://user-images.githubusercontent.com/11206864/39956683-f492fd00-5617-11e8-90cb-727cebff21bf.png)

Am I miss some configurations?

**Comment by albertcht** [comment]
Hi @LostNCG ,

Not sure where did you call `Room` facade? I tested it under websocket closure, websocket controller, http route closure and http controller, and it worked fine.

**Comment by LostNCG** [comment]
@albertcht , you are right, I access the page on wrong port.
The sender will leave the rooms automatically after disconnect event right?
If yes, how can I do if I need to trigger some function (like remove user from online name list)
like:
```php
Websocket::on('disconnecting', function ($websocket) {
    // get disconected user
    $fd = $websocket->getSender();
    // get user's rooms
    $rooms = Room::getRooms($fd);
    // loop rooms name
    foreach ($rooms as $room) {
        // a function to grab room instance implments in adapter design
        $channel = $this->getChannel($room, $fd, auth()->user());
        // trigger leave room event, like remove user from online list
        $channel->leave();
    }
});
```
As I can understance from document, I need to implement my own websocket handler right?

BTW, thank for your fast response on anytime, enjoy your 🍺

**Comment by LostNCG** [comment]
Currently, I will store user's room joined in redis table, I think this is the easier implementation by now.
