### ISSUE TITLE
How to transfer JSON

### ISSUE THREAD

**Issue by g88827929g** [swooletw/laravel-swoole#510]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

PHP 7.4.25

2. Please provide your Laravel/Lumen version.
Laravel8.0

3. Which release version of this package are you using?

"swooletw/laravel-swoole":"v2.10.0"

4. What did you do? If possible, provide a recipe for reproducing the error.
The websocket server could not get the JSON value

5. What did you expect to see?

6. What did you see instead?
I modified **SocketIOParser**, but the server couldn't get the **JSON** value
![test](https://user-images.githubusercontent.com/49873606/142997962-26ec0e7f-bcef-493b-80b4-d46ece65f003.jpg)

**Comment by g88827929g** [comment]
No one knows about it? Is the project dead?

**Comment by Arkanius** [comment]
Hi there! 

I don't know if I understood your problem. This only occours when you try to transfer json?
