### ISSUE TITLE
Can the community release some reports to compare w/ laravel/octane?

### ISSUE THREAD

**Issue by xiaohuilam** [swooletw/laravel-swoole#512]
Can the community release some reports to compare w/ laravel/octane?

I'm wondering if this package an alternative to octane.

**Comment by Arkanius** [comment]
Sure! Make yourself confortable to do this, even to compare with other laravel swoole packages!

This (and others packages) are alternatives to octane and the main reason to this is that all of these packages were created before the octane, so, a lot of users are current running production apps with swoole thanks to these packages.

Please, share the results once they were ready =]
