### ISSUE TITLE
laravel9 install failure

### ISSUE THREAD

**Issue by lingwangchao** [swooletw/laravel-swoole#517]
[root@centos api]# composer require swooletw/laravel-swoole:^2.11
./composer.json has been updated
Running composer update swooletw/laravel-swoole
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires swooletw/laravel-swoole ^2.11 -> satisfiable by swooletw/laravel-swoole[v2.11.0].
    - swooletw/laravel-swoole v2.11.0 requires illuminate/console ~5.4|~6.0|~7.0|~8.0 -> found illuminate/console[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0).

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
[root@centos api]#

**Comment by alecpl** [comment]
I've created #518 to move this forward.

**Comment by Arkanius** [comment]
Fixed in v2.12.x
