### ISSUE TITLE
我做了一些小改进

### ISSUE THREAD

**Issue by mu0641** [swooletw/laravel-swoole#52]
在我的项目里面使用了一些第三的插件，有很多不可预知的static导致了一些小状况，我修改成下面这样解决了我的问题。希望主分支也可以考虑加入这个机制，每次进入沙盒的时候自动重新初始化类对象里面的static 变量。
![image](https://user-images.githubusercontent.com/71642/39957184-387d6484-5621-11e8-8c57-dbf7761620b1.png)
![image](https://user-images.githubusercontent.com/71642/39957193-5c628bfe-5621-11e8-92e2-bb89d84ed849.png)

**Comment by albertcht** [comment]
Hi @mu0641 ,

Thanks for your suggestion. I will do some survey on this and consider to implement this feature.
