### ISSUE TITLE
Routes file changes not picked up until I restart my Docker container

### ISSUE THREAD

**Issue by emachiels** [swooletw/laravel-swoole#530]
**1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)**
PHP version:  8.1.10
Swoole version: 5.0.0

**2. Please provide your Laravel/Lumen version.**
9.27

**3. Which release version of this package are you using?**
2.12.1

**4. What did you do? If possible, provide a recipe for reproducing the error.**
I updated my routes file.

**5. What did you expect to see?**
I expected the new route to work.

**6. What did you see instead?**
Swoole didn't pick up the changes until I restarted my Docker container. I found [this repo](https://github.com/swooletw/watcher) and while that works, I was wondering if there is a better way to check if bootstrapped file changes where you don't need a different watcher running. I couldn't find an issue addressing this, but if there is one, I'm sorry.

**Comment by Arkanius** [comment]
Hi @emachiels,

Sorry my (really) late reply. 

When swoole server is running, it cannot get file changes, the only way to do update your files is by restarting swoole server. The repo you mentioned do exactly this, it watches your files and when a change is observed it kills your current swoole and start it again.

We can do this with many solutions, I use to do this with this watcher and an implemention of node [pm2](https://www.npmjs.com/package/pm2)
