### ISSUE TITLE
[question] does this support mysql persistent connection or mysql connection pooling

### ISSUE THREAD

**Issue by Kristian-Tan** [swooletw/laravel-swoole#531]
This is question rather than issue/bug.

Does this support mysql persistent connection or mysql connection pooling?

https://openswoole.com/docs/modules/mysqli-connection-pool

Quoted from link above:

> Connection pool is used to reduce the TCP reconnect overhead, can be used to increase the application performance.
> You can use the build-in MysqliPool to manage a pool of connection to database servers or remote services.

Edit: after a little observation, it seems that it defaults to using persistent connection (reusing same connection for each workers, the number of active connection in `SHOW FULL PROCESSLIST` equals to `config.swoole_http.worker_num` config), but does not support connection pool. I've also tried to add ```'options' => [ \PDO::ATTR_PERSISTENT => true/false, ],``` in config/database.php inside `connections` item but it still persistent

Observed (cmiiw):
- Persistent connection = supported (default, enforced)
- Non-persistent connection = not supported (cannot configure to non-persistent)
- Connection pool = not supported

**Comment by Arkanius** [comment]
Hi @Kristian-Tan ,

you're right, we dont support connection pool, our implementation uses persistent connection
