### ISSUE TITLE
Can we use Facades or not?

### ISSUE THREAD

**Issue by amcsi** [swooletw/laravel-swoole#60]
Please clarify in the Facades page of the wiki whether or not the basic Facades shipped by Laravel are okay to use or not.

I know that statics that are expected to yield different results in different requests should be avoided when developing under Swoole, because all requests happen under a single CLI call.
What is not clear to me though is whether standard Laravel Facades also count as statics to be avoided, or if they are already written cleverly enough that in such multithreaded event loop contexts they are safe to use.

**Comment by albertcht** [comment]
Hi @amcsi ,

Yes, you can use Facades safely with this package. The app container will be automatically bound to a clean sandbox container in each request. Since each worker can only process one request now, without the consideration for async client or coroutine, it's safe to use facades.

**Comment by amcsi** [comment]
Thank you, that's great news!

**Comment by videni** [comment]
@albertcht , can you explain why it is safe to use facade?  I created a issue [How do you solve the cached resolved instances for facade, it is supposed to be shared by multiple coroutines.](https://github.com/scil/LaravelFly/issues/35),  one instance resolved by a sandbox will be cached in the static variable `resolveInstance` which is shared by all coroutines,   I don't get  the reason why it is safe  in this  package.

**Comment by videni** [comment]
@amcsi , it doesn't safe , check  [How do you solve the cached resolved instances for facade](https://github.com/swooletw/laravel-swoole/issues/549).
