### ISSUE TITLE
app()->runningInConsole() true on HTTP request

### ISSUE THREAD

**Issue by megawubs** [swooletw/laravel-swoole#62]
Please answer these questions before submitting your issue. Thanks!

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
PHP 7.2.5 (cli) (built: Apr 26 2018 12:07:32) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.5, Copyright (c) 1999-2018, by Zend Technologies

swoole

swoole support => enabled
Version => 1.10.5
Author => tianfeng.han[email: mikan.tenny@gmail.com]
kqueue => enabled
rwlock => enabled
async http/websocket client => enabled
pcre => enabled
zlib => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

2. Please provide your Laravel/Lumen version.
Laravel v5.5.40

3. Which release version of this package are you using?
v2.3.8

4. What did you do? If possible, provide a recipe for reproducing the error.
```
app()->runningInConsole()
```

5. What did you expect to see?
`false`

6. What did you see instead?
`true`

Somehow, php thinks it's running from a cli program as `php_sapi_name()` returns `cli` when executed during a http request. This is in essence true as the server is started from a cli command. But can't we somehow tell PHP that we're not running in cli, but from `swoole` or something else?

**Comment by albertcht** [comment]
Hi @megawubs ,

Swoole server can only run in CLI environment. Do you have any special reason to do that?

**Comment by megawubs** [comment]
I'm adding swoole to an existing laravel application and there are several places where there is a check to see if the code is executed inside the cli or not, if so, some actions are not allowed.

**Comment by albertcht** [comment]
Personally I think you need to modify the checking logics in your Laravel application because you can't change the fact that swoole is running in CLI.

**Comment by megawubs** [comment]
I was already looking in to that. Thanks for the help!

**Comment by albertcht** [comment]
No problem.

**Comment by railken** [comment]
@albertcht sorry to write on a dead issue, but i have the same problem.

Using bugsnag the error report doesn't follow a request exception but a console one, here's the cause: https://github.com/bugsnag/bugsnag-laravel/blob/master/src/Request/LaravelResolver.php#L40

I guess there are a lot of others packages that use runningInConsole to check if is a http request or an artisan command. 

Should i write an issue for each of those package or it can be edited somehow here?
