### ISSUE TITLE
Socket.io routes being registered even when Websockets disabled

### ISSUE THREAD

**Issue by benpoulson** [swooletw/laravel-swoole#63]
Please answer these questions before submitting your issue. Thanks!

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
```
php -v
PHP 7.2.4 (cli) (built: Apr 12 2018 02:49:37) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.4, Copyright (c) 1999-2018, by Zend Technologies
```

```
php --ri swoole

swoole

swoole support => enabled
Version => 1.10.5
Author => tianfeng.han[email: mikan.tenny@gmail.com]
kqueue => enabled
rwlock => enabled
async http/websocket client => enabled
http2 => enabled
pcre => enabled
zlib => enabled
```

2. Please provide your Laravel/Lumen version.
`Laravel 5.6.17`

3. Which release version of this package are you using?
`2.3.8`

4. What did you do? If possible, provide a recipe for reproducing the error.
Set SWOOLE_HTTP_WEBSOCKET in `.env` to `false`.

5. What did you expect to see?
`/socket.io` routes not to be registered

6. What did you see instead?
`/socket.io` routes being registered.

**Comment by albertcht** [comment]
Hi @benpoulson ,

Thanks for your reporting, I will make it not require `socket.io` routes if websocket mode is off in the next release.
