### ISSUE TITLE
Laravel PHP Debugbar not working

### ISSUE THREAD

**Issue by aftabnaveed** [swooletw/laravel-swoole#70]
PHP v 7.1.9
Laravel: 5.6

PHP Debugbar is a useful tool that helps you understand the memoray usage  and debug queries etc. It looks like the Laravel extension for it is not working with  Laravel-Swoole: 
https://github.com/barryvdh/laravel-debugbar

Do I need to configure something to make it work?

**Comment by albertcht** [comment]
Hi @aftabnaveed ,

I don't think `laravel-debugbar` can work 100% with this package.

1. `laravel-debugbar` won't be enabled in cli mode. (see: https://github.com/barryvdh/laravel-debugbar/blob/master/src/LaravelDebugbar.php#L760)
2. Even if I forced to enable the debugbar manually, there's still app container pollution problem.
3. To resolve app container pollution, I tried to add the service provider of `laravel-debugbar` but only few collectors work.
4. Some collectors won't be available with this package. For example, application is booted only in the first time, so it's impossible to get booted time on every request in this case.

**Comment by aftabnaveed** [comment]
Do you recommend any profiler that can be used with Swoole?

**Comment by albertcht** [comment]
Hi @aftabnaveed ,

I haven't tried any profiler on Swoole yet. Maybe you can try if [Xdebug](https://github.com/xdebug/xdebug) or [php-spx](https://github.com/NoiseByNorthwest/php-spx) works on Swoole.

But as far as I know, Xdebug doesn't support Swoole's coroutine environment. It should work on Swoole 1.x.

**Comment by aftabnaveed** [comment]
Xdebug works with swoole version 2.x. Stable Version 4.0 is not yet released so it does not make sense to use that at this time. I will close this issue now. Thanks for your help.
