### ISSUE TITLE
Stdout Debug Logs

### ISSUE THREAD

**Issue by aftabnaveed** [swooletw/laravel-swoole#72]
Currently, when a request is served there is no stdout logging served unless I am missing any configurations here? It would be nice not to see only incoming requests but also some debug logs such as `error_log` and `var_dump` in stdout. This will make the debugging of application a lot easier. It also would be great to add how much time the request took to be processed and how much memory it consumed. 

The current code seems to create the HTTP Server via a Manager class which does not have access to the SymfonyCommand to spew out logs. I think the Manager(Http & WebSocket) needs some sort of access to SymfonyCommands to format the messages such as info, warn and error.

**Comment by albertcht** [comment]
Hi @aftabnaveed ,

Did you turn off `ob_output` in `config/swoole_http.php`? You can refer to [Debug Guideline](https://github.com/swooletw/laravel-swoole/wiki/Z3.-Debug-Guideline).

**Comment by aftabnaveed** [comment]
Yes I did disable the ob_output and sorry for not been clear about my question. I am looking for something like this: 

```
11546560                                                                                                               │  66%     34
[24/May/2018:16:38:45 +0000] 172.19.0.9 - - "GET /catalog/product/view/id/34072 HTTP/1.0" 200 347109 "-"               │  75%     50
13175728                                                                                                               │  80%   1380
[24/May/2018:16:39:17 +0000] 172.19.0.9 - - "GET /catalog/product/view/id/34072 HTTP/1.0" 200 346935 "-"               │  90%   2856
14878304                                                                                                               │  95%  11978
[24/May/2018:16:42:07 +0000] 172.19.0.9 - - "GET /catalog/product/view/id/34072 HTTP/1.0" 200 346911 "-"               │  98%  17847
16796656                                                                                                               │  99%  22491
[24/May/2018:16:42:37 +0000] 172.19.0.9 - - "GET /catalog/product/view/id/34072 HTTP/1.0" 200 346889 "-"               │ 100%  30584 (longest request)

```

**Comment by albertcht** [comment]
Hi @aftabnaveed ,

You can create a listener for `swoole.request` event and implement your own logging logics. This event will be triggered on every request.
