### ISSUE TITLE
关于task和协程

### ISSUE THREAD

**Issue by junshenshi** [swooletw/laravel-swoole#73]
Please answer these questions before submitting your issue. Thanks!

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
php 7.2
swoole2.1.3

2. Please provide your Laravel/Lumen version.
laravel5.5

3. Which release version of this package are you using?
2.2.1

如何实现TASK，协程异步IO？
看了src，只看到task push的方法，请问下以后会加入task自定义操作嘛？

**Comment by albertcht** [comment]
Hi @junshenshi ,

Coroutine features are still in develop in branch `feature/coroutine_feature`. It will provide mysql, http coroutine clients and DB connection pool. This feature requires `Swoole 4.0` and will be released after  `Swoole 4.0` stable version comes out.

Async task feature is not supported yet. It will be considered to be supported in the future. I suggest using coroutine clients for asyc I/O(after `feature/coroutine_feature` is released) and using laravel queue for other async task jobs.

**Comment by junshenshi** [comment]
嗨！@albertcht 
OK 刚刚查看了feature/coroutine_feature分支，建议可支持多种协程，
另外希望会有个example目录展示所有功能，以便参考使用。

**Comment by albertcht** [comment]
Hi @junshenshi ,

In the coroutine feature, users will be able to use all the coroutine clients provided by Swoole. I just provide an advanced integration with Eloquent for more elegant usage.
