### ISSUE TITLE
not work with nginx

### ISSUE THREAD

**Issue by wanghongli123** [swooletw/laravel-swoole#77]
Please answer these questions before submitting your issue. Thanks!

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
php: 7.1.6
swoole: 2.2.0

2. Please provide your Laravel/Lumen version.
Laravel: 5.4

3. Which release version of this package are you using?
2.3

4. What did you do? If possible, provide a recipe for reproducing the error.
http {
    server {
		listen 80 default_server;
		listen [::]:80 default_server ipv6only=on;
		autoindex off;
		root /var/www/track/public;
		index index.html index.htm index.php;

		location / {
            proxy_http_version 1.1;
            proxy_set_header Connection "keep-alive";
            proxy_set_header X-Real-IP $remote_addr;
            if (!-e $request_filename) {
                proxy_pass http://192.168.10.2:1215;
            }
        }
    }
}

5. What did you expect to see?
if use nginx, then output /app/public/index.php 's content. swoole server is working, and exec curl http://127.0.0.1:1215 can get right output.

6. What did you see instead?

**Comment by Abbotton** [comment]
WIKI中有详细的nginx配置可供您参考。[see wiki](https://github.com/swooletw/laravel-swoole/wiki/9.-Nginx-Configuration)
