### ISSUE TITLE
webscoket not Effective 

### ISSUE THREAD

**Issue by 775397252** [swooletw/laravel-swoole#80]
## Please provide your Laravel/Lumen version.

laravel5.6

## my question?
when i use this package,i find that i can't connect webscoket,should i configuration nginx same with doc?

**Comment by albertcht** [comment]
Hi @775397252 ,

This is nothing to do with Nginx configs if you connect to swoole server directly. Please follow [Issues Guideline] for providing more detailed information, thanks.
