### ISSUE TITLE
Uncaught SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by george-kar** [swooletw/laravel-swoole#85]
Please answer these questions before submitting your issue. Thanks!

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

2.2.0

2. Please provide your Laravel/Lumen version.

5.6 Laravel

3. Which release version of this package are you using?

latest now 2.3.9

4. What did you do? If possible, provide a recipe for reproducing the error.

php artisan swoole:http start 

5. What did you expect to see?

My app running

6. What did you see instead?

It complains about a javascript file I run with "Uncaught SyntaxError: Unexpected token .". When I run with php artisan serve it works perfect.

**Comment by albertcht** [comment]
Please see #79 #30
