### ISSUE TITLE
Error "Sandbox is not enabled yet"

### ISSUE THREAD

**Issue by george-kar** [swooletw/laravel-swoole#86]
Please answer these questions before submitting your issue. Thanks!

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

PHP 7.2.3-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Mar  6 2018 11:18:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

swoole

swoole support => enabled
Version => 2.2.0
Author => tianfeng.han[email: mikan.tenny@gmail.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

2. Please provide your Laravel/Lumen version.

Laravel Framework 5.6.20

3. Which release version of this package are you using?

Latest 2.3.9

4. What did you do? If possible, provide a recipe for reproducing the error.

php artisan swoole:http start

5. What did you expect to see?

Application

6. What did you see instead?

Alert!: HTTP/1.1 500 Internal Server Error

SwooleTW \ Http \ Exceptions \ SandboxException
   Sandbox is not enabled yet.
     *
     *
     *

   SwooleTW\Http\Exceptions\SandboxException thrown with message "Sandbox is not enabled yet." Stacktrace: #3 SwooleTW\Http\Exceptions\SandboxException in
   /home/forge/backpack.cafepro.gr/vendor/swooletw/laravel-swoole/src/Server/Sandbox.php:120 #2 SwooleTW\Http\Server\Sandbox:getApplication in
   /home/forge/backpack.cafepro.gr/vendor/swooletw/laravel-swoole/src/Server/Sandbox.php:290 #1 SwooleTW\Http\Server\Sandbox:getLaravelApp in
   /home/forge/backpack.cafepro.gr/vendor/swooletw/laravel-swoole/src/Server/Sandbox.php:298 #0 SwooleTW\Http\Server\Sandbox:enable in
   /home/forge/backpack.cafepro.gr/vendor/swooletw/laravel-swoole/src/Server/Manager.php:258 (BUTTON) COPY

**Comment by george-kar** [comment]
should I switch to 2.3.9 will fix the issue?

**Comment by albertcht** [comment]
Hi @george-kar ,

Yes, you can use `v2.3.9` without this issue.

**Comment by george-kar** [comment]
Strange but although I have downgraded

Package operations: 0 installs, 1 update, 0 removals
  - Updating swooletw/laravel-swoole (v2.4.0 => v2.3.9): Loading from cache
Generating autoload files


I have the exact same error :/

**Comment by albertcht** [comment]
Hi @george-kar ,

It looks like a cache problem. The hotfix version `v2.4.1` is now released.

**Comment by george-kar** [comment]
Confirm 2.4.1 fixes the issue
