### ISSUE TITLE
Working example of NGINX config?

### ISSUE THREAD

**Issue by george-kar** [swooletw/laravel-swoole#89]
I have used this configuration with my nginx server

https://github.com/swooletw/laravel-swoole/issues/79

But it looks like it doesn't work. It downloads the index file (php) as plain text.
Can anyone share a working example?

Thanks

**Comment by albertcht** [comment]
Please refer to [Nginx Configuration](https://github.com/swooletw/laravel-swoole/wiki/9.-Nginx-Configuration) in Wiki.
