### ISSUE TITLE
您好Albert  请问下Room::add的一些疑问

### ISSUE THREAD

**Issue by junshenshi** [swooletw/laravel-swoole#9]
试添加ROOM，这些数据是存在内存里的嘛？ restart/stop room存的数据会清空？建议持久化数据 - -

**Comment by junshenshi** [comment]
刚刚测试 如果向不存在的room发送数据，所有人都能收到 - -

**Comment by albertcht** [comment]
Hi @junshenshi ,

目前 Room 是儲存在 swoole table 中，當主進程關閉時數據及會消失，在接下來的規劃中會實作 Redis 的 driver 來達成持久化儲存

請問能貼一下重現 `向不存在的room发送数据，所有人都能收到` 的代碼供參考嗎？

**Comment by junshenshi** [comment]
![_20180426091222](https://user-images.githubusercontent.com/19427115/39280417-eef61000-4931-11e8-8d26-8c28d7770d37.png)
`public function onMessage(Frame $frame)
    {
        Websocket::broadcast()->to('table_name')->emit('message', '222222222222'.json_encode(Room::getClients('table_name')));
    }`
没有添加任何人到table_name里，
除自身外其他fd都能收到信息

**Comment by albertcht** [comment]
Hi @junshenshi ,

這個問題已經在 `develop branch` 中被修復，請參照：[commit 3fdc54c](https://github.com/swooletw/laravel-swoole/commit/3fdc54c43e19ce402b9ce039d63adebcf4f30e85)

`devleop` 和現在 `master` 存在一些差異，之後會等 `develop branch` 一系列 feature 和 bug 修復後一併 merge 回 `master`，屆時文檔會一併更新

**Comment by albertcht** [comment]
Hi @junshenshi ,

在新的 `develop branch` 中已經支援 room 使用 redis 當作 driver，但主要不是以持久化儲存為目的

因為每次主進程重啟時所有客戶端就會斷線，並無法確保下次連線時會拿到一樣的 fd，所以舊有的儲存資料是對不上的

目前如果選用 redis 當 driver，在啟動時會清除所有舊有的資料

**Comment by albertcht** [comment]
Hi @junshenshi ,

新版的程式已經全數合併至 `master branch` 並且更新了文檔，請參考新版使用，謝謝
