### ISSUE TITLE
Benchmark Results Collection

### ISSUE THREAD

**Issue by albertcht** [swooletw/laravel-swoole#90]
Hi everyone,

Thanks for your support to this package. Currently I'm collecting benchmark results in different machine specs and use cases. It will be helpful if you can provide your benchmark result (with fresh new laravel or lumen repo) as comments below. 

It's recommended to use [wrk](https://github.com/wg/wrk) as benchmark tool with the following command:

```
wrk -t4 -c10 http://your.app
```

> You can remove 'web' middleware in `$middlewareGroups` of `App\Http\Kernel::class` to disable session for eliminating I/O factors.

Here's the example format:

* Machine: AWS EC2 / 4 CPUs / 16 GB Memory / PHP 7.2 / Ubuntu 16.04.4 x64
* Swoole Version: 4.0
* PHP Version: 7.2
* Laravel/Lumen Version: Laravel 5.6.3
* Benchmark Result:

```
Running 10s test @ http://laravel-swoole.local
  4 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.34ms    1.59ms  25.69ms   79.53%
    Req/Sec   317.06     43.72   373.00     83.25%
  12637 requests in 10.01s, 30.68MB read
Requests/sec:   1262.17
Transfer/sec:      3.06MB
```

```
Running 10s test @ http://laravel-swoole.local:1215
  4 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.71ms    1.68ms  30.80ms   96.84%
    Req/Sec     1.32k   114.40     1.60k    67.00%
  52488 requests in 10.01s, 126.39MB read
Requests/sec:   5245.17
Transfer/sec:     12.63MB
```

**Comment by codercms** [comment]
Also i think you should to describe what exactly are you benchmarking.
"Hello world" tests isn't representative.

**Comment by albertcht** [comment]
Thanks for your suggestion, basically this is exactly a 'hello world' benchmarking. It will be meaningless if there's too much I/O 
 waiting (like DB query) since this is still synchronous.

I will close this issue first because there are not any feedbacks received and I'm also working on coroutine feature.
