### ISSUE TITLE
want laravel-ide-helper support

### ISSUE THREAD

**Issue by dickwu** [swooletw/laravel-swoole#93]
Please answer these questions before submitting your issue. Thanks!

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

PHP 7.2.6 (cli) (built: May 25 2018 06:18:43) ( NTS )

2. Please provide your Laravel/Lumen version.

lumen 5.6

3. Which release version of this package are you using?

"swooletw/laravel-swoole": "^2.1"

4. What did you do? If possible, provide a recipe for reproducing the error.
https://github.com/barryvdh/laravel-ide-helper
php artisan ide-helper:generate

5. What did you expect to see?

generate right class map file

6. What did you see instead?

Exception: Class swoole.server does not exist
Skipping \SwooleTW\Http\Server\Facades\Server.
Exception: Class swoole.room does not exist
Skipping \SwooleTW\Http\Websocket\Facades\Room.
Exception: Class swoole.websocket does not exist
Skipping \SwooleTW\Http\Websocket\Facades\Websocket.
Exception: Class swoole.server does not exist
Skipping \SwooleTW\Http\Server\Facades\Server.
Exception: Class swoole.room does not exist
Skipping \SwooleTW\Http\Websocket\Facades\Room.
Exception: Class swoole.websocket does not exist
Skipping \SwooleTW\Http\Websocket\Facades\Websocket.

**Comment by Abbotton** [comment]
Hi, @dickwu the laravel-ide-helper skipping those classes , just because the swoole extension is not exists in your develop enviroment. if you realy want, you can just execute the command in your server enviroment, then download the `_ide_helper.php` and replaced the local `_ide_helper.php`. 

maybe the `swoole-ide-helper` package can help you, [see here](https://github.com/easy-swoole/swoole-ide-helper)

wish to help you

**Comment by dickwu** [comment]
@Abbotton I already have swoole extension on my develop enviroment

**Comment by albertcht** [comment]
Hi @dickwu ,

These instances: `swoole.server`, `swoole.room`, `swoole.websocket` will only be registered when you launch your laravel application with this package(`php artisan swoole:http start`). So it's normal laravel-ide-helper can't detect these instances.
