### ISSUE TITLE
Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by cw58665466** [swooletw/laravel-swoole#94]
When I was using

`header("Access-Control-Allow-Origin: *");`

for JS Cross-Origin 

It will report an error

`Cannot modify header information - headers already sent`

This is the environment at Centos

> PHP Version     | 7.1.18                                                     
Swoole Version  | 4.0.1                                                      
Laravel Version | 5.4.36

But when I was using the code in Mac OS X 
> | PHP Version     | 7.2.1                                                                                
| Swoole Version  | 2.0.7                                                                                
| Laravel Version | 5.4.36

The Error will not appear.
Is this question related to the swoole version and how to solve this problem?
Thank you

**Comment by albertcht** [comment]
Hi @cw58665466,

Please read [Notices](https://github.com/swooletw/laravel-swoole/wiki/Z1.-Notices) before opening an issue. (item no. 6)
