### ISSUE TITLE
Does it production ready?

### ISSUE THREAD

**Issue by Barbery** [swooletw/laravel-swoole#95]
Hi, I want to change my laravel's application from php-fpm to swoole, does it production ready?

**Comment by albertcht** [comment]
Hi @Barbery ,

Yes, personally I think this package is ready for production usage. But I can't guarantee you can migrate your original application from php-fpm to swoole without any changes. It heavily depends on if your code follows the guideline.

You can see [Q&A](https://github.com/swooletw/laravel-swoole/wiki/Z4.-Q&A) and [Notices](https://github.com/swooletw/laravel-swoole/wiki/Z1.-Notices) for more information.

**Comment by Barbery** [comment]
thank you!
