### ISSUE TITLE
The nginx configuration causes the laravel routing to fail

### ISSUE THREAD

**Issue by mrzxy** [swooletw/laravel-swoole#96]
This is the environment at Centos
PHP Version | 7.2.4
Swoole Version | 4.0.1
Laravel Version | 5.6

I configured nginx according to the wiki, and when the laravel route was not available, it was fine to remove the following content, but I don't know why.

![image](https://user-images.githubusercontent.com/11501927/42498972-3028c5c2-8460-11e8-966a-935f449672a3.png)

**Comment by litlife** [comment]
Same problem

**Comment by mrzxy** [comment]
thanks
