### ISSUE TITLE
swoole's lock

### ISSUE THREAD

**Issue by yupeng2015** [swooletw/laravel-swoole#97]
Hello, author, I'd like to ask how swoole's lock is used. Can you tell a demo how to use it?
I tried it on my own and found that time out appeared when I was using lock.

**Comment by albertcht** [comment]
Hi @yupeng2015 ,

I'm not quite clear about your question. This package doesn't provide any wrapper for Swoole Lock. If you're asking how you can use Swoole Lock, you should go to [official documentation](https://www.swoole.co.uk/docs/modules/swoole-lock).

**Comment by yupeng2015** [comment]
是这样，我理解的swoole的lock就像go的lock差不多用法。

//启动server时生成一个互斥锁，并且常驻
`$server = new \swoole_lock(SWOOLE_MUTEX); 
.......
$server->lock();
......
.....
(中间代码)
......
........

$server->unlock();`

一个进程访问一个程序，先lock，然后执行中间代码，在unlock之前，其他进程都被阻塞。

但是，swoole实际测试的时候，swoole可能是优化了进程使用。

访问地址，一个进程A，执行程序，先lock，然后执行中间代码。

再访问地址，还是用的进程A，执行程序，先lock，就在lock的时候，直接卡死了。

是不是我的用法有问题，还是说lock时需要判断一下是否开启多个进程？如何判断？

本人刚开始在使用swooletw，这个lock不是很明白。

**Comment by albertcht** [comment]
I think you should submit this issue to official `swoole-src` repo, thanks.
